#!/usr/bin/env python3
"""Generates the CMU military jeep RSIs and their previews.

The jeep is a voxel model (1 voxel = 1 px) rendered for each RSI direction with the oblique 3/4
projection the other vehicles use: screen_x = x, screen_y = -y - z, so top faces and south-facing
faces show. Every pixel remembers which part won the depth test, which is how a direction is split
into layers. Riders sit between the vehicle entity and an overlay entity:

  vehicle entity (under riders)
    jeep_base                    body; brake drums show when the wheels are taken off
    damaged_frame                frame damage
    wheels_0 / wheels_1          intact (animated while moving) / destroyed, like the humvee
    <hardpoint>_0 / _1           intact / damaged look of windshield_up, windshield_down,
                                 wirecutter and searchlight, in the directions they sit under riders
  overlay entity (over riders)
    jeep_overlay, damaged_overlay, wheels_overlay_0 / _1, <hardpoint>_overlay_0 / _1
  turret visual (gunner)         mgturret_0 / mgturret_1, drawn around the pivot like humveeturret_0
  hardpoints.rsi (32 px)         item icons: tires, mgturret, windshield, wirecutter, searchlight
  cargo_straps.rsi (32 px)       tie-downs drawn over a standard crate wrenched into the bed

Empty PRIMARY / ATTACH / WHEEL states are the hidden placeholders hardpoint layers start from.

Run: python Content.CMU/Design/Vehicles/JeepPixelArt/jeep_pixel_art.py
"""
import json
import math
import os
import random
import zlib

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
RSI_DIR = os.path.join(REPO, "Content.CMU", "Resources", "Textures", "CMU14", "Structures", "vehicles", "jeep")
PREVIEW_DIR = os.path.join(REPO, "bin", "jeep-preview")
TEXTURES = os.path.join(REPO, "Resources", "Textures")

SIZE = 96
ICON = 32
DIRS = "SNEW"
WHEEL_FRAMES = 4
WHEEL_DELAY = 0.1
LUGS = 13
COPYRIGHT = "Pixel-art military jeep drawn for CMU, generated by Content.CMU/Design/Vehicles/JeepPixelArt/jeep_pixel_art.py"


def ramp(hi, top, front, dark, line):
    return dict(hi=hi, top=top, front=front, dark=dark, line=line)


PAL = {
    "od": ramp((146, 153, 100), (118, 126, 80), (94, 101, 63), (76, 82, 51), (34, 38, 24)),
    "od_light": ramp((168, 175, 118), (142, 150, 98), (114, 121, 77), (94, 100, 63), (40, 44, 28)),
    "od_in": ramp((104, 110, 70), (86, 92, 58), (72, 77, 48), (60, 64, 40), (30, 33, 21)),
    "od_seam": ramp((94, 101, 63), (76, 82, 51), (72, 78, 49), (56, 61, 38), (34, 38, 24)),
    "frame": ramp((80, 84, 58), (62, 66, 45), (50, 53, 36), (40, 43, 29), (22, 24, 16)),
    "rubber": ramp((86, 86, 82), (66, 66, 64), (52, 52, 51), (42, 42, 41), (20, 20, 20)),
    "groove": ramp((58, 58, 56), (44, 44, 43), (36, 36, 35), (30, 30, 29), (16, 16, 16)),
    "rim": ramp((132, 139, 92), (110, 117, 75), (92, 98, 62), (74, 79, 50), (34, 37, 24)),
    "rim_dk": ramp((80, 86, 56), (64, 69, 45), (54, 58, 38), (46, 49, 32), (26, 28, 18)),
    "hub": ramp((170, 172, 152), (142, 144, 126), (118, 120, 104), (96, 98, 85), (44, 44, 40)),
    "steel": ramp((178, 178, 168), (144, 144, 136), (114, 114, 108), (90, 90, 86), (42, 42, 40)),
    "gun": ramp((118, 120, 120), (82, 84, 85), (64, 66, 67), (50, 52, 53), (20, 21, 22)),
    "canvas": ramp((152, 138, 100), (130, 117, 85), (108, 97, 70), (88, 79, 57), (48, 42, 29)),
    "canvas_seam": ramp((108, 97, 70), (98, 88, 63), (88, 79, 57), (72, 64, 46), (48, 42, 29)),
    "wood": ramp((178, 142, 92), (152, 118, 74), (126, 96, 60), (102, 78, 48), (58, 42, 26)),
    "strap": ramp((212, 192, 128), (188, 168, 108), (162, 144, 92), (132, 116, 74), (78, 68, 42)),
    "white": ramp((242, 242, 232), (228, 228, 216), (206, 206, 196), (178, 178, 168), (140, 140, 130)),
    "lamp": ramp((254, 250, 224), (242, 236, 202), (232, 226, 186), (202, 196, 162), (70, 70, 62)),
    "red": ramp((232, 106, 82), (206, 68, 50), (180, 50, 40), (142, 38, 30), (76, 22, 18)),
    "amber": ramp((242, 192, 92), (224, 162, 62), (198, 136, 46), (162, 106, 34), (80, 52, 18)),
    "black": ramp((70, 70, 70), (44, 44, 44), (34, 34, 34), (28, 28, 28), (14, 14, 14)),
    "char": ramp((60, 56, 50), (42, 39, 35), (34, 31, 28), (28, 26, 23), (12, 11, 10)),
    "yellow": ramp((228, 200, 90), (208, 178, 66), (184, 156, 56), (152, 128, 46), (88, 74, 30)),
    "fuel": ramp((252, 178, 82), (236, 134, 44), (210, 104, 30), (168, 74, 22), (98, 34, 12)),
    "fuel_dk": ramp((210, 104, 30), (176, 76, 24), (150, 60, 20), (120, 46, 16), (80, 26, 10)),
    "axe_red": ramp((214, 92, 80), (184, 56, 48), (156, 40, 36), (124, 30, 28), (70, 18, 16)),
    "etool": ramp((110, 128, 124), (84, 100, 98), (66, 80, 78), (54, 64, 62), (26, 32, 31)),
    "brass": ramp((222, 188, 98), (198, 162, 76), (172, 138, 62), (142, 112, 50), (80, 62, 26)),
    "lit": ramp((255, 252, 230), (255, 248, 214), (255, 244, 200), (250, 236, 180), (240, 224, 160)),
    "lit_red": ramp((255, 120, 96), (255, 92, 70), (240, 70, 54), (220, 56, 44), (190, 40, 32)),
    "lit_brake": ramp((255, 196, 176), (255, 168, 146), (255, 140, 118), (255, 116, 96), (240, 90, 70)),
    "lit_amber": ramp((255, 214, 120), (255, 196, 90), (246, 176, 70), (230, 156, 56), (200, 130, 40)),
    "lens": ramp((250, 246, 222), (236, 230, 196), (226, 220, 182), (206, 200, 164), (120, 116, 96)),
    "lens_dk": ramp((206, 200, 166), (186, 180, 148), (170, 164, 134), (150, 144, 118), (90, 88, 70)),
    "lit_dim": ramp((255, 238, 186), (252, 228, 168), (246, 216, 150), (236, 200, 132), (210, 170, 100)),
    "od_flat": ramp((110, 118, 74), (110, 118, 74), (110, 118, 74), (110, 118, 74), (34, 38, 24)),
    "od_in_flat": ramp((80, 86, 54), (80, 86, 54), (80, 86, 54), (80, 86, 54), (30, 33, 21)),
    "rust": ramp((176, 102, 64), (146, 80, 48), (120, 64, 40), (98, 52, 32), (54, 28, 16)),
}
GLASS = "glass"
GLASS_TINT = (176, 206, 204, 78)
GLASS_SHINE = (232, 244, 242, 150)
MUD = (98, 84, 58)
BODY_MATS = {"od", "od_seam", "frame"}
# Materials shaded as one flat surface: no lines or highlights between pixels of the same part.
FLAT_MATS = {"od_flat", "od_in_flat"}

VARIANTS = ("cargo", "gunner", "transport")
RSI_NAMES = {"cargo": "jeep", "gunner": "jeep_gunner", "transport": "jeep_transport"}

# Body heights (top voxel z): the tub rim is level with the hood like on the real jeep.
RIM = 20
HOOD = 20
FENDER = 18
FRONT_AXLE, REAR_AXLE = 21, -19
# Wheels: centre voxel height, radius, and the rim/hub radii on the outer face.
WHEEL_Z = 8
WHEEL_R = 8.4

# Parts drawn over the riders, per direction. Everything else stays under them.
OVERLAY_PARTS = {
    "S": {"grille", "fender", "bumper", "cowl", "dash", "steering", "chassis_front"},
    "N": {"rear_wall", "taillight", "bumperette", "rear_bench_back", "ammo"},
    "E": {"wall_right"},
    "W": {"wall_left"},
}
WHEEL_PARTS = {"wheel"}

# Hardpoints that sit on the body; each lists the directions where it is drawn over the riders.
ATTACHMENTS = {
    "windshield_up": "S",
    "windshield_down": "S",
    "wirecutter": "S",
    "searchlight": "S",
    "spare": "N",
    "jerrycan": "N",
    "shovel": "W",
    "axe": "W",
    "engine": "",
    "headlights": "S",
}
# What a jeep spawns with; the preview draws these unless told otherwise.
FITTED = ("engine", "headlights", "windshield_up", "spare", "jerrycan", "shovel", "axe")
# Centre r of each headlight, out beside the grille under the fender line.
HEADLIGHTS = (-14, 13)
HEADLIGHT_Z = 13
# The hood lid is drawn over the engine bay; facing south it is also in front of the riders.
HOOD_OVER = "S"
# Past upright, leaning back against the windshield like the real jeep, so the bay stays in view.
HOOD_OPEN_DEGREES = 112
# Lid angle per frame while it swings open (eased); closing plays it backwards.
HOOD_SWING = (0, 9, 26, 50, 76, 98, 112)
HOOD_SWING_DELAY = 0.07
# Fuel filler door on the right-side panel (the tools hang on the left): its span on the outer
# skin, the opened angle and the swing frames.
FUEL_DOOR = dict(f0=-9, f1=-4, z0=10, z1=14)
FUEL_DOOR_OVER = "E"
FUEL_DOOR_SWING = (0, 35, 70, 100)
SMOKE_FRAMES = 8
SMOKE_DELAY = 0.12

# Seats in jeep space: (name, f, r, z of the sitting surface).
SEATS = {
    "cargo": [("driver", -6.5, -10.0, 13), ("passenger", -6.5, 10.0, 13)],
    "gunner": [("driver", -6.5, -10.0, 13), ("passenger", -6.5, 10.0, 13), ("gunner", -23.0, 0.0, 25)],
    "transport": [("driver", -6.5, -10.0, 13), ("passenger", -6.5, 10.0, 13),
                  ("rear_left", -23.5, -10.0, 13), ("rear_right", -23.5, 10.0, 13)],
}
# Row of a 32 px mob sprite that lands on the sitting surface. Mob sprites stand, so a row near the
# hips puts the legs below the rim and the rider reads as seated.
RIDER_HIP_ROW = {"S": 19, "N": 20, "E": 18, "W": 18}
MG_PIVOT = (-16.0, 0.0, 34)
# Cargo slot: footprint of a standard 28 px crate on the bed, and the crate sprite's ground centre.
SLOT = dict(f0=-26, f1=-18, r0=-14, r1=13, floor=8)
CRATE_GROUND_ROW = 26


class Model:
    """Voxels keyed by (f, r, z): f forward, r towards the jeep's right, z up. Values are
    (material, part)."""

    def __init__(self, vox=None):
        self.vox = dict(vox or {})

    def box(self, f0, f1, r0, r1, z0, z1, mat, part):
        for f in range(f0, f1 + 1):
            for r in range(r0, r1 + 1):
                for z in range(z0, z1 + 1):
                    self.vox[(f, r, z)] = (mat, part)

    def mirror_box(self, f0, f1, r0, r1, z0, z1, mat, part, part_left=None):
        """Box on the right (r >= 0) and its mirror on the left (r -> -1 - r)."""
        self.box(f0, f1, r0, r1, z0, z1, mat, part)
        self.box(f0, f1, -1 - r1, -1 - r0, z0, z1, mat, part_left or part)

    def put(self, f, r, z, mat, part):
        self.vox[(f, r, z)] = (mat, part)

    def remove(self, pred):
        for k in [k for k in self.vox if pred(*k)]:
            del self.vox[k]

    def paint(self, pred, mat):
        for k, (_, part) in list(self.vox.items()):
            if pred(*k):
                self.vox[k] = (mat, part)

    def line(self, a, b, mat, part):
        n = int(max(abs(b[i] - a[i]) for i in range(3)) * 2) + 1
        for i in range(n + 1):
            t = i / n
            p = [a[k] + (b[k] - a[k]) * t for k in range(3)]
            self.put(math.floor(p[0]), math.floor(p[1]), math.floor(p[2]), mat, part)

    def without(self, *parts):
        return Model({k: v for k, v in self.vox.items() if v[1] not in parts})

    def merged(self, other):
        return Model({**self.vox, **other.vox})


JERRYCAN_X = [
    "......",
    "#....#",
    ".#..#.",
    ".#..#.",
    "..##..",
    "..##..",
    ".#..#.",
    ".#..#.",
    "#....#",
    "......",
    "......",
]


def noise(*key):
    return zlib.crc32(repr(key).encode()) % 1000 / 1000.0


def wheel_disc(u, v, slice_parity, outer_slice, phase, destroyed=False, radius=WHEEL_R):
    """Material of one voxel of a knobby tyre on a combat rim, or None for air. A destroyed tyre is
    shredded and flat at the bottom, with the rim showing through."""
    d = math.hypot(u, v)
    if d > radius:
        return None
    ang = math.atan2(v, u)
    k = ((ang + phase) / (2 * math.pi / LUGS) + 0.5 * slice_parity) % 1.0
    groove = k < 0.4
    if destroyed:
        if d > 5.6 and (v < -5.6 or noise(u, v, slice_parity) < 0.38):
            return None
        if outer_slice and d <= 5.6:
            if d > 4.9:
                return "char"
            if d < 1.5:
                return "rim_dk"
            return "rim_dk" if noise(u, v) < 0.3 else "rim"
        return "char" if noise(v, u, 7) < 0.5 else "black"
    if d > radius - 0.9 and groove:
        return None
    if outer_slice and d <= 5.6:
        if d > 4.9:
            return "rim_dk"
        if d < 1.7:
            return "hub"
        for n in range(5):
            la = phase * 2.2 + n * 2 * math.pi / 5
            if math.hypot(u - 3.1 * math.cos(la), v - 3.1 * math.sin(la)) < 0.75:
                return "steel"
        return "rim"
    if d > radius - 1.7 and groove:
        return "groove"
    return "rubber"


def wheel(m, fc, zc, r0, r1, phase, clip=None, destroyed=False):
    """Road wheel on an axle along r; the outermost slice shows the rim."""
    outer = r1 if r1 >= 0 else r0
    for a in range(-9, 10):
        for b in range(-9, 10):
            for r in range(r0, r1 + 1):
                if clip and clip(fc + a, r, zc + b):
                    continue
                mat = wheel_disc(a, b, r % 2, r == outer, phase, destroyed)
                if mat:
                    m.put(fc + a, r, zc + b, mat, "wheel")


def stamp(m, bitmap, mat, place):
    """place(col, row) -> voxel key for each set pixel of the bitmap."""
    for row, line in enumerate(bitmap):
        for col, ch in enumerate(line):
            if ch == "#":
                k = place(col, row)
                if k in m.vox:
                    m.vox[k] = (mat, m.vox[k][1])


# Tyres stand a little outboard of the body; anything that would poke into the tub is trimmed.
WHEEL_SPAN = ((16, 22), (-23, -17))


def inside_tub(f, r, z):
    return -19 <= r <= 18 and z >= 6 and f <= 5


def tread_face(m, fc, r0, r1, frame, face, destroyed):
    """A tyre seen end-on: its tread face, as tall as the wheel is wide from the side. face is +1 for
    the front of the tyre (seen facing south), -1 for the back (facing north)."""
    radius = int(WHEEL_R)
    f = fc + radius if face > 0 else fc - radius
    top = 2 * radius - 1
    for z in range(0, top + 1):
        for r in range(r0, r1 + 1):
            if inside_tub(f, r, z):
                continue
            edge = r in (r0, r1)
            if edge and z in (0, top):
                continue
            lug = ((z * face + frame) // 2 + (r % 2)) % 2 == 0
            if destroyed:
                if z > top - 3 and noise(r, z) < 0.6 or noise(z, r, 3) < 0.3:
                    continue
                mat = "char" if lug else "black"
            else:
                if edge and not lug:
                    continue
                mat = "rubber" if lug else "groove"
            m.put(f, r, z, mat, "wheel")


def wheels(view, phase=0.0, destroyed=False):
    m = Model()
    for fc in (FRONT_AXLE, REAR_AXLE):
        for r0, r1 in WHEEL_SPAN:
            if view in "EW":
                wheel(m, fc, WHEEL_Z, r0, r1, phase, inside_tub, destroyed)
            else:
                frame = round(phase / (2 * math.pi / LUGS) * WHEEL_FRAMES)
                tread_face(m, fc, r0, r1, frame, 1 if view == "S" else -1, destroyed)
    if view in "EW":
        # Shadowed wheel well behind the near rear tyre; the far side keeps its plain inner skin.
        r = 18 if view == "E" else -19
        for f in range(REAR_AXLE - 10, REAR_AXLE + 11):
            for z in range(6, RIM):
                if math.hypot(f - REAR_AXLE, z - WHEEL_Z) < WHEEL_R + 0.6:
                    m.put(f, r, z, "frame", "chassis")
    return m


def build(variant):
    """The body without wheels or hardpoints."""
    m = Model()

    # Frame rails, cross members and the brake drums left when the wheels come off.
    m.mirror_box(-29, 30, 8, 10, 2, 5, "frame", "chassis")
    m.box(28, 30, -9, 8, 2, 5, "frame", "chassis_front")
    m.box(-30, -29, -12, 11, 3, 5, "frame", "chassis")
    for fc in (FRONT_AXLE, REAR_AXLE):
        for a in range(-4, 5):
            for b in range(-4, 5):
                d = math.hypot(a, b)
                if d <= 3.8:
                    mat = "hub" if d < 1.2 else "frame"
                    m.mirror_box(fc + a, fc + a, 11, 12, WHEEL_Z + b, WHEEL_Z + b, mat, "chassis")
        m.mirror_box(fc - 1, fc + 1, 9, 10, WHEEL_Z - 1, WHEEL_Z + 1, "frame", "chassis")
        m.box(fc - 1, fc + 1, -17, 16, WHEEL_Z - 1, WHEEL_Z, "frame", "chassis")
    # Steering tie rod ahead of the front axle; both show through the gaps beside the grille.
    m.box(FRONT_AXLE + 5, FRONT_AXLE + 5, -17, 16, WHEEL_Z - 2, WHEEL_Z - 2, "steel", "chassis")
    m.mirror_box(FRONT_AXLE + 3, FRONT_AXLE + 4, 15, 16, WHEEL_Z - 2, WHEEL_Z - 2, "steel", "chassis")

    # Tub: floor, double-skinned walls, rear wheel arches and the step below the door.
    m.box(-30, 5, -20, 19, 6, 7, "od_in", "floor")
    for r in (-17, -13, -9, -5, 4, 8, 12, 16):
        m.box(-28, 3, r, r, 8, 8, "od_in", "floor")
    m.mirror_box(-27, -27, 14, 14, 8, 8, "steel", "floor")
    m.box(-30, 5, 19, 19, 6, RIM, "od", "wall_right")
    m.box(-29, 5, 18, 18, 6, RIM, "od_in", "wall_right")
    d = FUEL_DOOR
    m.remove(lambda f, r, z: r == 19 and d["f0"] <= f <= d["f1"] and d["z0"] <= z <= d["z1"])
    m.box(d["f0"], d["f1"], 18, 18, d["z0"], d["z1"], "black", "wall_right")
    m.box(-7, -6, 19, 19, 11, 13, "steel", "wall_right")
    m.box(-7, -6, 19, 19, 12, 12, "black", "wall_right")
    m.box(-30, 5, -20, -20, 6, RIM, "od", "wall_left")
    m.box(-29, 5, -19, -19, 6, RIM, "od_in", "wall_left")
    m.box(-30, -30, -19, 18, 6, RIM, "od", "rear_wall")
    m.box(-29, -29, -18, 17, 8, RIM, "od_in", "rear_wall")
    m.remove(lambda f, r, z: (f, r) in ((-30, 19), (-30, -20)) and z >= RIM - 1)
    # The rear arch is cut from the outer skin only, so the inner skin hides the tyre from the tub.
    arch = lambda f, z: math.hypot(f + 0.5 - (REAR_AXLE + 0.5), z + 0.5 - (WHEEL_Z + 0.5))
    m.remove(lambda f, r, z: r in (19, -20) and arch(f, z) < WHEEL_R + 0.6)
    m.paint(lambda f, r, z: r in (19, -20) and z == RIM - 2 and f <= 5 and arch(f, z) >= WHEEL_R + 1.6, "od_seam")
    m.mirror_box(-6, -2, 20, 20, 6, 6, "steel", "wall_right", "wall_left")
    for side, part in ((20, "wall_right"), (-21, "wall_left")):
        m.box(-29, -27, side, side, RIM - 1, RIM - 1, "steel", part)
        m.box(-29, -29, side, side, RIM - 2, RIM - 2, "steel", part)
        m.box(-27, -27, side, side, RIM - 2, RIM - 2, "steel", part)

    # Rear wheel housings inside the tub.
    m.mirror_box(-27, -11, 14, 17, 8, 12, "od_in", "hump")

    # Cowl with its vent, and the dash facing the driver.
    m.box(6, 9, -20, 19, 6, HOOD, "od", "cowl")
    m.box(9, 9, -8, 7, 6, HOOD - 1, "od_in", "bay")
    m.box(7, 8, -6, 5, HOOD, HOOD, "od_seam", "cowl")
    m.box(4, 5, -18, 17, 9, HOOD, "od", "dash")
    for rc in (-4, 3):
        m.put(3, rc, HOOD - 2, "lamp", "dash")
        for dr, dz in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            m.put(3, rc + dr, HOOD - 2 + dz, "black", "dash")
    m.box(3, 3, -1, 0, HOOD - 4, HOOD - 4, "steel", "dash")
    m.box(3, 3, 9, 14, HOOD - 5, HOOD - 5, "od_seam", "dash")

    # Engine bay under the hood: aprons, radiator behind the grille, battery. The lid and the engine
    # are separate layers.
    m.box(10, 29, -9, -9, 7, HOOD - 2, "od", "bay")
    m.box(10, 29, 8, 8, 7, HOOD - 2, "od", "bay")
    m.box(10, 29, -8, 7, 6, 6, "frame", "bay")
    m.box(27, 28, -8, 7, 8, HOOD - 2, "black", "bay")
    m.paint(lambda f, r, z: f == 27 and -8 <= r <= 7 and 8 <= z <= HOOD - 2 and z % 2 == 0, "frame")
    m.box(21, 24, 4, 7, 8, 12, "black", "bay")
    m.box(22, 22, 5, 5, 13, 13, "red", "bay")
    m.box(23, 23, 6, 6, 13, 13, "steel", "bay")

    # Grille: slots and the headlights set into it.
    m.box(30, 30, -9, 8, 6, HOOD - 1, "od", "grille")
    for r in (-8, -6, -4, -2, 1, 3, 5, 7):
        m.box(30, 30, r, r, 8, HOOD - 3, "black", "grille")
    # Headlight brackets reaching out from the grille sides; the lamps themselves are a hardpoint.
    m.mirror_box(29, 29, 9, 10, HEADLIGHT_Z, HEADLIGHT_Z, "steel", "grille")

    # Flat fenders with a lip over the tyre, blackout lamps and hood latches on top.
    m.mirror_box(10, 30, 9, 19, FENDER - 1, FENDER, "od", "fender")
    m.mirror_box(30, 30, 9, 19, FENDER - 2, FENDER - 2, "od", "fender")
    m.remove(lambda f, r, z: f == 30 and r in (19, -20) and z == FENDER)
    m.mirror_box(27, 28, 16, 17, FENDER + 1, FENDER + 1, "black", "fender")
    m.mirror_box(28, 28, 16, 16, FENDER + 1, FENDER + 1, "amber", "fender")
    m.mirror_box(25, 25, 9, 9, FENDER + 1, FENDER + 1, "steel", "fender")

    # C-channel bumper with shackles and stencils.
    m.box(31, 32, -20, 19, 3, 6, "od", "bumper")
    m.box(32, 32, -20, 19, 4, 5, "od_seam", "bumper")
    m.mirror_box(33, 33, 12, 13, 4, 5, "steel", "bumper")
    m.paint(lambda f, r, z: f == 32 and z == 5 and r in (-17, -16, -14, -12, 11, 13, 15, 16), "white")

    # Front seats with pleated backs, the tunnel and its levers.
    for r0, r1 in ((4, 15), (-16, -5)):
        seat(m, -11, -3, r0, r1, "seat")
        m.box(-12, -11, r0, r1, 13, 23, "canvas", "seat_back")
        m.paint(lambda f, r, z, r0=r0, r1=r1: f == -12 and r0 <= r <= r1 and (r in (r0, r1) or z in (13, 23)),
                "frame")
        m.box(-12, -12, r0 + 1, r1 - 1, 18, 18, "canvas_seam", "seat_back")
        for rp in (r0 + 3, r0 + 6, r0 + 9):
            m.box(-11, -11, rp, rp, 15, 22, "canvas_seam", "seat_back")
    m.box(-9, 4, -3, 2, 8, 9, "od_in", "tunnel")
    m.box(-2, -2, -1, -1, 10, 15, "black", "tunnel")
    m.box(0, 0, 0, 1, 10, 14, "black", "tunnel")
    steering_wheel(m)

    # Rear panel: tail lights, bumperettes, pintle, and the spare and jerry can mounts.
    m.mirror_box(-31, -31, 15, 19, 3, 5, "od", "bumperette")
    m.mirror_box(-31, -31, 16, 17, 11, 12, "red", "taillight")
    m.mirror_box(-31, -31, 16, 17, 13, 13, "black", "taillight")
    m.mirror_box(-31, -31, 17, 18, 14, 15, "amber", "taillight")
    m.box(-32, -31, -1, 0, 3, 4, "steel", "bumperette")
    m.box(-31, -31, 6, 8, 13, 15, "steel", "rear_wall")
    m.box(-31, -31, -17, -10, 7, 7, "steel", "rear_wall")
    m.box(-31, -31, -17, -17, 8, RIM - 2, "steel", "rear_wall")
    m.box(-31, -31, -10, -10, 8, RIM - 2, "steel", "rear_wall")

    # Tool brackets under the driver's door.
    for f in (-6, -2):
        m.box(f, f, -21, -21, 10, 10, "steel", "wall_left")
        m.box(f, f, -21, -21, 14, 14, "steel", "wall_left")

    if variant == "cargo":
        cargo_bed(m)
    elif variant == "transport":
        seat(m, -27, -21, -16, 15, "rear_bench")
        m.box(-27, -21, -1, 0, 12, 12, "canvas_seam", "rear_bench")
        m.box(-29, -28, -16, 15, 8, 23, "canvas", "rear_bench_back")
        for rp in (-13, -9, -5, 4, 8, 12):
            m.box(-28, -28, rp, rp, 13, 22, "canvas_seam", "rear_bench_back")
    else:
        gun_mount(m)
    return m


def seat(m, f0, f1, r0, r1, part):
    """Canvas cushion on a tube frame standing on four legs, so the floor shows under it."""
    for f in (f0, f1):
        for r in (r0, r1):
            m.put(f, r, 8, "frame", part)
    m.box(f0, f1, r0, r1, 9, 9, "frame", part)
    m.box(f0, f1, r0, r1, 10, 12, "canvas", part)
    m.paint(lambda f, r, z: m.vox[(f, r, z)][1] == part and z == 12 and f == (f0 + f1) // 2, "canvas_seam")


def steering_wheel(m):
    """Nearly upright rim on the driver's side, its top leaning towards the dash: a ring from behind,
    an arc over the dash from the front, a thin slanted line from the side."""
    hub = (1.0, -9.5, HOOD + 0.5)
    radius = 3.6
    tilt = math.radians(30)
    up = (math.sin(tilt), 0.0, math.cos(tilt))

    def at(a, rad=radius):
        return (hub[0] + rad * math.sin(a) * up[0], hub[1] + rad * math.cos(a), hub[2] + rad * math.sin(a) * up[2])

    for i in range(360):
        p = at(i * 2 * math.pi / 360)
        m.put(math.floor(p[0]), math.floor(p[1]), math.floor(p[2]), "black", "steering")
    for a in (0.0, math.pi, -math.pi / 2):
        m.line(hub, at(a, radius - 0.6), "gun", "steering")
    m.put(math.floor(hub[0]), math.floor(hub[1]), math.floor(hub[2]), "steel", "steering")
    m.line((4.5, -9.5, HOOD - 4.0), hub, "black", "steering")


def cargo_bed(m):
    """Flat bed with the slot a standard crate is dragged into and wrenched down."""
    s = SLOT
    for r in (-10, -4, 3, 9):
        m.box(-28, -14, r, r, 8, 8, "steel", "floor")
    for f, df in ((s["f0"], 1), (s["f1"], -1)):
        for r, dr in ((s["r0"], 1), (s["r1"], -1)):
            m.box(min(f, f + 2 * df), max(f, f + 2 * df), r, r, 8, 8, "yellow", "floor")
            m.box(f, f, min(r, r + 2 * dr), max(r, r + 2 * dr), 8, 8, "yellow", "floor")
            m.put(f - df, r - dr, 8, "steel", "floor")
    for r in (-17, 16):
        m.box(-25, -21, r, r, 8, 8, "strap", "floor")
        m.box(-20, -20, r, r, 8, 8, "steel", "floor")


def gun_mount(m):
    """Pedestal for the turret, the gunner's stool, diamond plate and ammo cans."""
    pz = int(MG_PIVOT[2])
    m.box(-19, -14, -3, 2, 8, 8, "steel", "pedestal")
    m.box(-17, -16, -1, 0, 9, pz - 1, "steel", "pedestal")
    for corner in ((-19, -3), (-19, 2), (-14, -3), (-14, 2)):
        m.line((corner[0] + 0.5, corner[1] + 0.5, 9.0), (-16.0, 0.0, 15.0), "steel", "pedestal")
    m.box(-28, -19, -7, 6, 8, 8, "steel", "floor")
    m.paint(lambda f, r, z: z == 8 and -28 <= f <= -19 and -7 <= r <= 6 and (f + r) % 2 == 0, "gun")
    m.box(-24, -23, -1, 0, 9, 23, "steel", "gunner_seat")
    m.box(-25, -22, -2, 1, 24, 24, "canvas", "gunner_seat")
    for r0, r1 in ((12, 17), (-18, -13)):
        m.box(-28, -24, r0, r1, 8, 12, "od", "ammo")
        m.box(-28, -26, r0, r1, 13, 15, "od", "ammo")
        m.box(-24, -24, r0, r1, 10, 10, "yellow", "ammo")
        m.box(-26, -26, r0, r1, 14, 14, "yellow", "ammo")
        m.box(-27, -27, r0 + 2, r1 - 2, 16, 16, "steel", "ammo")


# ---------------------------------------------------------------- hardpoints

def windshield_up(damaged=False):
    """Raked frame on the cowl: posts, top bar, centre divider, wipers and hinges."""
    m = Model()
    z0 = HOOD + 1
    for z in range(z0, z0 + 12):
        f = 8 - (z - z0) // 3
        for r in range(-20, 20):
            frame = z in (z0, z0 + 11) or r in (-20, 19, -1, 0)
            m.put(f, r, z, "od" if frame else GLASS, "windshield")
    for r0 in (-12, 7):
        m.box(5, 5, r0, r0 + 4, z0 + 9, z0 + 9, "black", "windshield")
    m.mirror_box(8, 8, 19, 19, z0, z0, "steel", "windshield")
    if damaged:
        m.paint(lambda f, r, z: r in (-1, 0) and z > z0 + 6, "char")
    return m


def windshield_down(damaged=False):
    """Windshield folded flat onto the hood, clear of the gun."""
    m = Model()
    z = HOOD + 1
    for f in range(8, 19):
        for r in range(-20, 20):
            frame = f in (8, 18) or r in (-20, 19, -1, 0)
            m.put(f, r, z, "od" if frame else GLASS, "windshield")
    m.mirror_box(7, 7, 19, 19, HOOD - 1, HOOD, "steel", "windshield")
    if damaged:
        m.paint(lambda f, r, zz: f == 18 and r in (-20, -19, -18, 12, 13), "char")
    return m


def wirecutter(damaged=False):
    """Notched wire-cutter post on the front bumper."""
    m = Model()
    top = 27
    bend = 3 if damaged else 0
    for z in range(4, top + 1):
        lean = bend * max(0, z - 18) // 9
        m.box(33 + lean, 33 + lean, -1, 0, z, z, "steel", "wirecutter")
        if z >= 7:
            m.put(34 + lean, -1, z, "frame", "wirecutter")
    for z in (22, 23, 25, 26):
        lean = bend * max(0, z - 18) // 9
        m.box(35 + lean, 35 + lean, -1, 0, z, z, "steel", "wirecutter")
    m.line((33.5, -0.5, 12.0), (31.5, -7.5, 6.5), "frame", "wirecutter")
    m.line((33.5, -0.5, 12.0), (31.5, 6.5, 6.5), "frame", "wirecutter")
    if damaged:
        m.paint(lambda f, r, z: 14 <= z <= 20 and (f + z) % 3 == 0, "char")
    return m


def searchlight(damaged=False):
    """Pivoting searchlight on the cowl by the driver's windshield post."""
    m = Model()
    z0 = HOOD + 1
    m.box(7, 8, -18, -17, z0, z0, "steel", "searchlight")
    m.box(7, 7, -18, -17, z0 + 1, z0 + 1, "steel", "searchlight")
    m.box(5, 9, -19, -16, z0 + 2, z0 + 4, "gun", "searchlight")
    m.box(10, 10, -19, -16, z0 + 2, z0 + 4, "black", "searchlight")
    m.box(10, 10, -18, -17, z0 + 3, z0 + 3, "char" if damaged else "lamp", "searchlight")
    m.box(10, 10, -18, -18, z0 + 4, z0 + 4, "white" if not damaged else "black", "searchlight")
    m.box(4, 4, -18, -17, z0 + 3, z0 + 3, "steel", "searchlight")
    if damaged:
        m.put(10, -17, z0 + 2, "white", "searchlight")
        m.put(10, -19, z0 + 4, "white", "searchlight")
        m.paint(lambda f, r, z: f in (5, 6) and z == z0 + 4, "char")
    return m


# The spare is a full road wheel, as wide as the others, on the carrier behind the rear panel.
SPARE_F = (-38, -32)


def spare(damaged=False):
    """A jeep wheel on the rear carrier, axle along f, rim facing backwards."""
    m = Model()
    width = SPARE_F[1] - SPARE_F[0] + 1
    for a in range(-9, 10):
        for b in range(-9, 10):
            for t in range(width):
                mat = wheel_disc(a, b, t % 2, t == 0, 0.0, destroyed=damaged)
                if mat:
                    m.put(SPARE_F[0] + t, 7 + a, 14 + b, mat, "spare")
    return m


def spare_tread(damaged, view):
    """The spare seen from the side: its tread face, as tall as the wheel, like the tyres seen
    from the front, instead of the disc edge-on."""
    radius = int(WHEEL_R)
    r = 7 + radius if view == "E" else 7 - radius
    top = 2 * radius
    m = Model()
    for z in range(14 - radius, 14 + radius + 1):
        for f in range(SPARE_F[0], SPARE_F[1] + 1):
            edge = f in SPARE_F
            row = z - (14 - radius)
            if edge and row in (0, top):
                continue
            lug = (row // 2 + (f % 2)) % 2 == 0
            if damaged:
                if row > top - 3 and noise(f, z) < 0.6 or noise(z, f, 5) < 0.3:
                    continue
                mat = "char" if lug else "black"
            else:
                if edge and not lug:
                    continue
                mat = "rubber" if lug else "groove"
            m.put(f, r, z, mat, "spare")
    return m


def jerrycan(damaged=False):
    """Fuel can in its rack, painted like the game's fuel can; a damaged one is holed and leaking."""
    m = Model()
    m.box(-33, -32, -16, -11, 8, RIM - 1, "fuel", "jerrycan")
    m.box(-33, -33, -16, -11, RIM - 4, RIM - 4, "fuel_dk", "jerrycan")
    stamp(m, JERRYCAN_X, "fuel_dk", lambda c, row: (-33, -16 + c, RIM - 1 - row))
    m.box(-33, -33, -11, -11, 10, 14, "white", "jerrycan")
    m.box(-32, -32, -16, -13, RIM, RIM, "fuel_dk", "jerrycan")
    m.box(-32, -32, -16, -16, RIM - 1, RIM, "fuel_dk", "jerrycan")
    m.box(-32, -32, -11, -11, RIM, RIM + 1, "black", "jerrycan")
    m.box(-34, -34, -16, -11, 12, 12, "black", "jerrycan")
    if damaged:
        for r, z in ((-14, 15), (-12, 11)):
            m.put(-33, r, z, "black", "jerrycan")
            for zz in range(4, z):
                if noise(r, zz) < 0.85:
                    m.put(-34 if zz >= 8 else -32, r, zz, "fuel_dk", "jerrycan")
        m.paint(lambda f, r, z: f == -33 and z >= RIM - 3 and r in (-16, -15), "char")
    return m


def shovel(damaged=False):
    """Entrenching tool strapped flat under the driver's door."""
    m = Model()
    m.box(-11, -11, -21, -21, 10, 12, "etool", "shovel")
    m.box(-10, -10, -21, -21, 10, 10, "etool", "shovel")
    m.box(-10, -10, -21, -21, 12, 12, "etool", "shovel")
    m.box(-9, -1, -21, -21, 11, 11, "etool", "shovel")
    m.box(0, 4, -21, -21, 10, 12, "steel", "shovel")
    m.box(5, 5, -21, -21, 11, 11, "steel", "shovel")
    m.box(-6, -6, -22, -22, 10, 12, "black", "shovel")
    m.box(-2, -2, -22, -22, 10, 12, "black", "shovel")
    if damaged:
        m.paint(lambda f, r, z: f >= 2 and z == 12, "char")
    return m


def axe(damaged=False):
    """Fire axe strapped above the shovel."""
    m = Model()
    m.box(-9, 2, -21, -21, 15, 15, "wood", "axe")
    m.box(3, 4, -21, -21, 14, 16, "axe_red", "axe")
    m.box(3, 4, -21, -21, 13, 13, "steel", "axe")
    m.box(2, 2, -21, -21, 16, 16, "axe_red", "axe")
    m.box(-6, -6, -22, -22, 14, 16, "black", "axe")
    m.box(-2, -2, -22, -22, 14, 16, "black", "axe")
    if damaged:
        m.paint(lambda f, r, z: f in (3, 4) and z == 16, "char")
        m.remove(lambda f, r, z: f == 4 and z == 13)
    return m


def hood_lid():
    """The closed hood: painted top with rounded shoulders over a bare underside."""
    m = Model()
    m.box(10, 29, -8, 7, HOOD, HOOD, "od", "hood_lid")
    m.box(10, 29, -8, 7, HOOD - 1, HOOD - 1, "od_in", "hood_lid")
    m.box(10, 29, -9, -9, HOOD - 1, HOOD - 1, "od", "hood_lid")
    m.box(10, 29, 8, 8, HOOD - 1, HOOD - 1, "od", "hood_lid")
    m.paint(lambda f, r, z: f == 10 and z == HOOD, "od_seam")
    return m


def hood_open(degrees=HOOD_OPEN_DEGREES):
    """The lid swung back about its hinge at the cowl, by default until it leans on the windshield."""
    lid = hood_lid()
    if degrees == 0:
        return lid
    flat = {"od": "od_flat", "od_seam": "od_in_flat", "od_in": "od_in_flat"}
    lid = Model({k: (flat.get(mat, mat), part) for k, (mat, part) in lid.vox.items()})
    t = math.radians(degrees)
    hinge_f, hinge_z = 10.0, HOOD + 1.0
    m = Model()
    for (f, r, z), v in lid.vox.items():
        for a in (0.25, 0.75):
            for c in (0.25, 0.75):
                rf, rz = f + a - hinge_f, z + c - hinge_z
                ff = hinge_f + rf * math.cos(t) - rz * math.sin(t)
                zz = hinge_z + rf * math.sin(t) + rz * math.cos(t)
                m.vox[(math.floor(ff), r, math.floor(zz))] = v
    return m


HOODS = {"hood_closed": hood_lid, "hood_open": hood_open}


def fuel_door(degrees=0):
    """Fuel filler door, hinged on its front edge, swung out from the right-side panel."""
    d = FUEL_DOOR
    hinge_f, hinge_r = d["f1"] + 1.0, 20.0
    t = math.radians(degrees)
    m = Model()
    for f in range(d["f0"], d["f1"] + 1):
        for z in range(d["z0"], d["z1"] + 1):
            edge = f in (d["f0"], d["f1"]) or z in (d["z0"], d["z1"])
            mat = "od_seam" if edge else "od"
            if f == d["f0"] and z == 12:
                mat = "steel"
            if f == d["f1"] and z in (d["z0"] + 1, d["z1"] - 1):
                mat = "steel"
            for a in (0.25, 0.75):
                df = f + a - hinge_f
                ff, rr = hinge_f + df * math.cos(t), hinge_r - 0.5 - df * math.sin(t)
                m.vox[(math.floor(ff), math.floor(rr), z)] = (mat, "fuel_door")
    return m


def engine(damaged=False):
    """Four-cylinder engine: block, valve cover, plug leads, air cleaner, manifold, fan."""
    m = Model()
    m.box(13, 24, -6, 5, 8, 16, "gun", "engine")
    m.box(14, 23, -4, 3, 17, 18, "steel", "engine")
    for f in (15, 17, 19, 21):
        m.put(f, 4, 17, "black", "engine")
    m.box(11, 13, -2, 1, 14, 17, "steel", "engine")
    m.box(14, 23, -7, -7, 10, 12, "rust", "engine")
    m.box(22, 23, 4, 5, 15, 17, "black", "engine")
    m.box(25, 25, -4, 3, 10, 15, "steel", "engine")
    m.paint(lambda f, r, z: f == 25 and (r + z) % 3 == 0, "frame")
    if damaged:
        m.paint(lambda f, r, z: z >= 17 and (f + r) % 3 == 0, "char")
        m.paint(lambda f, r, z: r == -6 and z <= 14 and f in (16, 17, 20), "black")
        m.remove(lambda f, r, z: f == 18 and r in (-1, 0) and z == 18)
    return m


def headlight_lamps(lens="lamp", part="headlights", cracked=False):
    """Two big round headlights on brackets beside the grille: a chrome bezel lit from the upper
    left, a darker outer lens ring around a bright centre, and a glint."""
    lit = lens == "lit"
    m = Model()
    for rc in HEADLIGHTS:
        for a in range(-3, 4):
            for b in range(-3, 4):
                d = math.hypot(a, b)
                if d > 3.2:
                    continue
                m.put(30, rc + a, HEADLIGHT_Z + b, "black", part)
                if d > 2.4:
                    mat = "steel" if b - a > 0 else "gun"
                elif d > 1.5:
                    mat = "lit_dim" if lit else "lens_dk"
                else:
                    mat = "lit" if lit else "lens"
                if not lit and (a, b) in ((-1, 1), (-1, 2)):
                    mat = "white"
                if not lit and (a, b) == (1, -1):
                    mat = "lens"
                if cracked and d <= 2.4:
                    mat = "white" if (a + b) % 3 == 0 or a == b else "black"
                m.put(31, rc + a, HEADLIGHT_Z + b, mat, part)
    return m


def headlights(damaged=False):
    """Headlights hardpoint: clear lenses, or shattered ones when damaged."""
    return headlight_lamps(cracked=damaged)


SIGNAL_DELAY = 0.4


def lamps(kind):
    """The lamps lit for one light group: headlights, tail lights, or one side's turn signals
    (front fender marker and rear amber lamp). Left is the driver's side."""
    if kind == "head":
        return headlight_lamps(lens="lit", part="lights")
    m = Model()
    if kind in ("tail", "brake"):
        m.mirror_box(-31, -31, 16, 17, 11, 12, "lit_red" if kind == "tail" else "lit_brake", "lights")
    elif kind == "signal_right":
        m.box(28, 28, 16, 16, FENDER + 1, FENDER + 1, "lit_amber", "lights")
        m.box(-31, -31, 17, 18, 14, 15, "lit_amber", "lights")
    else:
        m.box(28, 28, -17, -17, FENDER + 1, FENDER + 1, "lit_amber", "lights")
        m.box(-31, -31, -19, -18, 14, 15, "lit_amber", "lights")
    return m


LIGHT_GLOW = {"lit": (255, 236, 170), "lit_red": (255, 70, 50), "lit_amber": (255, 180, 70),
              "lit_brake": (255, 84, 62)}
# Light thrown onto the bodywork around each lamp: colour, reach in pixels, peak opacity. Brakes are
# the tail lights burning brighter.
LIGHT_SPILL = {"lit": ((255, 236, 180), 8, 52), "lit_red": ((255, 60, 40), 7, 64),
               "lit_brake": ((255, 66, 44), 11, 118), "lit_amber": ((255, 168, 60), 7, 76)}


def lights_layer(model, view, kind):
    """Lit lamps, a subtle cast of their light over the nearby bodywork, and a soft halo, for an
    unshaded overlay layer."""
    buf, _ = render(model.merged(lamps(kind)), view)
    col = shade(buf)
    lit = {px: (col[px], e[1]) for px, e in buf.items() if e[2] == "lights" and e[1] in LIGHT_GLOW}
    out = {}
    for (x, y), e in buf.items():
        if e[2] == "lights":
            continue
        best = None
        for (lx, ly), (_, mat) in lit.items():
            colour, reach, peak = LIGHT_SPILL[mat]
            d = math.hypot(x - lx, y - ly)
            a = round(peak * (1 - d / reach) ** 2) if d < reach else 0
            if a and (best is None or a > best[3]):
                best = colour + (a,)
        if best:
            out[(x, y)] = best
    for (x, y), (c, mat) in lit.items():
        glow = LIGHT_GLOW[mat]
        for dx in range(-3, 4):
            for dy in range(-3, 4):
                d = math.hypot(dx, dy)
                if d == 0 or d > 3.2:
                    continue
                p = (x + dx, y + dy)
                if p in lit:
                    continue
                out[p] = over(out.get(p), glow + (round(110 * (1 - d / 3.4)),))
    for px, (c, _) in lit.items():
        out[px] = c
    return out


def smoke_frames(view, dy, heavy):
    """Looping smoke leaking from under the hood edges and the grille, trailing back as it rises."""
    rnd = random.Random(seed(view, "smoke", "heavy" if heavy else "light"))
    count = 16 if heavy else 10
    sources = [(rnd.uniform(12, 28), rnd.choice((-9.5, 8.5)), HOOD) for _ in range(count - 2)]
    sources += [(29.5, rnd.uniform(-6, 5), HOOD - 1) for _ in range(2)]
    puffs = [(src, i / count + rnd.uniform(0, 0.08), rnd.uniform(-2.5, 2.5)) for i, src in enumerate(sources)]
    colour = (78, 74, 68) if heavy else (214, 214, 206)
    peak = 235 if heavy else 205
    frames = []
    for k in range(SMOKE_FRAMES):
        px = {}
        for (f, r, z), phase, drift in puffs:
            t = (k / SMOKE_FRAMES + phase) % 1.0
            sx, sy = project(view, f - 8 * t, r + drift * t, z + 1 + (26 if heavy else 20) * t)
            cx, cy = sx + SIZE // 2, sy + SIZE // 2 + dy
            rad = (2.2 + 5.5 * t) if heavy else (1.8 + 4.0 * t)
            alpha = peak * (1 - t * t)
            for x in range(math.floor(cx - rad), math.ceil(cx + rad) + 1):
                for y in range(math.floor(cy - rad), math.ceil(cy + rad) + 1):
                    d = math.hypot(x + 0.5 - cx, y + 0.5 - cy) / rad
                    if d > 1:
                        continue
                    lift = 18 if (x + 0.5 < cx and y + 0.5 < cy) else 0
                    src = tuple(min(255, c + lift) for c in colour) + (round(alpha * (1 - 0.5 * d * d)),)
                    px[(x, y)] = over(px.get((x, y)), src)
        frames.append(px)
    return frames


def over(dst, src):
    """Alpha-composite src over dst, both RGBA tuples."""
    if dst is None:
        return src
    sa, da = src[3] / 255, dst[3] / 255
    out_a = sa + da * (1 - sa)
    if out_a == 0:
        return (0, 0, 0, 0)
    rgb = tuple(round((src[i] * sa + dst[i] * da * (1 - sa)) / out_a) for i in range(3))
    return rgb + (round(out_a * 255),)


HARDPOINTS = {
    "windshield_up": windshield_up,
    "windshield_down": windshield_down,
    "wirecutter": wirecutter,
    "searchlight": searchlight,
    "spare": spare,
    "jerrycan": jerrycan,
    "shovel": shovel,
    "axe": axe,
    "engine": engine,
    "headlights": headlights,
}


def build_mg(damaged=False):
    """Pintle-mounted heavy machine gun; pivot at the origin, barrel towards +f."""
    m = Model()
    m.box(-1, 0, -1, 0, -3, -1, "steel", "mg_mount")
    m.box(-6, 3, -2, 1, 0, 3, "gun", "mg")
    m.box(-5, 2, -2, 1, 3, 3, "gun", "mg")
    m.box(4, 9, -1, 0, 1, 2, "gun", "mg")
    m.paint(lambda f, r, z: 4 <= f <= 9 and z == 2 and f % 2 == 0, "black")
    if damaged:
        m.box(10, 15, 0, 0, 1, 1, "gun", "mg")
        m.box(16, 19, 0, 0, 0, 0, "gun", "mg")
        m.box(19, 20, -1, 0, 0, 0, "char", "mg")
    else:
        m.box(10, 20, 0, 0, 1, 1, "gun", "mg")
        m.box(20, 21, -1, 0, 1, 2, "gun", "mg")
    m.box(2, 2, -1, 0, 4, 4, "gun", "mg")
    m.box(-8, -7, -2, -2, 0, 3, "black", "mg")
    m.box(-8, -7, 1, 1, 0, 3, "black", "mg")
    m.box(-7, -7, -1, 0, 1, 1, "steel", "mg")
    m.box(-2, 3, -6, -3, -2, 2, "od", "mg")
    m.box(-2, 3, -6, -6, 0, 0, "yellow", "mg")
    m.box(0, 1, -3, -3, 2, 2, "brass", "mg")
    if damaged:
        m.paint(lambda f, r, z: r <= -3 and (f + z) % 2 == 0, "char")
        m.paint(lambda f, r, z: -5 <= f <= 1 and z == 3 and (f + r) % 3 == 0, "char")
        m.remove(lambda f, r, z: f == 3 and r == -6 and z >= 1)
    return m


# ---------------------------------------------------------------- rendering

def to_world(view, f, r):
    if view == "X":
        return f, r
    if view == "S":
        return -r, -f
    if view == "N":
        return r, f
    if view == "E":
        return f, -r
    return -f, r


def project(view, f, r, z):
    x, y = to_world(view, f, r)
    return x, -y - z


def render(model, view, parts=None):
    """Z-buffered oblique render: {(col, row): (depth, mat, part, face, voxel)} for opaque voxels,
    and the same for glass. Smaller depth is nearer the viewer."""
    buf = {}
    glass = {}
    for key, (mat, part) in model.vox.items():
        if parts is not None and part not in parts:
            continue
        f, r, z = key
        wx, wy = to_world(view, f + 0.5, r + 0.5)
        xi, yi = math.floor(wx), math.floor(wy)
        target = glass if mat == GLASS else buf
        for face, row, depth in (("top", -(yi + z + 2), yi + 0.5), ("front", -(yi + z + 1), yi)):
            cur = target.get((xi, row))
            if cur is None or depth < cur[0]:
                target[(xi, row)] = (depth, mat, part, face, key)
    return buf, glass


NEIGHBOURS = ((1, 0, 0.75), (-1, 0, 0.75), (0, -1, 1.25), (0, 1, 0.25))


def shade(buf):
    """Colours a depth buffer. A pixel next to a farther surface becomes its material's outline;
    top faces get a lit lip where they fold into the face below and along their west edge; the row
    above an outline on a vertical face falls into shadow; low bodywork picks up mud."""
    edge = set()
    for (x, y), (d, mat, part, _, _) in buf.items():
        for dx, dy, limit in NEIGHBOURS:
            n = buf.get((x + dx, y + dy))
            if mat in FLAT_MATS and n is not None and n[2] == part:
                continue
            if n is None or n[0] > d + limit:
                edge.add((x, y))
                break
    out = {}
    for (x, y), (d, mat, part, face, key) in buf.items():
        pal = PAL[mat]
        if (x, y) in edge:
            col = pal["line"]
        elif face == "top":
            below = buf.get((x, y + 1))
            fold = below is not None and below[3] == "front" and abs(below[0] - (d - 0.5)) < 1e-6
            col = pal["hi"] if fold or (x - 1, y) in edge else pal["top"]
        else:
            col = pal["dark"] if (x, y + 1) in edge else pal["front"]
        z = key[2]
        if mat in BODY_MATS and face == "front" and z <= 9 and (x, y) not in edge:
            if noise(*key) < (10 - z) * 0.07:
                col = tuple((c * 2 + mc) // 3 for c, mc in zip(col, MUD))
        out[(x, y)] = col + (255,)
    return out


def blend(dst, src):
    if dst is None:
        return src
    a = src[3] / 255.0
    return tuple(round(src[i] * a + dst[i] * (1 - a)) for i in range(3)) + (255,)


def glass_color(x, y):
    return GLASS_SHINE if (x + y) % 11 in (0, 1, 5) else GLASS_TINT


def bullet_holes(layer, glass_px, rng_seed, count):
    """Spider-cracked bullet holes punched through the glass pixels of a layer."""
    rnd = random.Random(rng_seed)
    pts = sorted(glass_px)
    for _ in range(min(count, len(pts))):
        x, y = rnd.choice(pts)
        layer[(x, y)] = (16, 18, 16, 235)
        for dx, dy in rnd.sample([(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)], 5):
            for step in range(1, rnd.randint(2, 4)):
                p = (x + dx * step, y + dy * step)
                if p in glass_px:
                    layer[p] = (236, 242, 238, 200)


def layer_of(buf, col, glass, part):
    """Pixels where a part wins the depth test, glass blended over whatever is behind it."""
    layer = {px: col[px] for px, e in buf.items() if e[2] == part}
    glass_px = set()
    for px, (gd, _, gpart, _, _) in glass.items():
        if gpart != part:
            continue
        behind = buf.get(px)
        if behind is not None and behind[0] < gd:
            continue
        layer[px] = blend(layer.get(px), glass_color(*px))
        glass_px.add(px)
    return layer, glass_px


def split_direction(variant, view, dy):
    """One direction split into layer pixel dicts, in canvas coordinates."""
    overlay_parts = OVERLAY_PARTS[view]
    body = build(variant)
    model = body.merged(wheels(view))

    full, _ = render(model, view)
    full_col = shade(full)
    base_parts = {p for _, p in body.vox.values()} - overlay_parts
    base_only, _ = render(body, view, base_parts)
    base_col = shade(base_only)

    layers = {"base": {}, "overlay": {}, "wheels": {}}
    for px, (_, _, part, _, _) in full.items():
        if part in WHEEL_PARTS:
            layers["wheels"][px] = full_col[px]
        elif part in overlay_parts:
            layers["overlay"][px] = full_col[px]
    # The base keeps what the overlay and wheels hide, so the drums show with the wheels off.
    for px, c in base_col.items():
        winner = full.get(px)
        owned = winner is not None and winner[2] in base_parts
        layers["base"][px] = full_col[px] if owned else c

    broken, _ = render(body.merged(wheels(view, destroyed=True)), view)
    broken_col = shade(broken)
    layers["wheels_destroyed"] = {px: broken_col[px] for px, v in broken.items() if v[2] in WHEEL_PARTS}

    for name, make in HARDPOINTS.items():
        for state, damaged in (("0", False), ("1", True)):
            part_model = spare_tread(damaged, view) if name == "spare" and view in "EW" else make(damaged)
            buf, glass = render(model.merged(part_model), view)
            col = shade(buf)
            part = next(iter(part_model.vox.values()))[1]
            layer, glass_px = layer_of(buf, col, glass, part)
            if damaged:
                bullet_holes(layer, glass_px, seed(variant, view, name), 4)
                for px, c in damage(layer, seed(variant, view, name, "scorch"), light=True).items():
                    layer[px] = blend(layer[px], c)
            layers[f"{name}_{state}"] = layer

    def lid_layer(lid):
        buf, _ = render(model.merged(lid), view)
        col = shade(buf)
        return {px: col[px] for px, e in buf.items() if e[2] == "hood_lid"}

    for name, make in HOODS.items():
        layers[name] = lid_layer(make())
    swing = [lid_layer(hood_open(a)) for a in HOOD_SWING]

    frames = []
    for k in range(WHEEL_FRAMES):
        fb, _ = render(body.merged(wheels(view, k * (2 * math.pi / LUGS) / WHEEL_FRAMES)), view)
        fc = shade(fb)
        frames.append({px: fc[px] for px, v in fb.items() if v[2] in WHEEL_PARTS})

    ox, oy = SIZE // 2, SIZE // 2 + dy

    def place(d):
        return {(x + ox, y + oy): c for (x, y), c in d.items()}

    shut, _ = render(model.merged(hood_lid()).merged(fuel_door()), view)
    seats = {}
    for px, (_, _, part, _, key) in full.items():
        if part in SEAT_PARTS and seat_at(key, variant):
            seats.setdefault(seat_at(key, variant), set()).add(px)

    surface = {}
    for px, (_, _, part, face, key) in shut.items():
        if part not in WHEEL_PARTS and part not in CRAYON_SKIP:
            over_riders = (part in overlay_parts or (part == "hood_lid" and view in HOOD_OVER)
                           or (part == "fuel_door" and view in FUEL_DOOR_OVER))
            surface[px] = (*key, face, over_riders)

    out = {k: place(v) for k, v in layers.items()}
    out["surface"] = place(surface)
    out["seats"] = {name: set(place({p: 0 for p in pts})) for name, pts in seats.items()}
    out["wheels_frames"] = [place(f) for f in frames]
    out["hood_swing"] = [place(f) for f in swing]

    def door_layer(door):
        buf, _ = render(model.merged(door), view)
        col = shade(buf)
        return place({px: col[px] for px, e in buf.items() if e[2] == "fuel_door"})

    out["fuel_door_swing"] = [door_layer(fuel_door(a)) for a in FUEL_DOOR_SWING]
    out["lights"] = place(lights_layer(model, view, "tail"))
    out["brake_on"] = place(lights_layer(model, view, "brake"))
    out["headlights_on"] = place(lights_layer(model, view, "head"))
    out["signal_left"] = place(lights_layer(model, view, "signal_left"))
    out["signal_right"] = place(lights_layer(model, view, "signal_right"))
    return out


def view_dy():
    """Vertical shift per direction that centres the body (all variants) in the canvas."""
    out = {}
    for v in DIRS:
        rows = []
        for var in VARIANTS:
            m = build(var).merged(wheels(v)).merged(hood_open()).merged(fuel_door(FUEL_DOOR_SWING[-1]))
            for name, make in HARDPOINTS.items():
                if name != "windshield_down":
                    m = m.merged(make())
            buf, glass = render(m, v)
            rows += [y for (_, y) in buf] + [y for (_, y) in glass]
        out[v] = -round((min(rows) + max(rows)) / 2)
    return out


def seed(*parts):
    return zlib.crc32("/".join(parts).encode())


def damage(pixels, rng_seed, light=False):
    """Scorches, scrapes and bullet holes restricted to the given pixels."""
    rnd = random.Random(rng_seed)
    out = {}
    pts = sorted(pixels)
    if not pts:
        return out
    scale = 3 if light else 1
    for _ in range(max(1 if light else 3, len(pts) // (260 * scale))):
        cx, cy = rnd.choice(pts)
        rad = rnd.uniform(1.5, 3.0) if light else rnd.uniform(2.0, 4.5)
        for (x, y) in pts:
            dd = math.hypot(x - cx, (y - cy) * 1.3)
            if dd < rad and rnd.random() < 0.85 - dd / rad * 0.5:
                out[(x, y)] = (24, 22, 16, rnd.randint(110, 190))
    if light:
        return out
    for _ in range(max(2, len(pts) // 400)):
        x, y = rnd.choice(pts)
        dx = rnd.choice((-1, 1))
        for i in range(rnd.randint(3, 6)):
            p = (x + i * dx, y + (i // 2) * rnd.choice((0, 1)))
            if p in pixels:
                out[p] = (170, 164, 140, 170)
    for _ in range(max(3, len(pts) // 300)):
        x, y = rnd.choice(pts)
        out[(x, y)] = (12, 12, 10, 255)
        for p in ((x + 1, y), (x, y + 1)):
            if p in pixels:
                out[p] = (150, 146, 126, 160)
    return out


def to_image(pixels, size=SIZE):
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    for (x, y), c in pixels.items():
        if 0 <= x < size and 0 <= y < size:
            img.putpixel((x, y), c)
    return img


def rsi_sheet(tiles):
    """Robust's RSI layout: frames row-major in a square-ish grid, each direction's frames in turn."""
    w, h = tiles[0].size
    cols = math.ceil(math.sqrt(len(tiles)))
    rows = math.ceil(len(tiles) / cols)
    out = Image.new("RGBA", (w * cols, h * rows), (0, 0, 0, 0))
    for i, t in enumerate(tiles):
        out.paste(t, ((i % cols) * w, (i // cols) * h))
    return out


def centred(model, view, size, cy=None):
    """A model rendered on its own, centred in a size x size canvas (or at row cy)."""
    buf, glass = render(model, view)
    col = shade(buf)
    px = dict(col)
    for p in glass:
        if p not in buf or buf[p][0] > glass[p][0]:
            px[p] = blend(px.get(p), glass_color(*p))
    xs = [x for x, _ in px]
    ys = [y for _, y in px]
    ox = size // 2 - (min(xs) + max(xs) + 1) // 2
    oy = size // 2 - (min(ys) + max(ys) + 1) // 2 if cy is None else cy
    return to_image({(x + ox, y + oy): c for (x, y), c in px.items()}, size)


# RSI order for 8 directions, as world-space unit vectors (x east, y north).
DIRS8 = {"S": (0, -1), "N": (0, 1), "E": (1, 0), "W": (-1, 0),
         "SE": (1, -1), "SW": (-1, -1), "NE": (1, 1), "NW": (-1, 1)}
# How far the barrel lifts when the gunner aims up.
RAISED_PITCH = 55


def aimed(model, direction, pitch=0.0):
    """The gun turned to a world direction and lifted by pitch degrees about its trunnion,
    resampled in world space so diagonals stay solid. The pintle under it only turns."""
    dx, dy = direction
    n = math.hypot(dx, dy)
    dx, dy = dx / n, dy / n
    cp, sp = math.cos(math.radians(pitch)), math.sin(math.radians(pitch))
    out = Model()
    for (f, r, z), v in model.vox.items():
        tilt = v[1] != "mg_mount"
        for a in (0.25, 0.75):
            for b in (0.25, 0.75):
                for c in (0.25, 0.75):
                    ff, rr, zz = f + a, r + b, z + c
                    if tilt:
                        ff, zz = ff * cp - zz * sp, ff * sp + zz * cp
                    x, y = ff * dx + rr * dy, ff * dy - rr * dx
                    out.vox[(math.floor(x), math.floor(y), math.floor(zz))] = v
    return out


def mg_images(damaged=False, pitch=0.0):
    """Turret overlay frames for the 8 RSI directions, drawn around the pivot."""
    m = build_mg(damaged)
    imgs = []
    for direction in DIRS8.values():
        buf, _ = render(aimed(m, direction, pitch), "X")
        imgs.append(to_image({(x + SIZE // 2, y + SIZE // 2): c for (x, y), c in shade(buf).items()}))
    return imgs


def strap_images():
    """Tie-downs over a standard 32 px crate sprite (28 px wide, lid rows 13-20, front 21-30).
    They run across the jeep: over the lid when it faces north or south, over the lid and down
    the front when it faces east or west."""
    S, D, B, L = (188, 168, 108, 255), (132, 116, 74, 255), (144, 144, 136, 255), (42, 42, 40, 255)
    imgs = []
    for v in DIRS:
        px = {}
        if v in "SN":
            for y in (15, 18):
                for x in range(2, 30):
                    px[(x, y)] = S
                    px[(x, y + 1)] = D
                for x in (19, 20):
                    px[(x, y)] = B
                    px[(x, y + 1)] = L
                px[(1, y)] = px[(30, y)] = L
        else:
            for x in (9, 21):
                for y in range(13, 31):
                    px[(x, y)] = S
                    px[(x + 1, y)] = D
                px[(x, 24)] = B
                px[(x + 1, 24)] = L
        for x0 in (0, 29):
            for (dx, dy) in ((0, 0), (1, 0), (2, 0), (0, -1), (2, -1)):
                px[(x0 + dx, 30 + dy)] = L if dy == 0 else B
        imgs.append(to_image(px, ICON))
    return imgs


def scaled(model, k):
    """Every voxel blown up to a k x k x k block, for icons of small parts."""
    out = Model()
    for (f, r, z), v in model.vox.items():
        for a in range(k):
            for b in range(k):
                for c in range(k):
                    out.vox[(f * k + a, r * k + b, z * k + c)] = v
    return out


def icon_images():
    """Hardpoint item icons, each a 32 px single-direction state."""
    tyre = Model()
    for a in range(-9, 10):
        for b in range(-9, 10):
            for r in range(0, 6):
                mat = wheel_disc(a, b, r % 2, r == 5, 0.0)
                if mat:
                    tyre.put(a, r, b, mat, "wheel")
    small_shield = Model()
    for z in range(0, 12):
        f = -(z // 3)
        for r in range(-13, 13):
            frame = z in (0, 11) or r in (-13, 12, -1, 0)
            small_shield.put(f, r, z, "od" if frame else GLASS, "windshield")
    return {
        "tires": centred(tyre, "E", ICON),
        "mgturret": centred(build_mg(), "E", ICON),
        "windshield": centred(small_shield, "S", ICON),
        "wirecutter": centred(wirecutter(), "E", ICON),
        "searchlight": centred(scaled(searchlight(), 2), "E", ICON),
        "engine": centred(engine(), "S", ICON),
        "headlights": centred(scaled(Model({(f, r - 9 if r > 0 else r + 10, z): v for (f, r, z), v
                                            in headlight_lamps().vox.items()}), 2), "S", ICON),
    }


def seat_offsets(variant, dy):
    """Rider sprite centre per seat and direction, in pixels (x right, y up) from the vehicle origin,
    plus the depth used to draw far riders first."""
    out = {}
    for name, f, r, z in SEATS[variant]:
        out[name] = {}
        for v in DIRS:
            sx, sy = project(v, f, r, z)
            cy = sy + dy[v] - (RIDER_HIP_ROW[v] - 16)
            out[name][v] = dict(px=(round(sx), round(-cy)), depth=to_world(v, f, r)[1])
    return out


def mg_offsets(dy):
    out = {}
    for v in DIRS:
        sx, sy = project(v, *MG_PIVOT)
        out[v] = (round(sx), round(-(sy + dy[v])))
    return out


def crate_offsets(dy):
    """Centre of a standard crate sprite sitting in the cargo slot."""
    s = SLOT
    fc, rc = (s["f0"] + s["f1"] + 1) / 2, (s["r0"] + s["r1"] + 1) / 2
    out = {}
    for v in DIRS:
        sx, sy = project(v, fc, rc, s["floor"])
        out[v] = (round(sx), round(-(sy + dy[v] - (CRATE_GROUND_ROW - 16))))
    return out


CRAYON_SKIP = {"steering", "chassis", "chassis_front"}
FACE_NORMAL = {"S": "+f", "N": "-f", "E": "+r", "W": "-r"}


def write_crayon_map(variant, per_dir):
    """Per-pixel surface lookup for crayon drawings, laid out like an RSI state (S, N, E, W in a
    2x2 grid). A: 0 off the body, 255 drawn under riders, 128 drawn over riders. R = f + 128,
    G = r + 128 (voxel coordinates in jeep space), B = 2 * z + 1 for the face turned to the camera
    in that direction, 2 * z for a top face."""
    tiles = []
    for v in DIRS:
        px = {}
        for (x, y), (f, r, z, face, over) in per_dir[v]["surface"].items():
            px[(x, y)] = (f + 128, r + 128, 2 * z + (1 if face == "front" else 0), 128 if over else 255)
        tiles.append(to_image(px))
    path = os.path.join(RSI_DIR, "crayon_maps")
    os.makedirs(path, exist_ok=True)
    rsi_sheet(tiles).save(os.path.join(path, RSI_NAMES[variant] + ".png"))


# Part under the cursor, for click handling: written to the R channel of the click maps.
CLICK_IDS = {"hood_lid": 1, "fuel_door": 2, "engine": 3, "headlights": 4, "windshield": 5, "spare": 6,
             "jerrycan": 7, "shovel": 8, "axe": 9, "wirecutter": 10, "searchlight": 11, "wheel": 12}
OUTLINE = (255, 232, 150)
# Seat regions in jeep space (f, r, z ranges) for outlines and click ids, per version.
SEAT_PARTS = {"seat", "seat_back", "rear_bench", "rear_bench_back", "gunner_seat"}
SEAT_REGIONS = {
    "driver": ((-12, -3), (-16, -5), (8, 23)),
    "passenger": ((-12, -3), (4, 15), (8, 23)),
    "rear_left": ((-29, -21), (-16, -1), (8, 23)),
    "rear_right": ((-29, -21), (0, 15), (8, 23)),
    "gunner": ((-25, -22), (-2, 1), (9, 24)),
}
SEAT_IDS = {"driver": 13, "passenger": 14, "rear_left": 15, "rear_right": 16, "gunner": 17}


def seat_at(key, variant):
    """Which of this version's seats a voxel belongs to, or None."""
    for name, *_ in SEATS[variant]:
        (f0, f1), (r0, r1), (z0, z1) = SEAT_REGIONS[name]
        if f0 <= key[0] <= f1 and r0 <= key[1] <= r1 and z0 <= key[2] <= z1:
            return name
    return None


def outline(pixels):
    """Hover highlight for a part: a bright rim just outside it and a faint fill inside, so it also
    marks an empty slot where the item goes back."""
    out = {}
    for (x, y) in pixels:
        out[(x, y)] = OUTLINE + (70,)
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                p = (x + dx, y + dy)
                if p not in pixels:
                    out[p] = OUTLINE + (230,)
    return out


def click_scene(variant, view, hood):
    """Every slot filled, so each slot's pixels can be looked up even while it is empty."""
    m = build(variant).merged(wheels(view)).merged(hood).merged(fuel_door())
    for name, make in HARDPOINTS.items():
        if name == "windshield_down":
            continue
        m = m.merged(spare_tread(False, view) if name == "spare" and view in "EW" else make())
    return m


def write_click_maps(variant, dy):
    """Per-pixel part ids (R) with the jeep's silhouette in A, one map with the hood shut and one
    with it open, laid out like an RSI state."""
    path = os.path.join(RSI_DIR, "click_maps")
    os.makedirs(path, exist_ok=True)
    for name, hood in (("hood_closed", hood_lid()), ("hood_open", hood_open())):
        tiles = []
        for v in DIRS:
            buf, glass = render(click_scene(variant, v, hood), v)
            px = {}
            for (x, y), e in buf.items():
                ident = CLICK_IDS.get(e[2], 0)
                if e[2] in SEAT_PARTS and seat_at(e[4], variant):
                    ident = SEAT_IDS[seat_at(e[4], variant)]
                px[(x + SIZE // 2, y + SIZE // 2 + dy[v])] = (ident, 0, 0, 255)
            for (x, y), e in glass.items():
                key = (x + SIZE // 2, y + SIZE // 2 + dy[v])
                if key not in px or px[key][0] == 0:
                    px[key] = (CLICK_IDS["windshield"], 0, 0, 255)
            tiles.append(to_image(px))
        rsi_sheet(tiles).save(os.path.join(path, f"{RSI_NAMES[variant]}_{name}.png"))


def write_meta(path, size, states):
    meta = {"version": 1, "license": "CC-BY-SA-3.0", "copyright": COPYRIGHT,
            "size": {"x": size, "y": size}, "states": states}
    with open(os.path.join(path, "meta.json"), "w", newline="\n") as fh:
        json.dump(meta, fh, indent=2)
        fh.write("\n")


def fresh_dir(path):
    os.makedirs(path, exist_ok=True)
    for old in os.listdir(path):
        os.remove(os.path.join(path, old))


def write_rsi(variant, dy):
    path = os.path.join(RSI_DIR, RSI_NAMES[variant] + ".rsi")
    fresh_dir(path)
    per_dir = {v: split_direction(variant, v, dy[v]) for v in DIRS}
    states = []
    anim = [[WHEEL_DELAY] * WHEEL_FRAMES for _ in DIRS]

    def save(state, tiles, delays=None, directions=4):
        rsi_sheet(tiles).save(os.path.join(path, state + ".png"))
        entry = {"name": state}
        if directions != 1:
            entry["directions"] = directions
        if delays:
            entry["delays"] = delays
        states.append(entry)

    near = {v: v in "EW" for v in DIRS}
    save("jeep_base", [to_image(per_dir[v]["base"]) for v in DIRS])
    save("jeep_overlay", [to_image(per_dir[v]["overlay"]) for v in DIRS])
    save("damaged_frame", [to_image(damage(per_dir[v]["base"], seed(variant, v, "base"))) for v in DIRS])
    save("damaged_overlay", [to_image(damage(per_dir[v]["overlay"], seed(variant, v, "overlay"))) for v in DIRS])
    for name in HOODS:
        save(name, [to_image({} if v in HOOD_OVER else per_dir[v][name]) for v in DIRS])
        save(name + "_overlay", [to_image(per_dir[v][name] if v in HOOD_OVER else {}) for v in DIRS])
    door = lambda v, f, over: to_image(f if (v in FUEL_DOOR_OVER) == over else {})
    for state, frame in (("fuel_door_closed", 0), ("fuel_door_open", -1)):
        save(state, [door(v, per_dir[v]["fuel_door_swing"][frame], False) for v in DIRS])
        save(state + "_overlay", [door(v, per_dir[v]["fuel_door_swing"][frame], True) for v in DIRS])
    door_delays = [[HOOD_SWING_DELAY] * len(FUEL_DOOR_SWING) for _ in DIRS]
    for state, order in (("fuel_door_opening", 1), ("fuel_door_closing", -1)):
        save(state, [door(v, f, False) for v in DIRS for f in per_dir[v]["fuel_door_swing"][::order]],
             delays=door_delays)
        save(state + "_overlay", [door(v, f, True) for v in DIRS for f in per_dir[v]["fuel_door_swing"][::order]],
             delays=door_delays)
    alpha = lambda d: {k for k, c in d.items() if c[3] > 0}
    for name in [n for n in HARDPOINTS if n in ATTACHMENTS]:
        save(name + "_outline", [to_image(outline(alpha(per_dir[v][name + "_0"]))) for v in DIRS])
    save("hood_outline", [to_image(outline(alpha(per_dir[v]["hood_closed"]))) for v in DIRS])
    save("fuel_door_outline", [to_image(outline(alpha(per_dir[v]["fuel_door_swing"][0]))) for v in DIRS])
    save("wheels_outline", [to_image(outline(alpha(per_dir[v]["wheels"]))) for v in DIRS])
    for name, *_ in SEATS[variant]:
        save(f"seat_{name}_outline", [to_image(outline(per_dir[v]["seats"].get(name, set()))) for v in DIRS])
    if variant == "gunner":
        save("mgturret_outline", [to_image(outline({(x, y) for x in range(SIZE) for y in range(SIZE)
                                                    if img.getpixel((x, y))[3] > 0})) for img in mg_images()],
             directions=8)
    save("lights_on", [to_image(per_dir[v]["lights"]) for v in DIRS])
    save("headlights_on", [to_image(per_dir[v]["headlights_on"]) for v in DIRS])
    save("brake_on", [to_image(per_dir[v]["brake_on"]) for v in DIRS])
    blink = [[SIGNAL_DELAY, SIGNAL_DELAY] for _ in DIRS]
    for side in ("signal_left", "signal_right"):
        save(side, [to_image(f) for v in DIRS for f in (per_dir[v][side], {})], delays=blink)
    swing = [[HOOD_SWING_DELAY] * len(HOOD_SWING) for _ in DIRS]
    for state, order in (("hood_opening", 1), ("hood_closing", -1)):
        save(state, [to_image({} if v in HOOD_OVER else f) for v in DIRS for f in per_dir[v]["hood_swing"][::order]],
             delays=swing)
        save(state + "_overlay", [to_image(f if v in HOOD_OVER else {}) for v in DIRS
                                  for f in per_dir[v]["hood_swing"][::order]], delays=swing)
    smoke = [[SMOKE_DELAY] * SMOKE_FRAMES for _ in DIRS]
    for state, heavy in (("engine_smoke_0", False), ("engine_smoke_1", True)):
        save(state, [to_image(f) for v in DIRS for f in smoke_frames(v, dy[v], heavy)], delays=smoke)
    save("wheels_0", [to_image(f) for v in DIRS for f in per_dir[v]["wheels_frames"]], delays=anim)
    save("wheels_1", [to_image(per_dir[v]["wheels_destroyed"]) for v in DIRS])
    save("wheels_overlay_0", [to_image(f if near[v] else {}) for v in DIRS for f in per_dir[v]["wheels_frames"]],
         delays=anim)
    save("wheels_overlay_1", [to_image(per_dir[v]["wheels_destroyed"] if near[v] else {}) for v in DIRS])
    for name, over_dirs in ATTACHMENTS.items():
        for state in ("0", "1"):
            key = f"{name}_{state}"
            save(key, [to_image({} if v in over_dirs else per_dir[v][key]) for v in DIRS])
            save(f"{name}_overlay_{state}", [to_image(per_dir[v][key] if v in over_dirs else {}) for v in DIRS])
    if variant == "gunner":
        save("mgturret_0", mg_images(), directions=8)
        save("mgturret_1", mg_images(damaged=True), directions=8)
        save("mgturret_raised_0", mg_images(pitch=RAISED_PITCH), directions=8)
        save("mgturret_raised_1", mg_images(damaged=True, pitch=RAISED_PITCH), directions=8)
    blank = to_image({})
    for placeholder in ("PRIMARY", "ATTACH", "WHEEL"):
        save(placeholder, [blank], directions=1)
    write_meta(path, SIZE, states)
    write_crayon_map(variant, per_dir)
    write_click_maps(variant, dy)
    return per_dir


def write_small_rsis():
    path = os.path.join(RSI_DIR, "cargo_straps.rsi")
    fresh_dir(path)
    rsi_sheet(strap_images()).save(os.path.join(path, "straps.png"))
    write_meta(path, ICON, [{"name": "straps", "directions": 4}])

    path = os.path.join(RSI_DIR, "hardpoints.rsi")
    fresh_dir(path)
    icons = icon_images()
    for name, img in icons.items():
        img.save(os.path.join(path, name + ".png"))
    write_meta(path, ICON, [{"name": name} for name in icons])
    return icons


# ---------------------------------------------------------------- previews

def load_state(rsi, state, d=0):
    meta = json.load(open(os.path.join(TEXTURES, rsi, "meta.json")))
    w, h = meta["size"]["x"], meta["size"]["y"]
    img = Image.open(os.path.join(TEXTURES, rsi, state + ".png")).convert("RGBA")
    cols = img.width // w
    return img.crop(((d % cols) * w, (d // cols) * h, (d % cols) * w + w, (d // cols) * h + h))


def marine(d):
    """A jungle-camo marine composited from the game's sprites, for rider previews."""
    out = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
    skin = (204, 160, 128)
    for part in ("torso_m", "head_m", "l_leg", "r_leg", "l_arm", "r_arm", "l_hand", "r_hand", "l_foot", "r_foot"):
        p = load_state("Mobs/Species/Human/parts.rsi", part, d)
        px = p.load()
        for y in range(32):
            for x in range(32):
                c = px[x, y]
                if c[3]:
                    px[x, y] = (c[0] * skin[0] // 255, c[1] * skin[1] // 255, c[2] * skin[2] // 255, c[3])
        out.alpha_composite(p)
    for rsi, st in (("_RMC14/Objects/Clothing/Uniforms/Marine/standard/jungle.rsi", "equipped-INNERCLOTHING"),
                    ("_RMC14/Objects/Clothing/Shoes/Boots/jungle.rsi", "equipped-FEET"),
                    ("_RMC14/Objects/Clothing/OuterClothing/Armor/m3/standard/padded/jungle.rsi", "equipped-OUTERCLOTHING"),
                    ("_RMC14/Objects/Clothing/Head/Helmets/m10/standard/jungle.rsi", "equipped-HELMET")):
        try:
            out.alpha_composite(load_state(rsi, st, d))
        except (OSError, KeyError):
            pass
    return out


def crate_sprite():
    base = load_state("_RMC14/Structures/Storage/Crates/ammo.rsi", "base")
    base.alpha_composite(load_state("_RMC14/Structures/Storage/Crates/ammo.rsi", "closed"))
    return base


def paste(dst, src, x, y):
    """alpha_composite that accepts offsets outside the canvas."""
    layer = Image.new("RGBA", dst.size, (0, 0, 0, 0))
    layer.paste(src, (x, y))
    dst.alpha_composite(layer)


def composite(variant, view, per_dir, dy, riders=False, damaged=False, frame=None, loaded=False,
              fitted=FITTED, wheels_on=True, turret=True, hood="hood_closed", smoke=None, lights=False,
              door=0):
    """What the game draws for one direction: vehicle layers, riders, then the overlay entity."""
    v = per_dir[view]
    near = view in "EW"
    st = "1" if damaged else "0"
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    img.alpha_composite(to_image(v["base"]))
    if damaged:
        img.alpha_composite(to_image(damage(v["base"], seed(variant, view, "base"))))
    hardpoints = list(fitted)
    # Vehicle entity: engine, then the hood lid over it, then everything hung on the body.
    if "engine" in hardpoints:
        img.alpha_composite(to_image(v[f"engine_{st}"]))
    if hood and view not in HOOD_OVER:
        img.alpha_composite(to_image(v[hood]))
    if view not in FUEL_DOOR_OVER:
        img.alpha_composite(to_image(v["fuel_door_swing"][door]))
    for name in hardpoints:
        if name != "engine" and view not in ATTACHMENTS[name]:
            img.alpha_composite(to_image(v[f"{name}_{st}"]))
    wheel_px = v["wheels_destroyed"] if damaged else (v["wheels"] if frame is None else v["wheels_frames"][frame])
    if wheels_on:
        img.alpha_composite(to_image(wheel_px))

    def draw_crate():
        cx, cy = crate_offsets(dy)[view]
        paste(img, crate_sprite(), SIZE // 2 + cx - 16, SIZE // 2 - cy - 16)
        paste(img, strap_images()[DIRS.index(view)], SIZE // 2 + cx - 16, SIZE // 2 - cy - 16)

    crate_in_front = view == "N"
    if loaded and variant == "cargo" and not crate_in_front:
        draw_crate()

    def draw_turret():
        ox, oy = mg_offsets(dy)[view]
        paste(img, mg_images(damaged)[DIRS.index(view)], ox, -oy)

    # Facing north the gunner stands between the camera and the gun.
    gun_under_riders = turret and variant == "gunner" and view == "N"
    if gun_under_riders:
        draw_turret()
    if riders:
        sprite = marine(DIRS.index(view))
        offs = seat_offsets(variant, dy)
        for name, o in sorted(offs.items(), key=lambda kv: -kv[1][view]["depth"]):
            x, y = o[view]["px"]
            paste(img, sprite, SIZE // 2 + x - 16, SIZE // 2 - y - 16)
    if loaded and variant == "cargo" and crate_in_front:
        draw_crate()
    img.alpha_composite(to_image(v["overlay"]))
    if damaged:
        img.alpha_composite(to_image(damage(v["overlay"], seed(variant, view, "overlay"))))
    for name in hardpoints:
        if view in ATTACHMENTS[name]:
            img.alpha_composite(to_image(v[f"{name}_{st}"]))
    # Overlay entity: the lid goes after the windshield, which it stands in front of when open.
    if hood and view in HOOD_OVER:
        img.alpha_composite(to_image(v[hood]))
    if view in FUEL_DOOR_OVER:
        img.alpha_composite(to_image(v["fuel_door_swing"][door]))
    if wheels_on and near:
        img.alpha_composite(to_image(wheel_px))
    if lights:
        img.alpha_composite(to_image(v["lights"]))
        if "headlights" in hardpoints and not damaged:
            img.alpha_composite(to_image(v["headlights_on"]))
    if smoke is not None:
        img.alpha_composite(to_image(smoke))
    if turret and variant == "gunner" and not gun_under_riders:
        draw_turret()
    return img


def suspension_bob(frames, rng_seed=7):
    """Body offset in pixels per frame: a damped spring kicked by random bumps, rounded to whole
    pixels, so the jeep settles and jolts instead of bouncing on a fixed rhythm."""
    rnd = random.Random(rng_seed)
    pos, vel = 0.0, 0.0
    out = []
    for _ in range(frames * 4):
        if rnd.random() < 0.18:
            vel += rnd.uniform(-2.2, 2.2)
        vel += -pos * 0.45 - vel * 0.35
        pos += vel * 0.25
        out.append(pos)
    return [max(-1, min(1, round(v))) for v in out[::4]]


def moving(variant, view, per_dir, dy, k, bob):
    """One frame of the moving preview: everything but the wheels shifted by the bob."""
    v = per_dir[view]
    body = composite(variant, view, per_dir, dy, riders=True, loaded=True, wheels_on=False)
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    wheel_px = v["wheels_frames"][k % WHEEL_FRAMES]
    img.alpha_composite(to_image(wheel_px))
    paste(img, body, 0, bob)
    if view in "EW":
        img.alpha_composite(to_image(wheel_px))
    return img


def crayon(layer, over, surface, view, decal, anchor, colour):
    """Paints a crayon decal stored on the body into a body layer (over = the overlay entity's).
    anchor = (f, r, z, normal, right, down), right and down being the decal's axes in jeep space,
    set from the direction it was drawn in. Only pixels showing the same panel take paint, blended
    with the shading underneath."""
    fa, ra, za, normal, right, down = anchor
    src = decal.load()
    for (x, y), (f, r, z, face, is_over) in surface.items():
        if is_over != over or (x, y) not in layer:
            continue
        here = "up" if face == "top" else FACE_NORMAL[view]
        if here != normal:
            continue
        d = {"f": f - fa, "r": r - ra, "z": z - za}
        depth_axis = {"up": "z", "+f": "f", "-f": "f", "+r": "r", "-r": "r"}[normal]
        if abs(d[depth_axis]) > 2:
            continue
        u = 16 + sum(d[a] * k for a, k in right)
        w = 16 + sum(d[a] * k for a, k in down)
        if not (0 <= u < 32 and 0 <= w < 32) or src[u, w][3] == 0:
            continue
        base = layer[(x, y)]
        lum = (base[0] * 3 + base[1] * 6 + base[2]) / 10
        k = max(0.45, min(1.25, lum / 110))
        paint = tuple(min(255, int(c * k)) for c in colour)
        layer[(x, y)] = tuple(round(base[i] * 0.2 + paint[i] * 0.8) for i in range(3)) + (255,)


# Forward, forward-left and forward-right world directions for each jeep facing.
ARC_DIRS = {"S": ("S", "SE", "SW"), "N": ("N", "NW", "NE"), "E": ("E", "NE", "SE"), "W": ("W", "SW", "NW")}


def turret_arc_demo(per, dy):
    """The gunner jeep in each facing with the gun forward, at both ends of its arc, and aimed up."""
    rows = []
    names = list(DIRS8)
    for v in DIRS:
        row = []
        ox, oy = mg_offsets(dy)[v]
        for aim, pitch in [(d, 0.0) for d in ARC_DIRS[v]] + [(ARC_DIRS[v][0], RAISED_PITCH)]:
            img = composite("gunner", v, per["gunner"], dy, turret=False)
            paste(img, mg_images(pitch=pitch)[names.index(aim)], ox, -oy)
            row.append(img)
        rows.append(row)
    return sheet(rows, 3)


def turret_sweep(per, dy, snapped):
    """Frames of the gun swinging slowly across its arc, then aiming up and back down, in every
    facing. snapped mimics Robust: it draws the nearest of the 8 RSI directions and rotates that
    frame by what is left of the angle. Otherwise the gun is re-rendered at every angle."""
    names = list(DIRS8)
    bases = {v: composite("gunner", v, per["gunner"], dy, turret=False) for v in DIRS}
    gun = build_mg()
    sweep = list(range(0, 46, 3)) + [45] * 4 + list(range(45, -46, -3)) + [-45] * 4 + list(range(-45, 1, 3))
    lift = list(range(0, RAISED_PITCH + 1, 5)) + [RAISED_PITCH] * 6 + list(range(RAISED_PITCH, -1, -5))
    steps = [(a, 0) for a in sweep] + [(0, p) for p in lift]
    frames = []
    for angle, pitch in steps:
        row = []
        for v in DIRS:
            dx, dy0 = DIRS8[v]
            t = math.radians(angle)
            aim = (dx * math.cos(t) - dy0 * math.sin(t), dx * math.sin(t) + dy0 * math.cos(t))
            residual = 0.0
            if snapped:
                frame = max(DIRS8.values(), key=lambda d: (d[0] * aim[0] + d[1] * aim[1]) / math.hypot(*d))
                residual = math.degrees(math.atan2(aim[1], aim[0]) - math.atan2(frame[1], frame[0]))
                residual = (residual + 180) % 360 - 180
                aim = frame
                pitch = RAISED_PITCH if pitch > RAISED_PITCH / 2 else 0
            buf, _ = render(aimed(gun, aim, pitch), "X")
            sprite = to_image({(x + SIZE // 2, y + SIZE // 2): c for (x, y), c in shade(buf).items()})
            if residual:
                sprite = sprite.rotate(residual, resample=Image.NEAREST, center=(SIZE // 2, SIZE // 2))
            img = bases[v].copy()
            ox, oy = mg_offsets(dy)[v]
            paste(img, sprite, ox, -oy)
            row.append(img)
        frames.append(sheet([row], 3).convert("RGB"))
    return frames


def crayon_demo(per, dy):
    """A skull drawn on the hood facing south and a heart drawn on the right side facing east,
    shown in every direction."""
    skull = load_state("Effects/crayondecals.rsi", "skull")
    heart = load_state("Effects/crayondecals.rsi", "heart")
    # Facing south, screen right is -r and screen down is +f; facing east, right is +f, down is -z.
    on_hood = (20, 0, HOOD, "up", (("r", -1),), (("f", 1),))
    on_side = (-6, 19, 14, "+r", (("f", 1),), (("z", -1),))
    rows = []
    for var in VARIANTS:
        painted = {}
        for v in DIRS:
            d = dict(per[var][v])
            d["base"], d["overlay"] = dict(d["base"]), dict(d["overlay"])
            for decal, anchor, colour in ((skull, on_hood, (236, 236, 228)), (heart, on_side, (214, 48, 40))):
                crayon(d["base"], False, d["surface"], v, decal, anchor, colour)
                crayon(d["overlay"], True, d["surface"], v, decal, anchor, colour)
            painted[v] = d
        rows.append([composite(var, v, painted, dy) for v in DIRS])
    return sheet(rows, 3)


def sheet(rows, scale, bg=(74, 78, 64, 255), pad=4):
    w = max(len(r) for r in rows) * (SIZE + pad) + pad
    h = len(rows) * (SIZE + pad) + pad
    out = Image.new("RGBA", (w, h), bg)
    for j, r in enumerate(rows):
        for i, im in enumerate(r):
            out.alpha_composite(im, (pad + i * (SIZE + pad), pad + j * (SIZE + pad)))
    return out.resize((w * scale, h * scale), Image.NEAREST)


def main():
    os.makedirs(PREVIEW_DIR, exist_ok=True)
    for old in os.listdir(PREVIEW_DIR):
        os.remove(os.path.join(PREVIEW_DIR, old))
    dy = view_dy()
    per = {var: write_rsi(var, dy) for var in VARIANTS}
    icons = write_small_rsis()

    def grid(scale=3, **kw):
        return sheet([[composite(var, v, per[var], dy, **kw) for v in DIRS] for var in VARIANTS], scale)

    grid().save(os.path.join(PREVIEW_DIR, "jeep_variants.png"))
    grid(riders=True, loaded=True).save(os.path.join(PREVIEW_DIR, "jeep_riders.png"))
    down = ("windshield_down",) + FITTED[1:]
    everything = FITTED + ("wirecutter", "searchlight")
    grid(riders=True, loaded=True, fitted=down).save(os.path.join(PREVIEW_DIR, "jeep_riders_windshield_down.png"))
    grid(damaged=True).save(os.path.join(PREVIEW_DIR, "jeep_damaged.png"))
    grid(fitted=(), wheels_on=False).save(os.path.join(PREVIEW_DIR, "jeep_stripped.png"))
    grid(fitted=everything).save(os.path.join(PREVIEW_DIR, "jeep_hardpoints.png"))
    grid(fitted=everything, damaged=True).save(os.path.join(PREVIEW_DIR, "jeep_hardpoints_damaged.png"))
    for var in VARIANTS:
        rows = [[composite(var, v, per[var], dy, fitted=f) for v in DIRS] for f in (FITTED, down)]
        rows += [[composite(var, v, per[var], dy, riders=True, loaded=True, fitted=f) for v in DIRS]
                 for f in (FITTED, down)]
        sheet(rows, 5).save(os.path.join(PREVIEW_DIR, f"jeep_{var}_x5.png"))
    crayon_demo(per, dy).save(os.path.join(PREVIEW_DIR, "jeep_crayons.png"))
    grid(hood="hood_open").save(os.path.join(PREVIEW_DIR, "jeep_hood_open.png"))
    hover_rows = []
    for var in VARIANTS:
        for fitted in ((), FITTED):
            row = []
            for v in DIRS:
                img = composite(var, v, per[var], dy, fitted=fitted, wheels_on=bool(fitted))
                state_dir = os.path.join(RSI_DIR, RSI_NAMES[var] + ".rsi")
                names = (["spare", "jerrycan", "shovel", "axe", "headlights", "wheels"] if not fitted
                         else ["hood", "fuel_door"])
                for n in names:
                    sheet_img = Image.open(os.path.join(state_dir, n + "_outline.png")).convert("RGBA")
                    d = DIRS.index(v)
                    img.alpha_composite(sheet_img.crop(((d % 2) * SIZE, (d // 2) * SIZE, (d % 2) * SIZE + SIZE,
                                                        (d // 2) * SIZE + SIZE)))
                row.append(img)
            hover_rows.append(row)
    sheet(hover_rows, 3).save(os.path.join(PREVIEW_DIR, "jeep_hover_outlines.png"))
    last = len(FUEL_DOOR_SWING) - 1
    door_seq = list(range(last + 1)) + [last] * 8 + list(range(last, -1, -1)) + [0] * 8
    door_frames = [sheet([[composite(var, v, per[var], dy, door=k) for v in ("E", "S", "N")] for var in VARIANTS], 3)
                   .convert("RGB") for k in door_seq]
    door_frames[0].save(os.path.join(PREVIEW_DIR, "jeep_fuel_door.gif"), save_all=True,
                        append_images=door_frames[1:], duration=int(HOOD_SWING_DELAY * 1000) + 40, loop=0)
    def night_frame(var, v, signals, blink_on=True):
        img = composite(var, v, per[var], dy)
        px = img.load()
        for y in range(SIZE):
            for x in range(SIZE):
                r, g, b, a = px[x, y]
                px[x, y] = (r * 2 // 7, g * 2 // 7, b * 3 // 8, a)
        if signals is not None:
            img.alpha_composite(to_image(per[var][v]["lights"]))
            img.alpha_composite(to_image(per[var][v]["headlights_on"]))
            for layer in signals:
                if blink_on or not layer.startswith("signal"):
                    img.alpha_composite(to_image(per[var][v][layer]))
        return img

    cases = (None, (), ("brake_on",), ("signal_left", "signal_right"), ("signal_left",), ("signal_right",))
    sheet([[night_frame("cargo", v, c) for v in DIRS] for c in cases], 3, bg=(18, 20, 26, 255)).save(
        os.path.join(PREVIEW_DIR, "jeep_lights.png"))
    blink_frames = [sheet([[night_frame("cargo", v, c, on) for v in DIRS] for c in cases[3:]], 3,
                          bg=(18, 20, 26, 255)).convert("RGB") for on in (True, False)]
    blink_frames[0].save(os.path.join(PREVIEW_DIR, "jeep_signals.gif"), save_all=True,
                         append_images=blink_frames[1:], duration=int(SIGNAL_DELAY * 1000), loop=0)
    grid(hood="hood_open", riders=True, loaded=True).save(os.path.join(PREVIEW_DIR, "jeep_hood_open_riders.png"))
    last = len(HOOD_SWING) - 1
    sequence = list(range(last + 1)) + [last] * 8 + list(range(last, -1, -1)) + [0] * 8
    swing_frames = []
    for k in sequence:
        rows = []
        for var in VARIANTS:
            row = []
            for v in DIRS:
                d = dict(per[var][v])
                d["hood_closed"] = d["hood_swing"][k]
                row.append(composite(var, v, {**per[var], v: d}, dy))
            rows.append(row)
        swing_frames.append(sheet(rows, 3).convert("RGB"))
    swing_frames[0].save(os.path.join(PREVIEW_DIR, "jeep_hood_swing.gif"), save_all=True,
                         append_images=swing_frames[1:], duration=int(HOOD_SWING_DELAY * 1000) + 30, loop=0)
    smoky = {v: [smoke_frames(v, dy[v], h) for h in (False, True)] for v in DIRS}
    frames = []
    for k in range(SMOKE_FRAMES * 2):
        rows = [[composite(var, v, per[var], dy, damaged=heavy, hood=h, smoke=smoky[v][heavy][k % SMOKE_FRAMES])
                 for v in DIRS] for var, h, heavy in (("cargo", "hood_closed", False), ("transport", "hood_closed", True),
                                                      ("gunner", "hood_open", True))]
        frames.append(sheet(rows, 3).convert("RGB"))
    frames[0].save(os.path.join(PREVIEW_DIR, "jeep_engine_smoke.gif"), save_all=True, append_images=frames[1:],
                   duration=int(SMOKE_DELAY * 1000), loop=0)
    turret_arc_demo(per, dy).save(os.path.join(PREVIEW_DIR, "jeep_turret_arc.png"))
    for snapped, name in ((False, "jeep_turret_sweep_smooth.gif"), (True, "jeep_turret_sweep_ingame.gif")):
        frames = turret_sweep(per, dy, snapped)
        frames[0].save(os.path.join(PREVIEW_DIR, name), save_all=True, append_images=frames[1:],
                       duration=140, loop=0)
    frames = [grid(frame=k).convert("RGB") for k in range(WHEEL_FRAMES)]
    frames[0].save(os.path.join(PREVIEW_DIR, "jeep_wheels.gif"), save_all=True, append_images=frames[1:],
                   duration=int(WHEEL_DELAY * 1000), loop=0)
    count = 32
    bobs = {var: suspension_bob(count, seed(var) % 1000) for var in VARIANTS}
    frames = [sheet([[moving(var, v, per[var], dy, k, bobs[var][k]) for v in DIRS] for var in VARIANTS], 3)
              .convert("RGB") for k in range(count)]
    frames[0].save(os.path.join(PREVIEW_DIR, "jeep_moving.gif"), save_all=True, append_images=frames[1:],
                   duration=int(WHEEL_DELAY * 1000), loop=0)
    strip = Image.new("RGBA", (len(icons) * (ICON + 4) + 4, ICON + 8), (74, 78, 64, 255))
    for i, img in enumerate(icons.values()):
        strip.alpha_composite(img, (4 + i * (ICON + 4), 4))
    strip.resize((strip.width * 6, strip.height * 6), Image.NEAREST).save(os.path.join(PREVIEW_DIR, "hardpoint_icons.png"))

    data = {
        "note": "Pixel offsets (x right, y up) of each sprite centre from the vehicle origin, per RSI "
                "direction. Draw riders far to near: larger depth first. Facing north the crate is "
                "in front of the riders, otherwise behind them.",
        "riders": {var: {n: {v: o[v] for v in DIRS} for n, o in seat_offsets(var, dy).items()}
                   for var in VARIANTS},
        "mgturret_pixel_offsets": {v: list(p) for v, p in mg_offsets(dy).items()},
        "cargo_crate_offsets": {v: list(p) for v, p in crate_offsets(dy).items()},
    }
    with open(os.path.join(HERE, "seat_offsets.json"), "w", newline="\n") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")


if __name__ == "__main__":
    main()
