using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AU14.Insurgency.Sapper;

/// <summary>
///     Read-only list of the card logins a siphon rig has leaked out of hacked ATMs.
///     Opened by using the rig in hand.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SapperSiphonRigWindow : DefaultWindow
{
    public SapperSiphonRigWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<SkimmedAccount> accounts)
    {
        DataRows.RemoveAllChildren();

        if (accounts.Count == 0)
        {
            DataRows.AddChild(new Label { Text = "No account data captured. Siphon an ATM to dump its recent logins." });
            return;
        }

        foreach (var acct in accounts)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = $"#{acct.AccountNumber}", MinSize = new(110, 0) });
            row.AddChild(new Label { Text = acct.Name,               MinSize = new(160, 0) });
            row.AddChild(new Label { Text = acct.Pin.ToString(),     MinSize = new(70,  0) });
            DataRows.AddChild(row);
        }
    }
}
