using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

/// <summary>
///     Read-only display window for data retrieved from a CLF network tap skimmer.
///     Opened by ClfNetworkTapBui when the server sends skimmer data via the ATM UI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ClfNetworkTapWindow : DefaultWindow
{
    public ClfNetworkTapWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<SkimmedAccount> accounts)
    {
        DataRows.RemoveAllChildren();

        if (accounts.Count == 0)
        {
            DataRows.AddChild(new Label { Text = "No account data captured." });
            return;
        }

        foreach (var acct in accounts)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = $"#{acct.AccountNumber}", MinSize = new(110, 0) });
            row.AddChild(new Label { Text = acct.Name,               MinSize = new(160, 0) });
            row.AddChild(new Label { Text = acct.Pin.ToString(),     MinSize = new(70,  0) });
            DataRows.AddChild(row);
        }
    }
}
