using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class ColonyAtmWindow : DefaultWindow
{
    public ColonyAtmWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateDisplay(ColonyAtmBuiState s)
    {
        // ── Header ─────────────────────────────────────────────────────────
        AccountLabel.Text  = s.AccountNumber > 0 ? $"Account #{s.AccountNumber}" : "COLONY ATM";
        BalanceLabel.Text  = s.Screen >= AtmScreen.MainMenu ? $"Balance: ${s.Balance}" : string.Empty;

        // ── Screen label (centre display) ──────────────────────────────────
        ScreenLabel.Text = BuildScreenText(s);

        // ── Keypad buffer ──────────────────────────────────────────────────
        BufferLabel.Text = s.KeypadBuffer.Length > 0 ? s.KeypadBuffer : string.Empty;

        // ── Side button labels ─────────────────────────────────────────────
        BtnL1.Text    = s.LeftLabels[0];
        BtnL1.Visible = s.LeftLabels[0].Length > 0;
        BtnL2.Text    = s.LeftLabels[1];
        BtnL2.Visible = s.LeftLabels[1].Length > 0;
        BtnL3.Text    = s.LeftLabels[2];
        BtnL3.Visible = s.LeftLabels[2].Length > 0;
        BtnR1.Text    = s.RightLabels[0];
        BtnR1.Visible = s.RightLabels[0].Length > 0;
        BtnR2.Text    = s.RightLabels[1];
        BtnR2.Visible = s.RightLabels[1].Length > 0;
        BtnR3.Text    = s.RightLabels[2];
        BtnR3.Visible = s.RightLabels[2].Length > 0;

        // ── Skimmer table ──────────────────────────────────────────────────
        SkimmerPanel.Visible = s.Screen == AtmScreen.SkimmerData;
        if (s.Screen == AtmScreen.SkimmerData)
            PopulateSkimmerTable(s.SkimmerData);

        // ── Numpad visibility: hide on locked/result/skimmer ───────────────
        var showNumpad = s.Screen is not (AtmScreen.PinLocked or AtmScreen.Result
            or AtmScreen.WithdrawConfirm or AtmScreen.RemoteDepositConfirm
            or AtmScreen.TransferConfirm or AtmScreen.Welcome or AtmScreen.MainMenu
            or AtmScreen.SkimmerData);
        NumpadContainer.Visible = showNumpad;
        ControlRow.Visible = s.Screen is not (AtmScreen.Welcome or AtmScreen.MainMenu or AtmScreen.SkimmerData);
    }

    private static string BuildScreenText(ColonyAtmBuiState s)
    {
        return s.Screen switch
        {
            AtmScreen.Welcome          => "Welcome!\nPlease swipe your ID card.",
            AtmScreen.PinEntry         => $"Enter PIN:\n{s.KeypadBuffer}\n{s.StatusMessage}",
            AtmScreen.PinLocked        => $"Card locked.\nToo many incorrect attempts.\n{(s.LockExpiry.HasValue ? $"Try again in {(int)(s.LockExpiry.Value - TimeSpan.Zero).TotalMinutes} min." : string.Empty)}",
            AtmScreen.MainMenu         => $"Hello, {s.OwnerName}.\nSelect an option.",
            AtmScreen.Withdraw         => $"Enter amount to withdraw:\n{(s.KeypadBuffer.Length > 0 ? $"${s.KeypadBuffer}" : "")}\n{s.StatusMessage}",
            AtmScreen.WithdrawConfirm  => s.StatusMessage,
            AtmScreen.Deposit          => $"Enter amount to deposit:\n{(s.KeypadBuffer.Length > 0 ? $"${s.KeypadBuffer}" : "")}\n{s.StatusMessage}",
            AtmScreen.RemoteDeposit    => $"Enter recipient account #:\n{s.KeypadBuffer}\n{s.StatusMessage}",
            AtmScreen.RemoteDepositAmount  => $"{s.StatusMessage}\n${s.KeypadBuffer}",
            AtmScreen.RemoteDepositConfirm => s.StatusMessage,
            AtmScreen.Transfer         => $"Enter recipient account #:\n{s.KeypadBuffer}\n{s.StatusMessage}",
            AtmScreen.TransferAmount   => $"{s.StatusMessage}\n${s.KeypadBuffer}",
            AtmScreen.TransferConfirm  => s.StatusMessage,
            AtmScreen.Result           => s.StatusMessage,
            AtmScreen.SkimmerData      => "Captured Accounts:",
            _                          => string.Empty,
        };
    }

    private void PopulateSkimmerTable(List<SkimmedAccount> accounts)
    {
        SkimmerRows.RemoveAllChildren();
        foreach (var acct in accounts)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = $"#{acct.AccountNumber}", MinSize = new(120, 0) });
            row.AddChild(new Label { Text = acct.Name,               MinSize = new(140, 0) });
            row.AddChild(new Label { Text = acct.Pin.ToString(),     MinSize = new(60,  0) });
            SkimmerRows.AddChild(row);
        }
    }
}


