using System.Linq;
using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class ColonyBankAdminWindow : DefaultWindow
{
    public event Action<int, int, string?>? OnCredit;
    public event Action<int, int, string?>? OnDebit;
    public event Action<int>? OnUnlock;

    public ColonyBankAdminWindow()
    {
        RobustXamlLoader.Load(this);

        CreditButton.OnPressed += _ =>
        {
            if (int.TryParse(AccountInput.Text, out var acct) && int.TryParse(AmountInput.Text, out var amt))
                OnCredit?.Invoke(acct, amt, NoteInput.Text);
        };

        DebitButton.OnPressed += _ =>
        {
            if (int.TryParse(AccountInput.Text, out var acct) && int.TryParse(AmountInput.Text, out var amt))
                OnDebit?.Invoke(acct, amt, NoteInput.Text);
        };

        UnlockButton.OnPressed += _ =>
        {
            if (int.TryParse(AccountInput.Text, out var acct))
                OnUnlock?.Invoke(acct);
        };
    }

    public void Populate(ColonyBankAdminBuiState state)
    {
        // ── Accounts tab ──────────────────────────────────────────────────
        AccountRows.RemoveAllChildren();
        foreach (var acct in state.Accounts.OrderBy(a => a.AccountNumber))
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = $"#{acct.AccountNumber}", MinSize = new(90,  0) });
            row.AddChild(new Label { Text = acct.Name,               MinSize = new(160, 0) });
            row.AddChild(new Label { Text = acct.JobTitle,           MinSize = new(130, 0) });
            row.AddChild(new Label { Text = $"${acct.Balance}",      MinSize = new(80,  0) });
            AccountRows.AddChild(row);
        }

        // ── Transactions tab ──────────────────────────────────────────────
        TransactionRows.RemoveAllChildren();
        foreach (var tx in state.Transactions.AsEnumerable().Reverse())
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = $"{tx.Timestamp.TotalMinutes:F0}m",  MinSize = new(50,  0) });
            row.AddChild(new Label { Text = $"#{tx.AccountNumber}",              MinSize = new(90,  0) });
            row.AddChild(new Label { Text = tx.AccountName,                      MinSize = new(130, 0) });
            row.AddChild(new Label { Text = tx.Type.ToString(),                  MinSize = new(110, 0) });
            row.AddChild(new Label { Text = $"${tx.Amount}",                     MinSize = new(70,  0) });
            row.AddChild(new Label { Text = tx.Note ?? string.Empty,             HorizontalExpand = true });
            TransactionRows.AddChild(row);
        }
    }
}
