"""
Pixel-art colony ATM: the source of truth for the ATM window's art.

Run from anywhere:  python atm_pixel_art.py

Writes the game assets (atm_base.png and the atm_*.rsi sprites) into
Content.CMU/Resources/Textures/CMU14/ColonyEconomy/, and review material (a layered SVG,
state previews and animation GIFs) into atm_pixel_art/ in the system temp folder, outside the repo.

The machine is drawn on a 227 x 300 grid from primitives - panels, bevels, screws, a bitmap
font, a geometric Weyland-Yutani mark - in the in-game ATM sprite's palette, after the original
hand-painted atm_ui.png with its misalignments corrected: both pillars are the same width, all
four fascia corners match and the plates line up with the fascia.

It is laid out like a real machine: a five-row keypad - the digits, then erase / 0 / 00, then a
wide CANCEL and ENTER - a plain access panel where the old art had an open bin, and a card-sized
recess with a slot at its foot that the ID card is pushed down into like a time-clock card, so the
player's own card stands in it at its original size.

ColonyAtmWindow places each sprite with the same grid coordinates as the LAYOUT table below;
change one and you must change the other.
"""
import json
import tempfile
from pathlib import Path

from PIL import Image

W, H = 227, 300
# What the window shows: the fascia, outline to outline. Everything is still drawn on the full
# 227x300 grid, so every rectangle below keeps its coordinates; the window offsets them by VIEW.
VIEW = (12, 84, 203, 181)
HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
TEXTURES = REPO / "Content.CMU/Resources/Textures/CMU14/ColonyEconomy"
# Review material is only for looking at, so it stays out of the repo.
REVIEW = Path(tempfile.gettempdir()) / "atm_pixel_art"
LICENSE = "CC-BY-SA-3.0"
COPYRIGHT = ("Pixel-art colony ATM drawn for CMU after the original atm_ui.png, generated by "
             "Content.CMU/Design/ColonyEconomy/AtmPixelArt/atm_pixel_art.py")

# Sprite rectangles (x, y, width, height) in grid pixels. Mirrored by ColonyAtmWindow.
LAYOUT = {
    "glass": (31, 102, 107, 84),
    "reader": (145, 100, 51, 42),
    "slot_y": (134, 0, 0, 0),
    # The card recess: as wide as the CM holo-badge (16) plus a pixel either side, its slot along
    # the bottom. Cards are drawn at their own size, so the reader fits the card, not the other way.
    "bay": (161, 111, 18, 23),
    # Where the card is drawn: from the fascia's top band, where the hand brings it in, down to the slot.
    "card": (145, 86, 51, 48),
    # Room for the bills fanned out toward the customer, down to the shelf.
    "cash": (42, 196, 85, 27),
    "receipt": (121, 189, 19, 32),
    "led_power": (31, 196, 5, 5),
    "led_activity": (31, 207, 5, 5),
}
# Keys are wider than they are tall, like a real ATM's, so five rows fit the well.
KEY_W, KEY_H = 15, 13
KEY_ORIGIN, KEY_PITCH = (146, 145), (17, 15)
KEYPAD = (("1", 0, 0), ("2", 1, 0), ("3", 2, 0), ("4", 0, 1), ("5", 1, 1), ("6", 2, 1),
          ("7", 0, 2), ("8", 1, 2), ("9", 2, 2), ("clear", 0, 3), ("0", 1, 3), ("00", 2, 3))
# The fifth row: two wide keys under the grid.
WIDE_W, WIDE_Y = 24, KEY_ORIGIN[1] + 4 * KEY_PITCH[1]
WIDE_KEYS = (("cancel", 146), ("enter", 171))


def key_rect(index):
    _, col, row = KEYPAD[index]
    return KEY_ORIGIN[0] + col * KEY_PITCH[0], KEY_ORIGIN[1] + row * KEY_PITCH[1], KEY_W, KEY_H


# ── Palette ──────────────────────────────────────────────────────────────────
C = dict(
    gold="#93630d", gold_hi="#ab7a1f", grey="#837e77",
    outline="#0a0705", key_ol="#1a1209",
    slot="#050403", slot_rim="#2c241b",
    bracket="#a1a67d",
    grille="#2c1e0f", grille_hi="#7a6548",
    tray="#130c05",
    led_off="#5a5636", led_off_hi="#77724a",
    plate="#766a58", plate_text="#1d160e",
    # Screw heads: steel, a shade apart from whatever they are driven into.
    screw="#77706a", screw_hi="#9a938c", screw_lo="#4f4944", screw_slot="#2a2420",
)

# ── Fonts ────────────────────────────────────────────────────────────────────
F3 = {  # 3x5, wider where three columns cannot carry the letter
    "A": [".#.", "#.#", "###", "#.#", "#.#"], "B": ["##.", "#.#", "##.", "#.#", "##."],
    "C": [".##", "#..", "#..", "#..", ".##"], "D": ["##.", "#.#", "#.#", "#.#", "##."],
    "E": ["###", "#..", "##.", "#..", "###"], "F": ["###", "#..", "##.", "#..", "#.."],
    "G": [".##", "#..", "#.#", "#.#", ".##"], "H": ["#.#", "#.#", "###", "#.#", "#.#"],
    "I": ["###", ".#.", ".#.", ".#.", "###"], "J": ["..#", "..#", "..#", "#.#", ".#."],
    "K": ["#.#", "#.#", "##.", "#.#", "#.#"], "L": ["#..", "#..", "#..", "#..", "###"],
    "M": ["#...#", "##.##", "#.#.#", "#...#", "#...#"], "N": ["#..#", "##.#", "#.##", "#..#", "#..#"],
    "O": [".#.", "#.#", "#.#", "#.#", ".#."], "P": ["##.", "#.#", "##.", "#..", "#.."],
    "R": ["##.", "#.#", "##.", "#.#", "#.#"], "S": [".##", "#..", ".#.", "..#", "##."],
    "T": ["###", ".#.", ".#.", ".#.", ".#."], "U": ["#.#", "#.#", "#.#", "#.#", "###"],
    "V": ["#.#", "#.#", "#.#", "#.#", ".#."], "W": ["#...#", "#...#", "#.#.#", "##.##", "#...#"],
    "Y": ["#.#", "#.#", ".#.", ".#.", ".#."],
    "0": ["###", "#.#", "#.#", "#.#", "###"], "1": [".#.", "##.", ".#.", ".#.", "###"],
    "2": ["##.", "..#", ".#.", "#..", "###"], "-": ["...", "...", "###", "...", "..."],
    " ": ["...", "...", "...", "...", "..."],
}
F5 = {  # 5x7
    "0": [".###.", "#...#", "#..##", "#.#.#", "##..#", "#...#", ".###."],
    "1": ["..#..", ".##..", "..#..", "..#..", "..#..", "..#..", ".###."],
    "2": [".###.", "#...#", "....#", "..##.", ".#...", "#....", "#####"],
    "3": ["####.", "....#", "....#", ".###.", "....#", "....#", "####."],
    "4": ["...#.", "..##.", ".#.#.", "#..#.", "#####", "...#.", "...#."],
    "5": ["#####", "#....", "####.", "....#", "....#", "#...#", ".###."],
    "6": ["..##.", ".#...", "#....", "####.", "#...#", "#...#", ".###."],
    "7": ["#####", "....#", "...#.", "..#..", ".#...", ".#...", ".#..."],
    "8": [".###.", "#...#", "#...#", ".###.", "#...#", "#...#", ".###."],
    "9": [".###.", "#...#", "#...#", ".####", "....#", "...#.", ".##.."],
    "O": [".###.", "#...#", "#...#", "#...#", "#...#", "#...#", ".###."],
    "K": ["#...#", "#..#.", "#.#..", "##...", "#.#..", "#..#.", "#...#"],
    "X": ["#...#", "#...#", ".#.#.", "..#..", ".#.#.", "#...#", "#...#"],
    " ": [".....", ".....", ".....", ".....", ".....", ".....", "....."],
}


def rgba(c):
    if isinstance(c, tuple):
        return c
    c = c.lstrip("#")
    return (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16), int(c[6:8], 16) if len(c) == 8 else 255)


class Layer:
    def __init__(self, name=""):
        self.name = name
        self.px = {}

    def set(self, x, y, c):
        if 0 <= x < W and 0 <= y < H:
            self.px[(x, y)] = rgba(c)

    def get(self, x, y):
        return self.px.get((x, y))

    def rect(self, x0, y0, x1, y1, c):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.set(x, y, c)

    def outline(self, x0, y0, x1, y1, c, rounded=False):
        for x in range(x0, x1 + 1):
            if rounded and x in (x0, x1):
                continue
            self.set(x, y0, c)
            self.set(x, y1, c)
        for y in range(y0 + 1, y1):
            self.set(x0, y, c)
            self.set(x1, y, c)

    def glyphs(self, font, x, y, text, c, gap=1, bold=False):
        for ch in text:
            g = font.get(ch, font[" "])
            for gy, row in enumerate(g):
                for gx, bit in enumerate(row):
                    if bit == "#":
                        self.set(x + gx, y + gy, c)
                        if bold:
                            self.set(x + gx + 1, y + gy, c)
            x += len(g[0]) + gap + (1 if bold else 0)

    def blend(self, other):
        """Alpha-composites `other` over this layer, pixel by pixel."""
        for (x, y), (r, g, b, a) in other.px.items():
            under = self.px.get((x, y))
            if under is None or a == 255:
                self.px[(x, y)] = (r, g, b, a)
                continue
            k = a / 255
            ur, ug, ub, ua = under
            self.px[(x, y)] = (round(r * k + ur * (1 - k)), round(g * k + ug * (1 - k)),
                               round(b * k + ub * (1 - k)), max(ua, a))

    def paste(self, other, clip=None):
        for (x, y), c in other.px.items():
            if clip is None or (clip[0] <= x <= clip[2] and clip[1] <= y <= clip[3]):
                self.px[(x, y)] = c

    def image(self, rect=None):
        x0, y0, w, h = rect or (0, 0, W, H)
        img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        for (x, y), c in self.px.items():
            if x0 <= x < x0 + w and y0 <= y < y0 + h:
                img.putpixel((x - x0, y - y0), c)
        return img


def text_width(font, text, gap=1, bold=False):
    return sum(len(font.get(ch, font[" "])[0]) + gap + (1 if bold else 0) for ch in text) - gap


def centred(font, text, cx):
    return cx - text_width(font, text) // 2


# ── Shading helpers ──────────────────────────────────────────────────────────
# Light comes from the top-left throughout: raised edges catch it on their top and left and fall
# into shadow on their bottom and right; recesses do the opposite.
BAYER4 = ((0, 8, 2, 10), (12, 4, 14, 6), (3, 11, 1, 9), (15, 7, 13, 5))


def gradient(L, x0, y0, x1, y1, ramp):
    """Vertical gradient through `ramp`, ordered-dithered between neighbouring steps."""
    span = max(1, y1 - y0)
    for y in range(y0, y1 + 1):
        t = (y - y0) / span * (len(ramp) - 1)
        lo = int(t)
        frac = t - lo
        for x in range(x0, x1 + 1):
            step = lo + (1 if frac * 16 > BAYER4[y % 4][x % 4] + 0.5 and lo + 1 < len(ramp) else 0)
            L.set(x, y, ramp[step])


def bevel(L, x0, y0, x1, y1, hi, lo, raised=True):
    """One-pixel lit and shaded edges round a box; inverted for a recess."""
    a, b = (hi, lo) if raised else (lo, hi)
    L.rect(x0, y0, x1, y0, a)
    L.rect(x0, y0, x0, y1, a)
    L.rect(x0, y1, x1, y1, b)
    L.rect(x1, y0, x1, y1, b)


class _Rng:
    """Tiny deterministic generator, so the art is identical on every run."""

    def __init__(self, seed):
        self.state = seed * 2654435761 % 2 ** 32 or 1

    def next(self):
        self.state ^= (self.state << 13) % 2 ** 32
        self.state ^= self.state >> 17
        self.state ^= (self.state << 5) % 2 ** 32
        return self.state / 2 ** 32


def streaks(L, x0, y0, x1, y1, colour, seed, density=0.06):
    """Brushed-metal grain: short horizontal runs a shade off the base."""
    rng = _Rng(seed)
    for y in range(y0, y1 + 1):
        x = x0
        while x <= x1:
            if rng.next() < density:
                run = 2 + int(rng.next() * 6)
                for xx in range(x, min(x + run, x1 + 1)):
                    L.set(xx, y, colour)
                x += run + 2
            else:
                x += 1


def specks(L, x0, y0, x1, y1, colour, seed, density=0.012):
    """Wear: odd pixels of chipped paint or grime."""
    rng = _Rng(seed)
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            if rng.next() < density:
                L.set(x, y, colour)


def stamp(L, font, x, y, text, dark, lit):
    """Lettering pressed into a panel: dark strokes with their lower edge catching the light."""
    L.glyphs(font, x, y + 1, text, lit)
    L.glyphs(font, x, y, text, dark)


def screw(L, cx, cy):
    """
    A round steel head with a single slot, lit from the top left like everything else on the
    machine: no outline, just a light rim, a dark rim and the slot.
    """
    head = [".###.", "#####", "#####", "#####", ".###."]
    for y, row in enumerate(head):
        for x, bit in enumerate(row):
            if bit == "#":
                rim = C["screw_hi"] if x + y <= 2 else C["screw_lo"] if x + y >= 6 else C["screw"]
                L.set(cx - 2 + x, cy - 2 + y, rim)
    L.rect(cx - 1, cy, cx + 1, cy, C["screw_slot"])


def pin(L, x, y):
    """A tiny two-pixel fixing for small plates."""
    L.set(x, y, C["screw_hi"])
    L.set(x + 1, y + 1, "#2a2420")


def rivet(L, cx, cy):
    for dx, dy in ((0, -1), (-1, 0), (1, 0), (0, 1)):
        L.set(cx + dx, cy + dy, "#211e1a")
    L.set(cx - 1, cy - 1, "#5a544f")


def bone_slot(L, x0, y0, x1, y1, plate):
    """A slot with rounded end-caps standing one pixel proud of the bar at each end."""
    L.rect(x0 + 2, y0 + 1, x1 - 2, y1 - 1, C["slot"])
    for cx in (x0, x1 - 4):
        L.rect(cx, y0, cx + 4, y1, C["slot"])
        for x, y in ((cx, y0), (cx + 4, y0), (cx, y1), (cx + 4, y1)):
            L.set(x, y, plate)
    L.rect(x0 + 5, y1, x1 - 5, y1, C["slot_rim"])


def glass(L, ramp, gleam=None):
    """The tube face, darkening towards the bezel, with an optional gleam in the top-left."""
    x, y, w, h = LAYOUT["glass"]
    steps = (1, 3, 6, 10)
    for yy in range(y, y + h):
        for xx in range(x, x + w):
            dx, dy = min(xx - x, x + w - 1 - xx), min(yy - y, y + h - 1 - yy)
            d = min(dx, dy, (dx + dy) // 2 + 1)
            L.set(xx, yy, ramp[next((n for n, s in enumerate(steps) if d < s), len(steps))])
    if gleam:
        for i in range(16):
            for j in range(2):
                L.set(x + 3 + i + j, y + 16 - i + j, gleam)


# ── Weyland-Yutani mark ──────────────────────────────────────────────────────
def wy_logo(L, x0, y0, h=27, w=17, m=6, gold=None, grey=None):
    """
    Four 45-degree strokes, so every diagonal is a clean one-pixel staircase, and three identical
    grey triangles: two hanging from the top between the arms, one standing under the middle peak.
    """
    gold, grey = gold or C["gold"], grey or C["grey"]
    b0 = x0 + 2 * (h - 1)          # top of the middle peak; the two middle strokes share it
    d0 = b0 + 2 * (h - 1)
    for y in range(h):
        for xs in (x0 + y, b0 - y, b0 + y, d0 - y):
            L.rect(xs, y0 + y, xs + w - 1, y0 + y, gold if y else C["gold_hi"])
        for left, right in ((x0 + y + w + m, b0 - y - 1 - m),        # top-left notch
                            (b0 + y + w + m, d0 - y - 1 - m),        # top-right notch
                            (b0 - y + w + m, b0 + y - 1 - m)):       # under the peak
            if left <= right:
                L.rect(left, y0 + y, right, y0 + y, grey)
    return 4 * (h - 1) + w


# ── Base machine ─────────────────────────────────────────────────────────────
# The counter shelf, after the ledge on the in-game ATM sprite (CMU14/Structures/Machines/atm.rsi):
# a bright tan band right under the cash slot and keypad, its lip a lighter line. Seen from a little
# above, its top is a trapezoid: the back edge is the fascia's inner width, where the cash housing
# and keypad well stand on it, and the front edge reaches the fascia's outer edges because it is
# nearer. The sides are 45 degrees, so each is a clean one-pixel staircase.
SHELF_BACK, SHELF_FRONT = 223, 237          # rows of the back and front edges
SHELF_LEFT, SHELF_RIGHT = 12, 214           # the front edge's ends
SHELF_FOOT = 263                            # the counter's front wall runs down to here
SHELF_TOP = "#d8b684"                       # the sprite's ledge
SHELF_LIP_LINE = "#a99270"                  # the sprite's lip


def shelf_span(y):
    """Left and right ends of the shelf's top on row `y`."""
    inset = SHELF_FRONT - y
    return SHELF_LEFT + inset, SHELF_RIGHT - inset


def draw_shelf(L):
    # Where it meets the machine: a dark seam along the back edge.
    left, right = shelf_span(SHELF_BACK)
    L.rect(left, SHELF_BACK - 2, right, SHELF_BACK - 2, "#4a3f30")
    L.rect(left, SHELF_BACK - 1, right, SHELF_BACK - 1, "#2e261c")
    # The top: the ledge's tan, a shade darker at the back under the machine, lit toward the front.
    ramp = ("#c6a46f", "#cdab77", "#d3b17e", SHELF_TOP, "#dcbb8a", "#e0c090")
    depth = SHELF_FRONT - SHELF_BACK
    for y in range(SHELF_BACK, SHELF_FRONT + 1):
        left, right = shelf_span(y)
        L.rect(left, y, right, y, ramp[min(len(ramp) - 1, (y - SHELF_BACK) * len(ramp) // (depth + 1))])
        # The sides: a lit staircase on the left, a shaded one on the right.
        L.set(left, y, "#ecd09e")
        L.set(right, y, "#a07f50")
    # The front edge catches the light. Under it the counter's front wall, the sprite's lip colour,
    # runs straight down to the machine's foot, darkening toward the floor: the shelf is a solid
    # counter, not a ledge in the air.
    L.rect(SHELF_LEFT, SHELF_FRONT, SHELF_RIGHT, SHELF_FRONT, "#f0d6a6")
    wall = ("#b29c78", SHELF_LIP_LINE, "#a48e6c", "#9f8968", "#9a8466", "#947f61", "#8e7a5c", "#887558")
    for y in range(SHELF_FRONT + 1, SHELF_FOOT + 1):
        k = (y - SHELF_FRONT - 1) * len(wall) // (SHELF_FOOT - SHELF_FRONT)
        L.rect(SHELF_LEFT + 1, y, SHELF_RIGHT - 1, y, wall[min(k, len(wall) - 1)])
    L.rect(SHELF_LEFT + 1, SHELF_FRONT + 1, SHELF_LEFT + 1, SHELF_FOOT, "#bca580")
    L.rect(SHELF_RIGHT - 1, SHELF_FRONT + 1, SHELF_RIGHT - 1, SHELF_FOOT, "#7a6850")
    L.rect(SHELF_LEFT, SHELF_FRONT + 1, SHELF_LEFT, SHELF_FOOT, C["outline"])
    L.rect(SHELF_RIGHT, SHELF_FRONT + 1, SHELF_RIGHT, SHELF_FOOT, C["outline"])
    # The company mark and name, stamped side by side on the wall and centred together.
    mark_w = 4 * (7 - 1) + 5
    name_w = text_width(F3, "WEYLAND-YUTANI")
    x0 = 113 - (mark_w + 5 + name_w) // 2
    top = (SHELF_FRONT + 1 + SHELF_FOOT) // 2 - 4
    stamp_logo(L, x0, top, h=7, w=5, m=2, dark="#5e4d36", lit="#c2aa82")
    stamp(L, F3, x0 + mark_w + 5, top + 1, "WEYLAND-YUTANI", "#5e4d36", "#c2aa82")


def stamp_logo(L, x0, y0, h, w, m, dark, lit):
    """The company mark pressed into a panel like stamped lettering: dark, lit along its lower edge."""
    mark = Layer()
    width = wy_logo(mark, 0, 0, h=h, w=w, m=m)
    for (x, y) in mark.px:
        L.set(x0 + x, y0 + y + 1, lit)
    for (x, y) in mark.px:
        L.set(x0 + x, y0 + y, dark)
    return width


def draw_base():
    L = Layer("base")

    # Fascia: outline, matching top and bottom bands with four identical screwed corners, and the
    # two pillars. The window shows exactly this (VIEW); the cabinet round it is not drawn.
    L.outline(12, 84, 214, 264, C["outline"])
    for y0 in (85,):
        gradient(L, 13, y0, 213, y0 + 11, ("#9c8768", "#88775d", "#7a6a52"))
        L.rect(13, y0, 213, y0, "#b49e7c")
        L.rect(13, y0 + 11, 213, y0 + 11, "#5e5040")
        for x0 in (13, 201):
            L.rect(x0, y0, x0 + 12, y0 + 11, "#4a4034")
            bevel(L, x0, y0, x0 + 12, y0 + 11, "#685a48", "#2c251d")
            screw(L, x0 + 6, y0 + 5)
    stamp(L, F3, centred(F3, "COLONY FINANCIAL", 113), 88, "COLONY FINANCIAL", "#55493a", "#b49e7c")
    for x0 in (13, 201):
        gradient(L, x0, 97, x0 + 12, 251, ("#8f7c5f", "#85735a", "#7a6a52", "#6f6049"))
        L.rect(x0, 97, x0, 251, "#a99270")
        L.rect(x0 + 1, 97, x0 + 1, 251, "#96825f")
        L.rect(x0 + 12, 97, x0 + 12, 251, "#55493a")
        L.rect(x0, 97, x0 + 12, 97, "#b49e7c")
        specks(L, x0 + 2, 99, x0 + 10, 249, "#9a8566", seed=x0, density=0.02)

    # The inner face sits a step back from the pillars.
    gradient(L, 26, 97, 200, 251, ("#7a6a50", "#74644b", "#6d5e46", "#665741"))
    bevel(L, 26, 97, 200, 251, "#4a3f30", "#8f7c5f", raised=False)
    specks(L, 28, 99, 198, 249, "#5f5140", seed=7, density=0.008)

    # Screen bezel: a moulded surround with a lit lip and a deep inner shadow, corners rounded.
    L.rect(29, 100, 139, 187, "#2a2220")
    bevel(L, 29, 100, 139, 187, "#4d3e37", "#1a1513")
    L.rect(30, 101, 138, 101, "#14100e")
    L.rect(30, 101, 30, 186, "#14100e")
    for x, y in ((29, 100), (139, 100), (29, 187), (139, 187)):
        L.set(x, y, "#5c4e3c")
    glass(L, ("#474b21", "#4e5225", "#555a28", "#5b602b", "#5f642d"), gleam="#666c31")

    draw_reader(L)

    # Keypad well, a step down so the keys stand proud of it.
    L.rect(142, 142, 198, 220, "#5f4f39")
    bevel(L, 142, 142, 198, 220, "#3a3024", "#86735a", raised=False)
    specks(L, 144, 144, 196, 218, "#56482f", seed=19, density=0.02)
    for i in range(len(KEYPAD)):
        x, y, w, h = key_rect(i)
        L.rect(x + 1, y + h, x + w - 1, y + h, "#3f3324")
        draw_key(L, i, "on")
    for name, _ in WIDE_KEYS:
        x, y, w, h = wide_key_rect(name)
        L.rect(x + 1, y + h, x + w - 1, y + h, "#3f3324")
        draw_wide_key(L, name, "on")

    # Cash dispenser - the only way money comes out: a ridged shutter housing round the slot,
    # labelled, with grilles either side.
    L.rect(50, 189, 118, 220, "#5c4b32")
    for y in range(190, 220):
        if y < 197 or y > 213:
            L.rect(51, y, 117, y, "#66543a" if y % 2 else "#55452e")
    bevel(L, 50, 189, 118, 220, "#7d6a4e", "#3a2f20")
    stamp(L, F3, centred(F3, "CASH", 84), 191, "CASH", "#2c241a", "#8f7c5f")
    bone_slot(L, 52, 199, 116, 211, "#5c4b32")
    L.rect(55, 200, 113, 200, "#000000")
    L.rect(57, 210, 111, 210, "#1c1712")
    for gx in (41, 44, 47):
        L.rect(gx, 201, gx, 209, C["grille"])
        L.rect(gx + 1, 201, gx + 1, 209, C["grille_hi"])
        L.set(gx, 200, "#4a3e2e")
    for name in ("led_power", "led_activity"):
        x, y, _, _ = LAYOUT[name]
        L.outline(x, y, x + 4, y + 4, "#5e4a30", rounded=True)
        L.paste(led(name, None))

    draw_receipt_slot(L)
    draw_shelf(L)

    return L


# ── Receipt printer ──────────────────────────────────────────────────────────
# The receipt comes out of the slit toward the customer like the bills: a strip that widens as it
# nears and darkens toward the slit, leading edge first, printed lines across it.
RECEIPT_FAR_Y, RECEIPT_ROWS = 201, 13
RECEIPT_FAR_W, RECEIPT_NEAR_W = 9, 13
RECEIPT_MID = 130
RECEIPT_SHADE = (0.85, 0.65, 0.45, 0.3, 0.18, 0.1, 0.05)
PRINT_DELAYS = [0.15, 0.17, 0.17, 0.17, 0.17, 0.17, 0.25]   # with short_print_and_rip.ogg
PAPER = dict(edge="#8d877a", paper="#e9e4d6", ink="#8d877a")


def draw_receipt_slot(L):
    """Where the right-hand grille was: a small housing like the cash slot's, with a paper slit."""
    x0, y0, w, h = LAYOUT["receipt"]
    x1, y1 = x0 + w - 1, y0 + h - 1
    L.rect(x0, y0, x1, y1, "#5c4b32")
    for y in range(y0 + 1, y1):
        if y < 197 or y > 206:
            L.rect(x0 + 1, y, x1 - 1, y, "#66543a" if y % 2 else "#55452e")
    bevel(L, x0, y0, x1, y1, "#7d6a4e", "#3a2f20")
    stamp(L, F3, centred(F3, "RCPT", x0 + w // 2), 191, "RCPT", "#2c241a", "#8f7c5f")
    L.rect(x0 + 3, 199, x1 - 3, 202, C["slot"])
    L.rect(x0 + 3, 199, x1 - 3, 199, "#000000")
    L.rect(x0 + 4, 203, x1 - 4, 203, C["slot_rim"])


def receipt_span(row):
    width = RECEIPT_FAR_W + (RECEIPT_NEAR_W - RECEIPT_FAR_W) * row / (RECEIPT_ROWS - 1)
    return round(RECEIPT_MID - width / 2), round(RECEIPT_MID + width / 2) - 1


def receipt(drop):
    """The receipt `drop` rows out of the slit; the part still inside is hidden."""
    L = Layer()
    drop = min(drop, RECEIPT_ROWS)
    for row in range(drop):
        x0, x1 = receipt_span(row)
        v = 1 - (drop - row - 0.5) / RECEIPT_ROWS
        printed = 0.2 < v < 0.85 and int(v * RECEIPT_ROWS) % 2 == 0
        for x in range(x0, x1 + 1):
            u = (x - x0 + 0.5) / (x1 - x0 + 1)
            if x in (x0, x1) or row == drop - 1:
                colour = PAPER["edge"]
            elif printed and 0.2 < u < (0.8 if int(v * RECEIPT_ROWS) % 4 else 0.6):
                colour = PAPER["ink"]
            else:
                colour = PAPER["paper"]
            keep = 1 - (RECEIPT_SHADE[row] if row < len(RECEIPT_SHADE) else 0)
            r, g, b, _ = rgba(colour)
            L.set(x, RECEIPT_FAR_Y + row, "#%02x%02x%02x" % (int(r * keep), int(g * keep), int(b * keep)))
    if drop > 0:
        x0, x1 = receipt_span(drop - 1)
        L.rect(x0 + 1, RECEIPT_FAR_Y + drop, x1 - 1, RECEIPT_FAR_Y + drop, "#3d3324")
    return L


# ── Card reader ──────────────────────────────────────────────────────────────
def draw_reader(L):
    """
    The card reader, built like a time clock's: a recess exactly a card wide, with the housing's lip
    across its foot. The card is pushed down behind the lip and stands with its top half showing; a
    light rail runs down each side.
    """
    # Label strip, recessed, with raised lettering.
    L.rect(143, 100, 197, 109, "#3a3024")
    bevel(L, 143, 100, 197, 109, "#241c14", "#6a5a44", raised=False)
    L.glyphs(F3, centred(F3, "INSERT ID TAG", 170) + 1, 103, "INSERT ID TAG", "#1a140e")
    L.glyphs(F3, centred(F3, "INSERT ID TAG", 170), 102, "INSERT ID TAG", "#e0d3a8")

    # Housing round the recess.
    L.rect(143, 110, 197, 139, "#74644b")
    L.rect(146, 110, 194, 139, "#6e5c44")
    bevel(L, 146, 110, 194, 139, "#9c8566", "#4a3e2e")
    # Fixings in the housing's corners, now there is housing either side of the narrow reader.
    for x, y in ((148, 112), (191, 112), (148, 136), (191, 136)):
        pin(L, x, y)
    # Rails hugging the recess, each with its light strip.
    for x0 in (155, 180):
        L.rect(x0, 112, x0 + 4, 138, "#5a4a36")
        bevel(L, x0, 112, x0 + 4, 138, "#8a7558", "#3a2f22")
        L.rect(x0 + 1, 116, x0 + 3, 136, "#2a2219")
    # The recess: a card's width, stepped back, darker the deeper it goes.
    bx, by, bw, bh = LAYOUT["bay"]
    gradient(L, bx, by, bx + bw - 1, by + bh - 1, ("#4e4130", "#47392a", "#3f3325"))
    bevel(L, bx, by, bx + bw - 1, by + bh - 1, "#2c241a", "#7d6a4e", raised=False)
    # A guide mark showing where the card goes in.
    for dy in range(3):
        L.rect(169 - dy, 115 + dy, 170 + dy, 115 + dy, "#5a4a36")
    L.rect(167, 118, 172, 118, "#7d6a4e")
    # No black slot: the recess's foot is a lip of the housing, lit along its top edge, and the card
    # goes down behind it - it stops being drawn exactly where the lip starts.
    sy = LAYOUT["slot_y"][0]
    L.rect(bx, sy, bx + bw - 1, sy + 4, "#6e5c44")
    L.rect(bx, sy, bx + bw - 1, sy, "#b49e7c")
    L.rect(bx, sy + 1, bx + bw - 1, sy + 1, "#8f7c5f")
    L.rect(bx, sy + 4, bx + bw - 1, sy + 4, "#4a3e2e")
    draw_rails(L, C["bracket"])
    L.rect(143, 140, 197, 140, "#4a3f30")
    L.rect(143, 141, 197, 141, "#8f7c5f")


def draw_rails(L, colour, glow=None):
    """The reader's two light strips, lit `colour` with an optional glow spilling onto the rails."""
    for x0 in (157, 182):
        L.rect(x0, 116, x0, 136, colour)
        if glow:
            L.rect(x0 - 1, 116, x0 - 1, 136, glow)
            L.rect(x0 + 1, 116, x0 + 1, 136, glow)


def rails(colour, glow):
    L = Layer()
    draw_rails(L, colour, glow)
    return L


def bay_glass():
    """Darkness at the slot's mouth, laid over the card where it goes in."""
    L = Layer()
    bx, _, bw, _ = LAYOUT["bay"]
    sy = LAYOUT["slot_y"][0]
    for y, alpha in ((sy - 3, 0x30), (sy - 2, 0x60), (sy - 1, 0xa0)):
        L.rect(bx, y, bx + bw - 1, y, "#000000%02x" % alpha)
    return L


def tampered():
    """
    What a siphon rig leaves once the machine has repaired itself: pry scratches either side of the
    slot, a recess corner bent out of true, and a strip of adhesive residue where the rig sat. Small
    enough to miss, there for anyone who looks.
    """
    L = Layer()
    sy = LAYOUT["slot_y"][0]
    bx, _, bw, _ = LAYOUT["bay"]
    for x, y in ((bx - 2, sy - 2), (bx - 3, sy - 1), (bx - 2, sy + 3), (bx + bw + 1, sy - 2),
                 (bx + bw + 2, sy - 1), (bx + bw + 1, sy + 4), (bx + 3, sy + 5), (bx + 4, sy + 5)):
        L.set(x, y, "#b8a27e")
    L.set(bx - 1, sy - 2, "#3a2e20")
    L.set(bx + bw, sy - 2, "#3a2e20")
    # The recess's top-right corner, levered out.
    L.rect(bx + bw - 3, 111, bx + bw - 1, 111, "#8a7558")
    L.set(bx + bw - 1, 112, "#8a7558")
    L.set(bx + bw, 111, "#2c241a")
    # Adhesive residue along the housing under the slot.
    L.rect(bx - 1, sy + 6, bx + bw, sy + 6, "#8e7c5c")
    return L


CAUTION = ("#e8c030", "#1a1408")
# Each frame: (wire bursting or None, embers as (wire, dx, dy, colour)).
SPARK_FRAMES = [
    (0, []),
    (None, [(0, 3, -2, "#ffd060"), (0, -3, -1, "#ffb030"), (0, 2, 1, "#ff8020")]),
    (None, [(0, 4, -3, "#ff8020"), (0, -4, 0, "#c05010")]),
    (2, [(0, 5, -1, "#a04010")]),
    (None, [(2, 3, -2, "#ffd060"), (2, -2, -3, "#ffb030")]),
    (1, [(2, 4, -1, "#ff8020")]),
    (None, [(1, -3, -2, "#ffd060"), (1, 3, -1, "#ffb030"), (1, 1, 2, "#ff8020")]),
    (None, []),
]
# The sparks follow the zaps in the seized reader's sound, which the window loops from the moment the
# machine goes out: the sound's loudness every SPARK_TICK picks the frame - a burst at a wire on the
# loudest moments, flying embers on the quieter ones, nothing in the gaps - and the loop lasts
# exactly as long as the sound, so the two stay together.
ZAP_WAV = REPO / "Content.CMU/Resources/Audio/CMU14/ColonyEconomy/atm_zap.wav"
SPARK_TICK = 0.04
SPARK_BURSTS = (0, 3, 5)            # SPARK_FRAMES with a wire bursting, taken in turn
SPARK_EMBERS = (1, 2, 4, 6)         # SPARK_FRAMES with only embers flying
SPARK_QUIET = 7


def wav_levels(path, tick):
    """(length in seconds, loudness of every `tick` seconds) of a mono 16-bit WAV."""
    import wave
    with wave.open(str(path)) as w:
        rate, data = w.getframerate(), w.readframes(w.getnframes())
    samples = [int.from_bytes(data[i:i + 2], "little", signed=True) for i in range(0, len(data), 2)]
    step = int(rate * tick)
    levels = []
    for i in range(0, len(samples), step):
        chunk = samples[i:i + step]
        levels.append((sum(s * s for s in chunk) / len(chunk)) ** 0.5)
    return len(samples) / rate, levels


def spark_timeline():
    """(SPARK_FRAMES index, seconds) runs that cover the zap sound once."""
    length, levels = wav_levels(ZAP_WAV, SPARK_TICK)
    loudest = max(levels)
    runs, bursts, embers = [], 0, 0
    for level in levels:
        if level >= 0.45 * loudest:
            frame, bursts = SPARK_BURSTS[bursts % len(SPARK_BURSTS)], bursts + 1
        elif level >= 0.15 * loudest:
            frame, embers = SPARK_EMBERS[embers % len(SPARK_EMBERS)], embers + 1
        else:
            frame = SPARK_QUIET
        if runs and frame == runs[-1][0] == SPARK_QUIET:
            runs[-1][1] += SPARK_TICK
        else:
            runs.append([frame, SPARK_TICK])
    # The last tick is a part one; trim so the loop is exactly the sound's length.
    runs[-1][1] += length - sum(d for _, d in runs)
    return [(frame, round(seconds, 4)) for frame, seconds in runs]


SPARKS = spark_timeline()


def broken(frame):
    """
    A siphoned reader while it is out: faceplate cracked and scorched, cut wires hanging out of the
    slot and sparking, and caution tape across it all. `frame` moves the sparks.
    """
    L = tampered()
    bx, by, bw, bh = LAYOUT["bay"]
    sy = LAYOUT["slot_y"][0]
    # Scorch round the slot and up the recess.
    for x, y in ((bx + 2, sy - 1), (bx + 3, sy - 2), (bx + 5, sy - 1), (bx + 12, sy - 1), (bx + 13, sy - 3),
                 (bx + 15, sy - 1), (bx + 9, sy - 4), (bx + 8, sy - 2)):
        L.set(x, y, "#1e1610")
    # A crack running up the recess from the slot.
    for x, y in ((bx + 10, sy - 1), (bx + 10, sy - 2), (bx + 11, sy - 3), (bx + 11, sy - 4), (bx + 12, sy - 5),
                 (bx + 12, sy - 6), (bx + 11, sy - 7), (bx + 12, sy - 8), (bx + 13, sy - 9)):
        L.set(x, y, "#120d08")
    # Cut wires hanging from the slot: red, blue, yellow, each with a bare copper end.
    ends = []
    for x0, colour, path in ((bx + 3, "#c03a2e", (0, 1, 2, 2)), (bx + 8, "#3a6ac0", (0, 0, 1, 1, 2)),
                             (bx + 13, "#d0b030", (0, 1, 1))):
        x = x0
        for i, dx in enumerate(path):
            x = x0 + dx
            L.set(x, sy + 1 + i, colour)
        end = (x, sy + 1 + len(path))
        L.set(*end, "#e0a060")
        ends.append(end)
    # Sparks off the cut ends: a burst at one wire, its embers flying, then the next wire.
    burst, embers = SPARK_FRAMES[frame % len(SPARK_FRAMES)]
    if burst is not None:
        ex, ey = ends[burst]
        L.set(ex, ey, "#ffffff")
        for dx, dy in ((1, 0), (-1, 0), (0, -1), (0, 1)):
            L.set(ex + dx, ey + dy, "#fff3a0")
        for dx, dy in ((2, -1), (-2, -1), (1, -2), (-1, 1)):
            L.set(ex + dx, ey + dy, "#ffb030")
    for wire, dx, dy, colour in embers:
        ex, ey = ends[wire]
        L.set(ex + dx, ey + dy, colour)

    # Police tape straight across the whole reader, lettered OUT OF ORDER, its right end lifting.
    left, right, y0 = 143, 197, 118
    L.rect(left, y0, right, y0 + 8, CAUTION[0])
    L.rect(left, y0, right, y0, "#f6dc6a")
    L.rect(left, y0 + 8, right, y0 + 8, "#8a6c14")
    text = "OUT OF ORDER"
    L.glyphs(F3, centred(F3, text, 170), y0 + 2, text, CAUTION[1])
    L.set(right, y0 - 1, CAUTION[0])
    L.set(right - 1, y0 - 1, "#c8a020")
    return L


# ── Keys ─────────────────────────────────────────────────────────────────────
KEY_STATES = {
    #           face       top hi     left hi    shade      right lo   legend     backlight
    "on":      ("#7a6446", "#9c8664", "#8a7454", "#4a3a26", "#5a4832", "#f0e2a2", "#86704d"),
    "off":     ("#5f4d35", "#6e5b40", "#66533a", "#3d2f1f", "#4b3b29", "#8a7854", None),
    "hover":   ("#86704f", "#b09a77", "#98825f", "#4a3a26", "#5a4832", "#fff4bc", "#957f5a"),
    "pressed": ("#6a5639", "#2e2214", "#5e4c32", "#4a3a26", "#4b3b29", "#e6d798", "#755f40"),
}


def draw_key(L, index, state):
    face, hi, lhi, lo, rlo, legend, glow = KEY_STATES[state]
    x, y, w, h = key_rect(index)
    label = KEYPAD[index][0]
    sunk = state == "pressed"
    L.outline(x, y, x + w - 1, y + h - 1, C["key_ol"], rounded=True)
    L.rect(x + 1, y + 1, x + w - 2, y + h - 2, face)
    if sunk:
        # The cap drops a pixel: its top edge falls into shadow and the lower bevel all but
        # disappears under the panel.
        L.rect(x + 1, y + 1, x + w - 2, y + 2, hi)
        L.rect(x + 1, y + h - 2, x + w - 2, y + h - 2, lo)
    else:
        L.rect(x + 1, y + 1, x + w - 2, y + 1, hi)
        L.rect(x + 1, y + 2, x + 1, y + h - 4, lhi)
        L.rect(x + 1, y + h - 3, x + w - 2, y + h - 2, lo)
        L.rect(x + w - 2, y + 2, x + w - 2, y + h - 3, rlo)
    legend_art(L, label, x, y + (1 if sunk else 0), w, legend, glow)


ICONS = {
    "clear": ["..#####", ".#....#", "#.....#", ".#....#", "..#####"],
}


def legend_art(L, label, x, y, w, colour, glow):
    """A key's legend, centred, with the backlight bleeding a pixel round it when lit."""
    art = Layer()
    if label in ICONS:
        rows = ICONS[label]
        gx = x + (w - len(rows[0])) // 2
        for iy, row in enumerate(rows):
            for ix, bit in enumerate(row):
                if bit == "#":
                    art.set(gx + ix, y + 3 + iy, colour)
    else:
        text = {"cancel": "X", "enter": "OK"}.get(label, label)
        art.glyphs(F5, x + (w - text_width(F5, text)) // 2, y + 2, text, colour)
    if glow:
        for (px, py) in art.px:
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                if (px + dx, py + dy) not in art.px:
                    L.set(px + dx, py + dy, glow)
    L.paste(art)


def wide_key_rect(name):
    return dict(WIDE_KEYS)[name], WIDE_Y, WIDE_W, KEY_H


def draw_wide_key(L, name, state):
    """CANCEL or ENTER: the keypad's own cap, twice as wide, under the grid."""
    face, hi, lhi, lo, rlo, legend, glow = KEY_STATES["on" if state == "lit" else state]
    if state == "lit":
        legend, glow = "#fffbe0", "#a08a62"
    x, y, w, h = wide_key_rect(name)
    sunk = state == "pressed"
    L.outline(x, y, x + w - 1, y + h - 1, C["key_ol"], rounded=True)
    L.rect(x + 1, y + 1, x + w - 2, y + h - 2, face)
    if sunk:
        L.rect(x + 1, y + 1, x + w - 2, y + 2, hi)
        L.rect(x + 1, y + h - 2, x + w - 2, y + h - 2, lo)
    else:
        L.rect(x + 1, y + 1, x + w - 2, y + 1, hi)
        L.rect(x + 1, y + 2, x + 1, y + h - 4, lhi)
        L.rect(x + 1, y + h - 3, x + w - 2, y + h - 2, lo)
        L.rect(x + w - 2, y + 2, x + w - 2, y + h - 3, rlo)
    legend_art(L, name, x, y + (1 if sunk else 0), w, legend, glow)


# ── Status lights ────────────────────────────────────────────────────────────
LED_COLOURS = {
    "green": ("#c8ffd8", "#46ff77", "#46ff7760"),
    "amber": ("#fff0c0", "#ffb454", "#ffb45460"),
    "red": ("#ffd0d0", "#ff4e5e", "#ff4e5e60"),
    "dim_green": ("#46c86e", "#2a8a48", "#46ff7720"),
}


def led(name, colour):
    L = Layer()
    x, y, _, _ = LAYOUT[name]
    if colour is None:
        L.rect(x + 1, y + 1, x + 3, y + 3, C["led_off"])
        L.set(x + 1, y + 1, C["led_off_hi"])
        return L
    core, body, halo = LED_COLOURS[colour]
    for dx, dy in ((0, 1), (0, 2), (0, 3), (4, 1), (4, 2), (4, 3), (1, 0), (2, 0), (3, 0), (1, 4), (2, 4), (3, 4)):
        L.set(x + dx, y + dy, halo)
    L.rect(x + 1, y + 1, x + 3, y + 3, body)
    L.set(x + 2, y + 2, core)
    L.set(x + 1, y + 1, core)
    return L


# ── Cash ─────────────────────────────────────────────────────────────────────
# Dollar bills, drawn lying flat as they come out of the slot toward the customer, after the game's
# note (_RMC14/Objects/Misc/spacecash.rsi): a dark outline, cream paper inside a framed border, grey
# corner marks, the grey portrait panel with its dark bust, a green seal and a grey one. Each is laid
# out on a trapezoid that starts inside the slot and widens as it nears, like the shelf below, with
# a crisp one-pixel outline whatever its size, and it darkens toward the slot, where it is still
# inside the machine. It comes out leading edge first. More money is more notes: each one under the
# top bill lies NOTE_LEAD rows further out and a little to one side, so their front edges show
# below it as separate bills. The window picks the stack from the amount.
CASH_FAR_Y, CASH_ROWS = 202, 12     # the trapezoid's far row, inside the slot, and a bill's depth
CASH_FAR_W, CASH_NEAR_W = 40, 61    # its width at the far row and at the near edge
CASH_MID = 84                       # the slot's centre
PRESENTED = CASH_ROWS
MAX_NOTES = 5
NOTE_SHIFTS = (0, -1, 2, -2, 1)     # each note's sideways shift, top note first
NOTE_LEAD = 2                       # rows each note under the top one lies further out
# How dark each row is, counted from the far edge: deep in the slot almost black, clear once out.
CASH_SHADE = (0.85, 0.7, 0.55, 0.4, 0.28, 0.18, 0.1, 0.05)
BILL = dict(outline="#2a2a2a", paper="#ccc7b4", paper_hi="#d6ceb7", border="#b8ab94", mark="#76736c",
            panel="#a19b8b", bust="#4e4a41", bust_lo="#444138", seal="#508460", seal_hi="#6ca07c")


def cash_span(row, shift=0):
    """Left and right ends of the trapezoid on `row`, counted from its far edge."""
    width = CASH_FAR_W + (CASH_NEAR_W - CASH_FAR_W) * row / (CASH_ROWS - 1)
    return round(CASH_MID - width / 2) + shift, round(CASH_MID + width / 2) - 1 + shift


def cash_shade(colour, row):
    r, g, b, _ = rgba(colour)
    keep = 1 - (CASH_SHADE[row] if row < len(CASH_SHADE) else 0)
    return "#%02x%02x%02x" % (int(r * keep), int(g * keep), int(b * keep))


def bill_colour(u, v, left, right, near):
    """The note at (u, v), each 0..1 across and down it; `left`, `right`, `near` mark its edge pixels."""
    if left or right or near:
        return BILL["outline"]
    if u < 0.05 or u > 0.95 or v > 0.9:
        return BILL["paper_hi"] if v > 0.9 and 0.05 <= u <= 0.95 else BILL["border"]
    if v < 0.08:
        return BILL["border"]
    if (0.08 <= u <= 0.17 or 0.83 <= u <= 0.92) and (0.16 <= v <= 0.34 or 0.62 <= v <= 0.8):
        return BILL["mark"]
    du, dv = (u - 0.5) / 0.19, (v - 0.48) / 0.36
    if du * du + dv * dv <= 1:
        # The portrait: a round head over rounded shoulders.
        if ((u - 0.5) / 0.065) ** 2 + ((v - 0.33) / 0.15) ** 2 <= 1:
            return BILL["bust"]
        if v >= 0.54 and ((u - 0.5) / 0.135) ** 2 + ((v - 0.86) / 0.32) ** 2 <= 1:
            return BILL["bust_lo"]
        return BILL["panel"]
    if ((u - 0.76) / 0.06) ** 2 + ((v - 0.48) / 0.16) ** 2 <= 1:
        return BILL["seal_hi"] if u < 0.76 and v < 0.45 else BILL["seal"]
    if ((u - 0.24) / 0.045) ** 2 + ((v - 0.48) / 0.12) ** 2 <= 1:
        return BILL["mark"]
    return BILL["paper"]


def draw_bill(L, drop, shift):
    """One bill with its front edge `drop` rows out of the slot; the part still inside is hidden."""
    for row in range(max(0, drop - CASH_ROWS), drop):
        x0, x1 = cash_span(row, shift)
        v = 1 - (drop - row - 0.5) / CASH_ROWS
        for x in range(x0, x1 + 1):
            u = (x - x0 + 0.5) / (x1 - x0 + 1)
            colour = bill_colour(u, v, x == x0, x == x1, row == drop - 1)
            L.set(x, CASH_FAR_Y + row, cash_shade(colour, row))


def cash(drop, light=1.0, notes=1):
    """
    A stack of `notes` bills `drop` rows out of the slot (0..CASH_ROWS), the shutter lit at `light`
    (0..1). The rows showing are each note's leading part, so they are seen sliding out or in.
    """
    L = Layer()
    if light > 0:
        # A dim lamp behind the open shutter, brightest just inside the lip.
        for y, f in ((201, 0.55), (202, 0.8), (203, 1.0), (204, 0.9), (205, 0.75), (206, 0.6), (207, 0.5), (208, 0.4), (209, 0.3)):
            k = light * f
            L.rect(56, y, 112, y, "#%02x%02x%02x" % (int(0x0a + 0x1e * k), int(0x0c + 0x2a * k), int(0x08 + 0x14 * k)))
    drop = min(drop, CASH_ROWS)
    if drop <= 0:
        return L
    notes = min(notes, MAX_NOTES)
    for i in reversed(range(notes)):
        draw_bill(L, drop + NOTE_LEAD * i, NOTE_SHIFTS[i])
    # The bills' shadow below the front-most edge.
    front = drop + NOTE_LEAD * (notes - 1)
    x0, x1 = cash_span(front - 1)
    L.rect(x0 + 1, CASH_FAR_Y + front, x1 - 1, CASH_FAR_Y + front, "#3d3324")
    return L


# ── Screen ───────────────────────────────────────────────────────────────────
def screen_on():
    L = Layer()
    glass(L, ("#030805", "#050c07", "#07110a", "#09150c", "#0b180e"))
    return L


# Power-on frame delays, timed to crt_startup.ogg: dark through the switch click, a dot of light
# as the tube warms, then the raster opens on the high-voltage thump at ~0.65 s.
POWER_ON_DELAYS = [0.30, 0.25, 0.08, 0.08, 0.12, 0.1]


def screen_power(frame):
    """CRT warm-up: dark, a dot of light, a line, the line opening into the raster, a flash."""
    x, y, w, h = LAYOUT["glass"]
    L = Layer()
    L.rect(x, y, x + w - 1, y + h - 1, "#020403")
    mid = y + h // 2
    if frame == 0:
        L.set(x + w // 2, mid, "#c8ffd8")
        L.set(x + w // 2 - 1, mid, "#46ff7780")
        L.set(x + w // 2 + 1, mid, "#46ff7780")
    elif frame == 1:
        L.rect(x + 6, mid - 1, x + w - 7, mid + 1, "#46ff7780")
        L.rect(x + 2, mid, x + w - 3, mid, "#e6fff0")
    elif frame == 2:
        L.rect(x, mid - 12, x + w - 1, mid + 12, "#1b4a2a")
        L.rect(x, mid - 2, x + w - 1, mid + 2, "#46ff77")
    elif frame == 3:
        L.paste(screen_on())
        L.rect(x, y, x + w - 1, y + h - 1, "#46ff7738")
    return L


PHOS, PHOS_DIM, PHOS_HOT = "#46ff77", "#1f9c43", "#b8ffcc"
BOOT_LOGO_DELAYS = [0.07, 0.07, 0.07, 0.07, 0.07, 1.0]


def boot_logo(frame):
    """
    The company mark coming up on the tube at boot, wiped on top to bottom behind a bright beam:
    frames 0-4 reveal it, frame 5 holds it with the name and the motto.
    """
    x, y, w, h = LAYOUT["glass"]
    L = screen_on()
    mark = Layer()
    lw = wy_logo(mark, 0, 0, h=13, w=8, m=3, gold=PHOS, grey=PHOS_DIM)
    ox, oy = x + (w - lw) // 2, y + 24
    art = Layer()
    for (px, py), c in mark.px.items():
        art.set(ox + px, oy + py, PHOS_HOT if c == rgba(C["gold_hi"]) else c)
    art.glyphs(F3, centred(F3, "WEYLAND-YUTANI", x + w // 2), oy + 19, "WEYLAND-YUTANI", PHOS)
    art.glyphs(F3, centred(F3, "BUILDING BETTER WORLDS", x + w // 2), oy + 27, "BUILDING BETTER WORLDS", PHOS_DIM)
    bottom = oy + 32
    if frame < 5:
        edge = oy + (frame + 1) * (bottom - oy) // 5
        L.paste(art, clip=(0, 0, W, edge))
        L.rect(x + 4, edge + 1, x + w - 5, edge + 1, PHOS_HOT)
        L.rect(x + 8, edge + 2, x + w - 9, edge + 2, "#46ff7760")
    else:
        L.paste(art)
    return L


# What a machine knocked out of service shows behind its console: no mark, nobody's name, just a
# tube that will not hold steady - a hot tear flicking across it, a band of rows slipping sideways,
# the odd surge washing it bright, every other line sagging. The window spews its corrupted console
# over this, so it stays dark enough to read through.
def fault_screen(kind):
    """One frame of the out-of-order tube: calm, tear, tear_low, slip, interlace, surge or sag."""
    x, y, w, h = LAYOUT["glass"]
    L = screen_on()

    def scale_rows(rows, f):
        for (px, py), (r, g, b, al) in list(L.px.items()):
            if x <= px < x + w and py in rows:
                L.px[(px, py)] = (min(255, int(r * f)), min(255, int(g * f)), min(255, int(b * f)), al)

    light = Layer()
    if kind in ("tear", "tear_low"):
        # A hot tear across the tube with a smear of glow under it.
        ty = y + (19 if kind == "tear" else 63)
        L.rect(x, ty, x + w - 1, ty, PHOS_HOT)
        light.rect(x, ty + 1, x + w - 1, ty + 2, "#46ff7748")
        light.rect(x + 12, ty - 1, x + 47, ty - 1, "#46ff7730")
    elif kind == "slip":
        # A band of rows slipped sideways and wrapped round, the sync lost for a moment.
        for yy in range(y + 38, y + 51):
            row = [L.get(xx, yy) for xx in range(x, x + w)]
            shift = 9 + (yy % 4) * 4
            for i in range(w):
                c = row[(i - shift) % w]
                if c:
                    L.set(x + i, yy, c)
        light.rect(x, y + 37, x + w - 1, y + 37, "#46ff7738")
        light.rect(x, y + 51, x + w - 1, y + 51, "#46ff7720")
    elif kind == "interlace":
        # Every other line sagging.
        scale_rows(range(y, y + h, 2), 0.45)
    elif kind == "surge":
        # A surge washing the whole tube with light for a frame.
        light.rect(x, y, x + w - 1, y + h - 1, "#46ff7726")
        light.rect(x, y + h // 2 - 1, x + w - 1, y + h // 2 + 1, "#46ff7730")
    elif kind == "sag":
        # The tube sagging for a moment: everything a step dimmer.
        scale_rows(range(y, y + h), 0.6)
    L.blend(light)
    return L


# The loop: long calm stretches broken by flickers, on an uneven beat so it never reads as a metronome.
FAULT_LOOP = [("calm", 0.45), ("tear", 0.05), ("calm", 0.3), ("interlace", 0.07), ("calm", 0.6),
              ("slip", 0.06), ("calm", 0.2), ("surge", 0.04), ("calm", 0.5), ("tear_low", 0.05),
              ("sag", 0.08), ("calm", 0.35), ("slip", 0.05), ("interlace", 0.06)]
FAULT_FRAMES = [kind for kind, _ in FAULT_LOOP]
FAULT_DELAYS = [delay for _, delay in FAULT_LOOP]


# ── RSI output ───────────────────────────────────────────────────────────────
def write_rsi(name, size, states):
    """states: list of (state name, [layers], delays or None)."""
    path = TEXTURES / f"{name}.rsi"
    path.mkdir(parents=True, exist_ok=True)
    for old in path.glob("*.png"):
        old.unlink()
    meta = {"version": 1, "license": LICENSE, "copyright": COPYRIGHT,
            "size": {"x": size[2], "y": size[3]}, "states": []}
    for state, frames, delays in states:
        sheet = Image.new("RGBA", (size[2] * len(frames), size[3]), (0, 0, 0, 0))
        for i, frame in enumerate(frames):
            sheet.paste(frame.image(size), (i * size[2], 0))
        sheet.save(path / f"{state}.png")
        entry = {"name": state}
        if delays:
            entry["delays"] = [delays]
        meta["states"].append(entry)
    (path / "meta.json").write_text(json.dumps(meta, indent=4) + "\n", encoding="utf-8", newline="\n")
    return path


def key_layer(index, state):
    L = Layer()
    draw_key(L, index, state)
    return L


def wide_key_layer(name, state):
    L = Layer()
    draw_wide_key(L, name, state)
    return L


def shift(layer, src, dst):
    """Moves a layer drawn at `src` (x, y) onto `dst`, so sprites drawn in place share one RSI size."""
    out = Layer()
    for (px, py), c in layer.px.items():
        out.set(px - src[0] + dst[0], py - src[1] + dst[1], c)
    return out


# The note counter's run (atm_cash.wav, played by the server as cash comes out or goes in). The slot's
# frames are timed to it: dispensing, the shutter lights as the motor starts, the notes' edges show
# while they are counted, and the stack comes out as the counting stops; depositing, the notes are
# drawn in first, then counted. Each animation lasts exactly as long as the sound.
CASH_WAV = REPO / "Content.CMU/Resources/Audio/CMU14/ColonyEconomy/atm_cash.wav"


def cash_timing(tick=0.02):
    """(sound length, start and end of the counting) in seconds."""
    length, levels = wav_levels(CASH_WAV, tick)
    loud = [i for i, level in enumerate(levels) if level >= 0.5 * max(levels)]
    return length, loud[0] * tick, (loud[-1] + 1) * tick


CASH_SECONDS, COUNT_START, COUNT_END = cash_timing()
DISPENSE_DELAYS = [round(d, 3) for d in (COUNT_START, COUNT_END - COUNT_START - 0.2, 0.1, 0.1,
                                         max(0.05, CASH_SECONDS - COUNT_END))]
DEPOSIT_DELAYS = [round(d, 3) for d in (0.1, 0.1, 0.1, COUNT_END - 0.3, 0.15,
                                        max(0.05, CASH_SECONDS - COUNT_END - 0.15))]


def dispense(n):
    return [cash(0, 0.4, notes=n), cash(0, 1.0, notes=n), cash(PRESENTED // 3, notes=n),
            cash(2 * PRESENTED // 3, notes=n), cash(PRESENTED, notes=n)]


def take(n):
    # Taken: the notes are gone and the shutter's lamp fades.
    return [cash(0, 0.8, notes=n), cash(0, 0.5, notes=n), cash(0, 0.0, notes=n)]


def deposit(n):
    return [cash(PRESENTED, notes=n), cash(2 * PRESENTED // 3, notes=n), cash(PRESENTED // 3, notes=n), cash(0, 1.0, notes=n),
            cash(0, 0.5, notes=n), cash(0, 0.0, notes=n)]


def export_assets():
    TEXTURES.mkdir(parents=True, exist_ok=True)
    base = draw_base()
    vx, vy, vw, vh = VIEW
    base.image().crop((vx, vy, vx + vw, vy + vh)).save(TEXTURES / "atm_base.png")

    key_states = []
    for i, (label, _, _) in enumerate(KEYPAD):
        x, y, _, _ = key_rect(i)
        for state in KEY_STATES:
            key_states.append((f"{label}_{state}", [shift(key_layer(i, state), (x, y), KEY_ORIGIN)], None))
    write_rsi("atm_keys", (KEY_ORIGIN[0], KEY_ORIGIN[1], KEY_W, KEY_H), key_states)

    first = wide_key_rect(WIDE_KEYS[0][0])
    wide_states = []
    for name, _ in WIDE_KEYS:
        x, y, _, _ = wide_key_rect(name)
        for state in ("on", "off", "hover", "pressed"):
            wide_states.append((f"{name}_{state}", [shift(wide_key_layer(name, state), (x, y), first[:2])], None))
        wide_states.append((f"{name}_ready", [shift(wide_key_layer(name, s), (x, y), first[:2]) for s in ("lit", "on")],
                            [0.6, 0.6]))
    write_rsi("atm_fkeys", first, wide_states)

    write_rsi("atm_reader", LAYOUT["reader"], [
        ("lights_idle", [rails(C["bracket"], None)], None),
        ("lights_ready", [rails("#7dffa0", "#46ff7740"), rails(C["bracket"], None)], [0.6, 0.6]),
        ("lights_reading", [rails("#ffd27a", "#ffb45440"), rails("#8a6a2a", None)], [0.12, 0.12]),
        ("lights_ok", [rails("#7dffa0", "#46ff7740")], None),
        ("lights_wait", [rails("#ffd27a", "#ffb45440")], None),
        ("lights_locked", [rails("#ff8a8a", "#ff4e5e40"), rails("#6a2a2a", None)], [0.3, 0.3]),
        ("bay_glass", [bay_glass()], None),
        ("tampered", [tampered()], None),
        ("broken", [broken(frame) for frame, _ in SPARKS], [seconds for _, seconds in SPARKS]),
    ])

    # One set of states per stack height: dispense_1 .. dispense_5 and so on.
    cash_states = []
    for n in range(1, MAX_NOTES + 1):
        cash_states += [
            (f"dispense_{n}", dispense(n), DISPENSE_DELAYS),
            (f"dispensed_{n}", [dispense(n)[-1]], None),
            (f"take_{n}", take(n), [0.08, 0.1, 0.1]),
            (f"deposit_{n}", deposit(n), DEPOSIT_DELAYS),
        ]
    write_rsi("atm_cash", LAYOUT["cash"], cash_states)

    feed = [2, 4, 6, 8, 10, 12, RECEIPT_ROWS]
    write_rsi("atm_receipt", LAYOUT["receipt"], [
        ("print", [receipt(drop) for drop in feed], PRINT_DELAYS),
        ("presented", [receipt(RECEIPT_ROWS)], None),
        ("take", [receipt(0)], [0.05]),
    ])

    led_states = [("off", [led("led_power", None)], None)]
    for colour in LED_COLOURS:
        led_states.append((colour, [led("led_power", colour)], None))
    led_states.append(("amber_blink", [led("led_power", "amber"), led("led_power", None)], [0.12, 0.12]))
    led_states.append(("red_blink", [led("led_power", "red"), led("led_power", None)], [0.3, 0.3]))
    # The machine idling: a heartbeat flick on the power light, and sporadic traffic on the
    # activity light - uneven on purpose, so it reads as a network rather than a metronome.
    led_states.append(("green_pulse", [led("led_power", "green"), led("led_power", "dim_green")], [2.6, 0.12]))
    idle = [None, "amber", None, "amber", None, "amber", None, "amber"]
    led_states.append(("amber_idle", [led("led_power", c) for c in idle], [1.3, 0.07, 0.12, 0.06, 2.1, 0.09, 0.8, 0.05]))
    busy = ["amber", None, "amber", None, "amber", None]
    led_states.append(("amber_busy", [led("led_power", c) for c in busy], [0.05, 0.06, 0.04, 0.1, 0.06, 0.04]))
    write_rsi("atm_leds", LAYOUT["led_power"], led_states)

    write_rsi("atm_screen", LAYOUT["glass"], [
        ("on", [screen_on()], None),
        ("power_on", [screen_power(-1)] + [screen_power(i) for i in range(4)] + [screen_on()], POWER_ON_DELAYS),
        ("boot_logo", [boot_logo(i) for i in range(6)], BOOT_LOGO_DELAYS),
        # Never quite steady: tears flicking across it, rows slipping, surges, the tube sagging.
        ("fault", [fault_screen(kind) for kind in FAULT_FRAMES], FAULT_DELAYS),
    ])

    # The previous layout's sprites, superseded by the ones above.
    for gone in ("atm_enter.rsi",):
        old = TEXTURES / gone
        if old.exists():
            for f in old.iterdir():
                f.unlink()
            old.rmdir()
    return base


# ── Review material ──────────────────────────────────────────────────────────
# The window draws the inserted card's own sprite in the reader; these mirror its maths so the review
# GIF shows the real thing. Keep in step with ColonyAtmWindow.ReaderCard.
SAMPLE_CARDS = [REPO / "Resources/Textures/_RMC14/Objects/CMIDs/id.rsi/plain.png",
                REPO / "Resources/Textures/Objects/Misc/id_cards.rsi/gold.png"]
# Keyframes (seconds, frame top in art pixels) - keep in step with ColonyAtmWindow.ReaderCard.
# In: brought down to the slot, a beat to line it up, pushed home a pixel past, then it settles.
INSERT_KEYS = [(0.0, 86), (0.30, 104), (0.40, 104), (0.70, 116), (0.78, 115)]
# Out: the machine pops it up, it is held a moment, then lifted away.
EJECT_KEYS = [(0.0, 115), (0.12, 107), (0.32, 107), (0.60, 86)]


def smooth(t):
    return t * t * (3 - 2 * t)


def at(keys, t):
    for (t0, v0), (t1, v1) in zip(keys, keys[1:]):
        if t <= t1:
            return round(v0 + (v1 - v0) * smooth((t - t0) / (t1 - t0) if t1 > t0 else 1))
    return keys[-1][1]


def reader_card(top, sample=0):
    """The card with its frame's top edge at `top`, hidden where it has gone into the slot."""
    icon = Image.open(SAMPLE_CARDS[sample]).convert("RGBA").crop((0, 0, 32, 32))
    # A card wider than it is tall goes in on its side, a quarter turn clockwise, as the window does.
    bbox = icon.getchannel("A").getbbox()
    if bbox and bbox[2] - bbox[0] > bbox[3] - bbox[1]:
        icon = icon.transpose(Image.Transpose.ROTATE_270)
    bx, _, bw, _ = LAYOUT["bay"]
    cx, cy, cw, _ = LAYOUT["card"]
    sy = LAYOUT["slot_y"][0]
    left = bx + bw // 2 - 16           # the 32-wide frame centred on the recess
    L = Layer()
    for y in range(32):
        for x in range(32):
            c = icon.getpixel((x, y))
            px, py = left + x, top + y
            if c[3] and cx <= px < cx + cw and cy <= py < sy:
                L.set(px, py, c)
    return L


def seated(sample=0):
    out = Layer()
    out.paste(reader_card(INSERT_KEYS[-1][1], sample))
    out.blend(bay_glass())
    return out


def compose(layers, scale=3):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 255))
    for layer in layers:
        img.alpha_composite(layer.image())
    vx, vy, vw, vh = VIEW
    return img.crop((vx, vy, vx + vw, vy + vh)).resize((vw * scale, vh * scale), Image.NEAREST)


def rects(layer):
    runs = {}
    for y in range(H):
        x = 0
        while x < W:
            c = layer.px.get((x, y))
            if c is None:
                x += 1
                continue
            x1 = x
            while x1 + 1 < W and layer.px.get((x1 + 1, y)) == c:
                x1 += 1
            runs[(x, y)] = (x1, c)
            x = x1 + 1
    out, used = [], set()
    for (x, y), (x1, c) in sorted(runs.items(), key=lambda kv: (kv[0][1], kv[0][0])):
        if (x, y) in used:
            continue
        y1 = y
        while runs.get((x, y1 + 1)) == (x1, c) and (x, y1 + 1) not in used:
            y1 += 1
            used.add((x, y1))
        out.append((x, y, x1 - x + 1, y1 - y + 1, c))
    return out


def svg_group(layer, visible):
    def fill(c):
        return "#%02x%02x%02x" % c[:3] + ("" if c[3] == 255 else f'" fill-opacity="{c[3] / 255:.2f}')
    body = "".join(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{fill(c)}"/>'
                   for x, y, w, h, c in rects(layer))
    return f'  <g id="{layer.name}"{"" if visible else " display=\"none\""}>{body}</g>\n'


def named(name, layer):
    layer.name = name
    return layer


def keys_for(lit, wide):
    L = Layer()
    for i, (label, _, _) in enumerate(KEYPAD):
        draw_key(L, i, "on" if label in lit else "off")
    for name, state in wide.items():
        draw_wide_key(L, name, state)
    return L


def export_review(base):
    keys_menu = keys_for(list("123456"), {"cancel": "on", "enter": "off"})
    keys_pin = keys_for(list("1234567890") + ["00", "clear"], {"cancel": "on", "enter": "on"})
    for i, (label, _, _) in enumerate(KEYPAD):
        if label == "5":
            draw_key(keys_pin, i, "pressed")
    keys_result = keys_for([], {"cancel": "on", "enter": "lit"})
    green, amber, red = (rails("#7dffa0", "#46ff7740"), rails("#ffd27a", "#ffb45440"), rails("#ff8a8a", "#ff4e5e40"))

    layers = [
        named("base", base),
        named("screen-on", screen_on()),
        named("keys-main-menu", keys_menu),
        named("keys-pin-entry", keys_pin),
        named("keys-result", keys_result),
        named("card-seated", seated()),
        named("reader-ready", rails("#7dffa0", "#46ff7740")),
        named("reader-reading", rails("#ffd27a", "#ffb45440")),
        named("reader-locked", rails("#ff8a8a", "#ff4e5e40")),
        named("tampered", tampered()),
        named("cash-dispensed", cash(PRESENTED, notes=3)),
        named("led-power-green", led("led_power", "green")),
        named("led-activity-amber", led("led_activity", "amber")),
        named("led-activity-red", led("led_activity", "red")),
    ]
    shown = {"base", "screen-on", "keys-main-menu", "card-seated", "reader-ready", "led-power-green"}
    vx, vy, vw, vh = VIEW
    svg = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{vw * 3}" height="{vh * 3}" '
           f'viewBox="{vx} {vy} {vw} {vh}" shape-rendering="crispEdges">\n',
           "  <!-- Colony ATM, pixel art. One unit = one art pixel. Each <g> is a machine state;\n"
           "       toggle display to switch states. Generated by atm_pixel_art.py. -->\n"]
    svg += [svg_group(layer, layer.name in shown) for layer in layers]
    svg.append("</svg>\n")
    (REVIEW / "atm_pixel.svg").write_text("".join(svg), encoding="utf-8", newline="\n")

    for old in list(REVIEW.glob("preview_*.png")) + list(REVIEW.glob("anim_*.gif")):
        old.unlink()
    previews = {
        "idle": [base],
        "main_menu": [base, screen_on(), keys_menu, green, seated(), led("led_power", "green")],
        "pin_entry": [base, screen_on(), keys_pin, amber, seated(1), led("led_power", "green"),
                      led("led_activity", "amber")],
        "dispensing": [base, screen_on(), keys_result, green, seated(), cash(PRESENTED, notes=3), led("led_power", "green"),
                       led("led_activity", "amber")],
        "locked": [base, screen_on(), keys_result, red, seated(), led("led_power", "green"),
                   led("led_activity", "red")],
        "tampered": [base, tampered(), led("led_power", "green")],
        "out_of_order": [base, fault_screen("calm"), keys_for([], {n: "off" for n, _ in WIDE_KEYS}),
                   rails("#ff8a8a", "#ff4e5e40"), broken(0), led("led_power", "red"), led("led_activity", "red")],
    }
    for name, stack in previews.items():
        compose(stack).save(REVIEW / f"preview_{name}.png")

    # Animation strips as GIFs, cropped round the part that moves and blown up to read the pixels.
    def gif(name, rect, frames, delays, scale=6):
        x, y, w, h = rect
        imgs = []
        for frame in frames:
            full = Image.new("RGBA", (W, H))
            full.alpha_composite(base.image())
            for layer in frame:
                full.alpha_composite(layer.image())
            imgs.append(full.crop((x, y, x + w, y + h)).resize((w * scale, h * scale), Image.NEAREST).convert("RGB"))
        imgs[0].save(REVIEW / f"anim_{name}.gif", save_all=True, append_images=imgs[1:],
                     duration=[int(d * 1000) for d in delays], loop=0)

    reader_box = (140, 84, 60, 60)
    tick = 0.04
    for sample in range(len(SAMPLE_CARDS)):
        going_in = [[reader_card(at(INSERT_KEYS, i * tick), sample), bay_glass(), rails(C["bracket"], None)]
                    for i in range(int(INSERT_KEYS[-1][0] / tick) + 1)]
        coming_out = [[reader_card(at(EJECT_KEYS, i * tick), sample), bay_glass(), rails("#7dffa0", "#46ff7740")]
                      for i in range(int(EJECT_KEYS[-1][0] / tick) + 1)]
        seq = ([[rails("#7dffa0", "#46ff7740")]] + going_in
               + [[seated(sample), rails("#ffd27a", "#ffb45440")], [seated(sample), rails("#8a6a2a", None)]] * 2
               + [[seated(sample), rails("#7dffa0", "#46ff7740")]] + coming_out + [[rails("#7dffa0", "#46ff7740")]])
        gif(f"card_slide_{sample}", reader_box, seq,
            [0.6] + [tick] * len(going_in) + [0.12] * 4 + [0.8] + [tick] * len(coming_out) + [0.6])
    cash_box = (36, 186, 98, 36)
    # Every stack height in turn: $1-49 is one note, up to five for $500 and more.
    stacks, stack_delays = [], []
    for n in range(1, MAX_NOTES + 1):
        stacks += [[]] + [[f] for f in dispense(n)] + [[cash(PRESENTED, notes=n)]] + [[f] for f in take(n)]
        stack_delays += [0.4] + DISPENSE_DELAYS + [0.9, 0.08, 0.1, 0.1]
    gif("cash_dispense_take", cash_box, stacks, stack_delays)
    gif("cash_deposit", cash_box, [[]] + [[f] for f in deposit(3)], [0.5] + DEPOSIT_DELAYS)
    key_frames = [[key_layer(4, s)] for s in ("off", "on", "hover", "pressed", "hover", "on")]
    gif("key_states", (142, 156, 58, 34), key_frames, [0.6, 0.6, 0.5, 0.25, 0.5, 0.6])
    wide_frames = [[wide_key_layer(n, s) for n, _ in WIDE_KEYS] for s in ("off", "on", "hover", "pressed", "lit", "on")]
    gif("cancel_enter_keys", (142, 200, 58, 20), wide_frames, [0.6, 0.6, 0.5, 0.25, 0.5, 0.6])
    # The out-of-order screen's loop, as the window plays the fault state.
    gif("out_of_order", (27, 98, 115, 92), [[fault_screen(kind)] for kind in FAULT_FRAMES], FAULT_DELAYS, scale=3)
    gif("screen_power_on", (27, 98, 115, 92),
        [[screen_power(i)] for i in range(-1, 4)] + [[boot_logo(i)] for i in range(6)] + [[screen_on()]],
        POWER_ON_DELAYS[:-1] + BOOT_LOGO_DELAYS + [0.6], scale=3)


if __name__ == "__main__":
    base = export_assets()
    REVIEW.mkdir(exist_ok=True)
    export_review(base)
    print("assets ->", TEXTURES)
    print("review ->", REVIEW)
