"""
Pixel-art card payment terminal: the window art and the item sprite.

Run from anywhere:  python card_terminal_pixel_art.py

ColonyCardTerminalWindow places each sprite with the same grid coordinates as LAYOUT below.
"""
import json
from pathlib import Path

from PIL import Image

W, H = 112, 228
HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
WINDOW_ART = REPO / "Content.CMU/Resources/Textures/CMU14/ColonyEconomy"
ITEM_RSI = REPO / "Content.CMU/Resources/Textures/CMU14/Objects/Devices/card_terminal.rsi"
LICENSE = "CC-BY-SA-3.0"
COPYRIGHT = ("Pixel-art card terminal drawn for CMU, generated by "
             "Content.CMU/Design/ColonyEconomy/CardTerminalPixelArt/card_terminal_pixel_art.py")

LAYOUT = {
    "body": (6, 24, 100, 200),
    "head": (6, 24, 100, 26),
    "slit": (20, 26, 72, 3),
    "receipt": (16, 0, 80, 30),
    "logo": (12, 35, 27, 7),
    "pad": (42, 30, 28, 17),
    "lights": (73, 36, 23, 5),
    "bezel": (10, 53, 92, 92),
    "glass": (16, 58, 80, 82),
}
KEY_W, KEY_H = 24, 11
KEY_X, KEY_Y, PITCH_X, PITCH_Y = 16, 154, 28, 13
KEYPAD = (("1", 0, 0), ("2", 1, 0), ("3", 2, 0), ("4", 0, 1), ("5", 1, 1), ("6", 2, 1),
          ("7", 0, 2), ("8", 1, 2), ("9", 2, 2), ("menu", 0, 3), ("0", 1, 3), ("00", 2, 3),
          ("cancel", 0, 4), ("clear", 1, 4), ("enter", 2, 4))

C = dict(outline="#0b0b0c", body="#2a2c2f", body_hi="#45484d", body_lo="#18191b", slot="#050505",
         bezel="#131416", bezel_hi="#2c2e32", led_off="#3a2c0c",
         gold="#b8892a", gold_hi="#e0b24a", gold_lo="#7d5a14", gold_ink="#5a410c")

F3 = {
    "A": [".#.", "#.#", "###", "#.#", "#.#"], "D": ["##.", "#.#", "#.#", "#.#", "##."],
    "I": ["###", ".#.", ".#.", ".#.", "###"],
    "E": ["###", "#..", "##.", "#..", "###"], "L": ["#..", "#..", "#..", "#..", "###"],
    "M": ["#...#", "##.##", "#.#.#", "#...#", "#...#"], "N": ["#..#", "##.#", "#.##", "#..#", "#..#"],
    "P": ["##.", "#.#", "##.", "#..", "#.."], "R": ["##.", "#.#", "##.", "#.#", "#.#"],
    "T": ["###", ".#.", ".#.", ".#.", ".#."], "U": ["#.#", "#.#", "#.#", "#.#", "###"],
    "W": ["#...#", "#...#", "#.#.#", "##.##", "#...#"], "Y": ["#.#", "#.#", ".#.", ".#.", ".#."],
    "-": ["...", "...", "###", "...", "..."], " ": ["...", "...", "...", "...", "..."],
}
F5 = {
    "0": [".###.", "#...#", "#..##", "#.#.#", "##..#", "#...#", ".###."],
    "1": ["..#..", ".##..", "..#..", "..#..", "..#..", "..#..", ".###."],
    "2": [".###.", "#...#", "....#", "..##.", ".#...", "#....", "#####"],
    "3": ["####.", "....#", "....#", ".###.", "....#", "....#", "####."],
    "4": ["...#.", "..##.", ".#.#.", "#..#.", "#####", "...#.", "...#."],
    "5": ["#####", "#....", "####.", "....#", "....#", "#...#", ".###."],
    "6": ["..##.", ".#...", "#....", "####.", "#...#", "#...#", ".###."],
    "7": ["#####", "....#", "...#.", "..#..", ".#...", ".#...", ".#..."],
    "8": [".###.", "#...#", "#...#", ".###.", "#...#", "#...#", ".###."],
    "9": [".###.", "#...#", "#...#", ".####", "....#", "...#.", ".##.."],
    "O": [".###.", "#...#", "#...#", "#...#", "#...#", "#...#", ".###."],
    "K": ["#...#", "#..#.", "#.#..", "##...", "#.#..", "#..#.", "#...#"],
    "X": ["#...#", "#...#", ".#.#.", "..#..", ".#.#.", "#...#", "#...#"],
}
CLEAR_ICON = ["..#####", ".#....#", "#.....#", ".#....#", "..#####"]


def rgba(c):
    if isinstance(c, tuple):
        return c
    c = c.lstrip("#")
    return int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16), int(c[6:8], 16) if len(c) == 8 else 255


def shade(colour, keep):
    r, g, b, a = rgba(colour)
    return min(255, int(r * keep)), min(255, int(g * keep)), min(255, int(b * keep)), a


class Layer:
    def __init__(self, w=W, h=H):
        self.w, self.h = w, h
        self.px = {}

    def set(self, x, y, c):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.px[(x, y)] = rgba(c)

    def rect(self, x0, y0, x1, y1, c):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.set(x, y, c)

    def glyphs(self, font, x, y, text, c, gap=1):
        for ch in text:
            g = font.get(ch, font.get(" ", [".."]))
            for gy, row in enumerate(g):
                for gx, bit in enumerate(row):
                    if bit == "#":
                        self.set(x + gx, y + gy, c)
            x += len(g[0]) + gap

    def bitmap(self, rows, x, y, c):
        for gy, row in enumerate(rows):
            for gx, bit in enumerate(row):
                if bit == "#":
                    self.set(x + gx, y + gy, c)

    def paste(self, other):
        self.px.update(other.px)

    def image(self, rect=None):
        x0, y0, w, h = rect or (0, 0, self.w, self.h)
        img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        for (x, y), c in self.px.items():
            if x0 <= x < x0 + w and y0 <= y < y0 + h:
                img.putpixel((x - x0, y - y0), c)
        return img


def text_width(font, text, gap=1):
    return sum(len(font.get(ch, font.get(" ", [".."]))[0]) + gap for ch in text) - gap


def bevel(L, x0, y0, x1, y1, hi, lo, raised=True):
    top, bottom = (hi, lo) if raised else (lo, hi)
    L.rect(x0, y0, x1, y0, top)
    L.rect(x0, y0, x0, y1, top)
    L.rect(x0, y1, x1, y1, bottom)
    L.rect(x1, y0, x1, y1, bottom)


def rounded(L, x0, y0, x1, y1, r, c):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            dx = max(x0 + r - x, 0, x - (x1 - r))
            dy = max(y0 + r - y, 0, y - (y1 - r))
            if dx * dx + dy * dy <= r * r:
                L.set(x, y, c)


# ── The device ───────────────────────────────────────────────────────────────
# A modern handheld TPV in Weyland-Yutani colours: a charcoal slab, the gold printer-roll head on top
# with the paper slit along its edge, a CRT-style screen and the keypad under it.
def wy_logo(L, x0, y0, h, w, m, gold, hi, cut):
    """The geometric W-Y mark: four 45-degree strokes and three notches."""
    b0 = x0 + 2 * (h - 1)
    d0 = b0 + 2 * (h - 1)
    for y in range(h):
        for xs in (x0 + y, b0 - y, b0 + y, d0 - y):
            L.rect(xs, y0 + y, xs + w - 1, y0 + y, gold if y else hi)
        for left, right in ((x0 + y + w + m, b0 - y - 1 - m), (b0 + y + w + m, d0 - y - 1 - m),
                            (b0 - y + w + m, b0 + y - 1 - m)):
            if left <= right:
                L.rect(left, y0 + y, right, y0 + y, cut)


def draw_body():
    L = Layer()
    x, y, w, h = LAYOUT["body"]
    x1, y1 = x + w - 1, y + h - 1
    rounded(L, x, y, x1, y1, 8, C["outline"])
    rounded(L, x + 1, y + 1, x1 - 1, y1 - 1, 7, C["body_hi"])
    rounded(L, x + 2, y + 2, x1 - 1, y1 - 1, 7, C["body_lo"])
    rounded(L, x + 2, y + 2, x1 - 2, y1 - 2, 6, C["body"])

    # The printer-roll head: gold, lit along its rounded top, a dark seam where it meets the body.
    _, hy, _, hh = LAYOUT["head"]
    head = Layer()
    rounded(head, x + 1, hy + 1, x1 - 1, hy + hh + 6, 7, C["gold"])
    for (px, py), _ in list(head.px.items()):
        if py <= hy + hh:
            depth = py - hy
            colour = C["gold_hi"] if depth <= 2 else C["gold"] if depth < hh - 4 else C["gold_lo"]
            L.set(px, py, colour)
    L.rect(x + 1, hy + hh, x1 - 1, hy + hh, C["outline"])
    L.rect(x + 2, hy + hh + 1, x1 - 2, hy + hh + 1, C["body_lo"])

    sx, sy, sw, sh = LAYOUT["slit"]
    L.rect(sx, sy, sx + sw - 1, sy + sh - 1, C["slot"])
    for i in range(sx, sx + sw, 2):
        L.set(i, sy + sh, C["gold_lo"])

    lx, ly, lw, lh = LAYOUT["logo"]
    wy_logo(L, lx, ly, lh, 3, 1, C["gold_ink"], C["gold_lo"], C["gold"])
    L.paste(pad_symbol(C["gold_ink"]))
    L.paste(lights(0))

    # A CRT in a thick bezel: rounded corners, a lit lip above and a deep shadow inside.
    bx, by, bw, bh = LAYOUT["bezel"]
    rounded(L, bx, by, bx + bw - 1, by + bh - 1, 7, C["bezel"])
    rounded(L, bx + 1, by + 1, bx + bw - 2, by + 3, 6, C["bezel_hi"])
    rounded(L, bx + 2, by + 3, bx + bw - 3, by + bh - 3, 6, C["bezel"])
    gx, gy, gw, gh = LAYOUT["glass"]
    rounded(L, gx - 1, gy - 1, gx + gw, gy + gh, 6, "#050606")

    brand = "WEYLAND-YUTANI"
    L.glyphs(F3, (W - text_width(F3, brand)) // 2, by + bh + 3, brand, "#5d6268")

    for i in range(len(KEYPAD)):
        kx, ky, _, _ = key_rect(i)
        L.rect(kx + 1, ky + KEY_H, kx + KEY_W - 2, ky + KEY_H, "#121315")
        draw_key(L, i, "on")
    return L


def pad_symbol(colour):
    """The contactless mark on the head: a card beside four widening waves."""
    L = Layer()
    ax, ay, aw, ah = LAYOUT["pad"]
    cx, cy = ax + aw // 2, ay + ah // 2
    L.rect(cx - 12, cy - 3, cx - 5, cy + 3, colour)
    L.rect(cx - 11, cy - 2, cx - 6, cy + 2, C["gold"])
    L.rect(cx - 11, cy - 1, cx - 6, cy - 1, colour)
    for i in range(4):
        half = 1 + i
        x = cx - 1 + i * 3
        for dy in range(-half, half + 1):
            L.set(x + (1 if abs(dy) < half else 0), cy + dy, colour)
    return L


# ── Keys ─────────────────────────────────────────────────────────────────────
KEY_FACES = {
    "digit": ("#3b3e43", "#575b61", "#222427", "#d8dadc"),
    "cancel": ("#9b2f2a", "#c4544c", "#5e1a17", "#ffe2dc"),
    "clear": ("#b8901e", "#dcb84a", "#6e5510", "#2a2006"),
    "enter": ("#2f7a35", "#56a25b", "#1a4a1e", "#e4ffe4"),
}


def key_rect(index):
    _, col, row = KEYPAD[index]
    return KEY_X + col * PITCH_X, KEY_Y + row * PITCH_Y, KEY_W, KEY_H


def draw_key(L, index, state):
    label = KEYPAD[index][0]
    face, hi, lo, legend = KEY_FACES.get(label, KEY_FACES["digit"])
    if state == "off":
        face, hi, legend = shade(face, 0.7), shade(hi, 0.7), shade(legend, 0.45)
    elif state == "hover":
        face, hi = shade(face, 1.18), shade(hi, 1.15)
    x, y, w, h = key_rect(index)
    sunk = state == "pressed"
    L.rect(x, y, x + w - 1, y + h - 1, C["outline"])
    L.rect(x + 1, y + 1, x + w - 2, y + h - 2, face)
    if sunk:
        L.rect(x + 1, y + 1, x + w - 2, y + 1, lo)
    else:
        L.rect(x + 1, y + 1, x + w - 2, y + 1, hi)
        L.rect(x + 1, y + h - 2, x + w - 2, y + h - 2, lo)
    top = y + 2 + (1 if sunk else 0)
    if label == "clear":
        L.bitmap(CLEAR_ICON, x + (w - len(CLEAR_ICON[0])) // 2, top + 1, legend)
    elif label == "menu":
        L.glyphs(F3, x + (w - text_width(F3, "MENU")) // 2, top + 1, "MENU", legend)
    else:
        text = {"cancel": "X", "enter": "OK"}.get(label, label)
        L.glyphs(F5, x + (w - text_width(F5, text)) // 2, top, text, legend)


def key_layer(index, state):
    L = Layer()
    draw_key(L, index, state)
    x, y, _, _ = key_rect(index)
    out = Layer()
    for (px, py), c in L.px.items():
        out.set(px - x + KEY_X, py - y + KEY_Y, c)
    return out


# ── Screen, lights, pad ──────────────────────────────────────────────────────
def screen(level):
    """CRT glass: rounded corners, darker toward the edges, a soft glare at the top left."""
    L = Layer()
    x, y, w, h = LAYOUT["glass"]
    ramp = [shade(c, level) for c in ("#030805", "#050c07", "#07110a", "#09150c", "#0b180e")]
    mask = Layer()
    rounded(mask, x, y, x + w - 1, y + h - 1, 6, "#ffffff")
    for (xx, yy) in mask.px:
        d = min(xx - x, x + w - 1 - xx, yy - y, y + h - 1 - yy)
        L.set(xx, yy, ramp[min(d // 3, 4)])
    for i in range(18):
        L.set(x + 4 + i, y + 4, shade("#1a2f20", level))
        if i < 10:
            L.set(x + 4, y + 5 + i // 2, shade("#14261a", level))
    return L


def lights(lit, colour="#46ff77"):
    L = Layer()
    lx, ly, _, _ = LAYOUT["lights"]
    for i in range(4):
        x = lx + i * 6
        if i < lit:
            L.rect(x, ly, x + 4, ly + 4, shade(colour, 0.6))
            L.rect(x + 1, ly + 1, x + 3, ly + 3, colour)
            L.set(x + 1, ly + 1, "#e8fff0" if colour == "#46ff77" else "#ffe8e8")
        else:
            L.rect(x, ly, x + 4, ly + 4, C["gold_lo"])
            L.rect(x + 1, ly + 1, x + 3, ly + 3, C["led_off"])
    return L


# ── Receipt ──────────────────────────────────────────────────────────────────
# Out of the slit and away up the top of the device: narrowing as it recedes, dark where it is
# still in the slit, leading edge first, printed lines across it.
RECEIPT_ROWS = 24
RECEIPT_NEAR_W, RECEIPT_FAR_W = 62, 52
RECEIPT_SHADE = (0.8, 0.55, 0.35, 0.2, 0.1)
PAPER = dict(edge="#8d877a", paper="#ece8dc", ink="#8d877a")
PRINT_DELAYS = [0.15, 0.17, 0.17, 0.17, 0.17, 0.17, 0.25]


def receipt_span(row):
    width = RECEIPT_NEAR_W + (RECEIPT_FAR_W - RECEIPT_NEAR_W) * row / (RECEIPT_ROWS - 1)
    mid = LAYOUT["slit"][0] + LAYOUT["slit"][2] / 2
    return round(mid - width / 2), round(mid + width / 2) - 1


def receipt(out):
    L = Layer()
    out = min(out, RECEIPT_ROWS)
    base = LAYOUT["slit"][1] + 1
    for row in range(out):
        x0, x1 = receipt_span(row)
        v = 1 - (out - row - 0.5) / RECEIPT_ROWS
        printed = 0.15 < v < 0.9 and int(v * RECEIPT_ROWS) % 3 == 0
        y = base - row
        for x in range(x0, x1 + 1):
            u = (x - x0 + 0.5) / (x1 - x0 + 1)
            if x in (x0, x1) or row == out - 1:
                c = PAPER["edge"]
            elif printed and 0.12 < u < (0.88 if int(v * RECEIPT_ROWS) % 2 else 0.6):
                c = PAPER["ink"]
            else:
                c = PAPER["paper"]
            L.set(x, y, shade(c, 1 - (RECEIPT_SHADE[row] if row < len(RECEIPT_SHADE) else 0)))
    return L


# ── Item sprite ──────────────────────────────────────────────────────────────
# A handheld TPV: receipt out of a wide printer head, the screen, a keypad tapering to the grip.
# Lit from the top left like the other CMU devices: outline, highlight edge, shadowed right side.
ITEM = dict(O="#141517", D="#1f2124", M="#2e3135", m="#3a3d42", L="#565a60", B="#0d0e10", G="#0f2a17",
            g="#39d36a", Y="#e0b24a", y="#b8892a", w="#7d5a14", k="#050505", P="#ece8dc", p="#c9c3b3",
            i="#8d877a", T="#a3a8ae", t="#5f646a", R="#c0392b", A="#d4a72c", N="#3fa34d")
ICON = [
    "................",
    "................",
    "................",
    "...OOOkkkkkOOO..",
    "..OYYYYYYYYYYyO.",
    ".OYyyyyyyyyyyywO",
    ".OYywywywyyyyywO",
    ".OYyyyyyyyyyyywO",
    ".OwwwwwwwwwwwwwO",
    ".OLMMMMMMMMMMmDO",
    ".OLBBBBBBBBBBmDO",
    ".OLBGggggggGBmDO",
    ".OLBGGGGGGGGBmDO",
    ".OLBGgggggGGBmDO",
    ".OLBGGGGGGGGBmDO",
    ".OLBGggggGGGBmDO",
    ".OLBBBBBBBBBBmDO",
    ".OLMMMMMMMMMMmDO",
    ".OLmTtmTtmTtmmDO",
    ".OLmmmmmmmmmmmDO",
    ".OLmTtmTtmTtmmDO",
    ".OLmmmmmmmmmmmDO",
    ".OLmTtmTtmTtmmDO",
    ".OLmmmmmmmmmmmDO",
    ".OLmRtmAtmNtmmDO",
    ".OLMMMMMMMMMMmDO",
    "..ODDDDDDDDDDDO.",
    "...OOOOOOOOOOO..",
]
ICON_AT = (7, 2)


def item_icon():
    L = Layer(32, 32)
    ox, oy = ICON_AT
    for y, row in enumerate(ICON):
        for x, key in enumerate(row):
            if key != ".":
                L.set(ox + x, oy + y, ITEM[key])
    return L


ITEM_PAPER = ["pPpPp", "PPPPP", "PiiiP"]
ITEM_PAPER_AT = (13, 2)
ITEM_PRINT_DELAYS = [0.4, 0.4, 0.45]


def item_receipt(rows):
    """The receipt `rows` rows out of the top slit, leading edge first."""
    L = Layer(32, 32)
    ox, oy = ITEM_PAPER_AT
    shown = ITEM_PAPER[:rows]
    for y, row in enumerate(shown):
        for x, key in enumerate(row):
            if key != ".":
                L.set(ox + x, oy + len(ITEM_PAPER) - rows + y, ITEM[key])
    return L


def item_screen():
    """The lit screen, drawn unshaded over the icon so it glows in the dark."""
    L = Layer(32, 32)
    ox, oy = ICON_AT
    for y, row in enumerate(ICON):
        for x, key in enumerate(row):
            if key in "Gg":
                L.set(ox + x, oy + y, "#1f6b38" if key == "G" else "#46ff77")
    return L


# In-hand frames, south / north / east / west, placed like the other handheld devices.
INHAND_PAL = dict(D="#141517", M="#2e3135", m="#3a3d42", l="#565a60", L="#7a7f86", G="#39d36a",
                  W="#ece8dc", Y="#e0b24a", y="#b8892a")
INHAND_LEFT = [
    ((16, 12), ["..WW..",
                ".DDDD.",
                "DYYYYD",
                "DyyyyD",
                "DGGGMD",
                "DGGGMD",
                "DlLlLD",
                "DLlLlD",
                "DmmmmD",
                ".DDDD."]),
    ((9, 15), [".W",
               ".y",
               ".y",
               "..",
               "..",
               "..",
               ".L",
               "DD"]),
    ((20, 11), ["....WW",
                "...DDY",
                "..DYyD",
                ".DGYyD",
                "DLGMMD",
                "LDMMD.",
                ".MDD..",
                ".MD...",
                ".D...."]),
    ((11, 13), ["WW.....",
                "YDD....",
                "DyYD...",
                "DyYGD..",
                "DMMGLD.",
                ".DMMDLD",
                "..DDMl.",
                "...DMM.",
                "....DD."]),
]


def mirror(frames, positions):
    """The right hand: each left frame flipped; east and west swap views."""
    flipped = [[row[::-1] for row in rows] for _, rows in frames]
    return list(zip(positions, [flipped[0], flipped[1], flipped[3], flipped[2]]))


INHAND_RIGHT = mirror(INHAND_LEFT, [(10, 12), (21, 15), (14, 13), (6, 11)])


def inhand(side):
    frames = INHAND_LEFT if side == "left" else INHAND_RIGHT
    sheet = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    for d, ((ox, oy), rows) in enumerate(frames):
        L = Layer(32, 32)
        for y, row in enumerate(rows):
            for x, key in enumerate(row):
                if key != ".":
                    L.set(ox + x, oy + y, INHAND_PAL[key])
        sheet.paste(L.image(), ((d % 2) * 32, (d // 2) * 32))
    return sheet


# ── Output ───────────────────────────────────────────────────────────────────
def write_rsi(path, size, states):
    path.mkdir(parents=True, exist_ok=True)
    for old in path.glob("*.png"):
        old.unlink()
    meta = {"version": 1, "license": LICENSE, "copyright": COPYRIGHT,
            "size": {"x": size[0], "y": size[1]}, "states": []}
    for state in states:
        name, frames, delays = state[:3]
        directions = state[3] if len(state) > 3 else 1
        if isinstance(frames, Image.Image):
            frames.save(path / f"{name}.png")
        else:
            sheet = Image.new("RGBA", (size[0] * len(frames), size[1]), (0, 0, 0, 0))
            for i, frame in enumerate(frames):
                sheet.paste(frame, (i * size[0], 0))
            sheet.save(path / f"{name}.png")
        entry = {"name": name}
        if directions > 1:
            entry["directions"] = directions
        if delays:
            entry["delays"] = [delays]
        meta["states"].append(entry)
    (path / "meta.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8", newline="\n")


def crop(layer, rect):
    return layer.image(rect)


def export():
    WINDOW_ART.mkdir(parents=True, exist_ok=True)
    draw_body().image().save(WINDOW_ART / "terminal_base.png")

    key_rect0 = (KEY_X, KEY_Y, KEY_W, KEY_H)
    key_states = []
    for i, (label, _, _) in enumerate(KEYPAD):
        for state in ("on", "off", "hover", "pressed"):
            key_states.append((f"{label}_{state}", [crop(key_layer(i, state), key_rect0)], None))
        if label == "enter":
            frames = [crop(key_layer(i, s), key_rect0) for s in ("hover", "on")]
            key_states.append(("enter_ready", frames, [0.5, 0.5]))
    write_rsi(WINDOW_ART / "terminal_keys.rsi", (KEY_W, KEY_H), key_states)

    glass = LAYOUT["glass"]
    write_rsi(WINDOW_ART / "terminal_screen.rsi", glass[2:], [
        ("on", [crop(screen(1.0), glass)], None),
        ("power_on", [crop(screen(level), glass) for level in (0.0, 2.5, 1.6, 1.0)], [0.15, 0.08, 0.1, 0.1]),
    ])

    lr = LAYOUT["lights"]
    write_rsi(WINDOW_ART / "terminal_lights.rsi", lr[2:], [
        ("off", [crop(lights(0), lr)], None),
        ("reading", [crop(lights(n), lr) for n in (1, 2, 3, 4)], [0.12, 0.12, 0.12, 0.3]),
        ("approved", [crop(lights(4), lr)], None),
        ("declined", [crop(lights(4, "#ff4e5e"), lr), crop(lights(0), lr)], [0.25, 0.25]),
    ])

    pr = LAYOUT["pad"]
    write_rsi(WINDOW_ART / "terminal_pad.rsi", pr[2:], [
        ("ready", [crop(pad_symbol("#46ff77"), pr), crop(pad_symbol("#1f9c43"), pr)], [0.5, 0.5]),
    ])

    rr = LAYOUT["receipt"]
    feed = [3, 7, 10, 14, 17, 21, RECEIPT_ROWS]
    write_rsi(WINDOW_ART / "terminal_receipt.rsi", rr[2:], [
        ("print", [crop(receipt(n), rr) for n in feed], PRINT_DELAYS),
        ("presented", [crop(receipt(RECEIPT_ROWS), rr)], None),
        ("take", [crop(receipt(0), rr)], [0.05]),
    ])

    write_rsi(ITEM_RSI, (32, 32), [
        ("icon", [item_icon().image()], None),
        ("screen", [item_screen().image()], None),
        ("receipt_print", [item_receipt(n).image() for n in (1, 2, 3)], ITEM_PRINT_DELAYS),
        ("receipt", [item_receipt(3).image()], None),
        ("inhand-left", inhand("left"), None, 4),
        ("inhand-right", inhand("right"), None, 4),
    ])


if __name__ == "__main__":
    export()
    print("window art ->", WINDOW_ART)
    print("item sprite ->", ITEM_RSI)
